export interface AdminModuleDefinition {
  slug: string;
  title: string;
  description: string;
  quickActions: string[];
  primaryMetrics: Array<{ label: string; value: string }>;
}

export const adminModules: AdminModuleDefinition[] = [
  { slug: 'programs', title: 'Programs', description: 'Create, publish, and monitor all Spotlight programs and lifecycle states.', quickActions: ['Create Program', 'Publish Program', 'Duplicate Program', 'Export Program Data'], primaryMetrics: [{ label: 'Active Programs', value: '12' }, { label: 'Draft Programs', value: '5' }, { label: 'Closed Programs', value: '9' }] },
  { slug: 'contests', title: 'Contests', description: 'Manage contest setup, registration windows, voting and result publication.', quickActions: ['Create Contest', 'Pause Voting', 'Lock Results', 'Generate Contest Report'], primaryMetrics: [{ label: 'Active Contests', value: '18' }, { label: 'Voting Live', value: '7' }, { label: 'Completed', value: '34' }] },
  { slug: 'film-academy', title: 'Film Academy', description: 'Handle academy intakes, classes, projects, facilitators and certificates.', quickActions: ['Create Intake', 'Assign Facilitators', 'Track Assignments', 'Issue Certificates'], primaryMetrics: [{ label: 'Active Batches', value: '4' }, { label: 'Students', value: '182' }, { label: 'Projects', value: '41' }] },
  { slug: 'sme-pitch', title: 'SME Pitch', description: 'Review startup submissions, assign judges and publish investor-ready finalists.', quickActions: ['Create Pitch Round', 'Assign Judges', 'Publish Finalists', 'Export Investor Report'], primaryMetrics: [{ label: 'Applications', value: '263' }, { label: 'Shortlisted', value: '48' }, { label: 'Investor Ready', value: '15' }] },
  { slug: 'applicants', title: 'Applicants', description: 'Unified application queue across all programs with advanced filtering and stage actions.', quickActions: ['Review Applications', 'Request Info', 'Approve', 'Bulk Export'], primaryMetrics: [{ label: 'Pending Review', value: '327' }, { label: 'Approved', value: '1042' }, { label: 'Rejected', value: '226' }] },
  { slug: 'contestants', title: 'Contestants', description: 'Manage contestant profiles, stage transitions, publishing and visibility controls.', quickActions: ['Add Contestant', 'Feature Contestant', 'Move Stage', 'Publish Profile'], primaryMetrics: [{ label: 'Active Contestants', value: '689' }, { label: 'Featured', value: '57' }, { label: 'Disqualified', value: '14' }] },
  { slug: 'voting', title: 'Voting', description: 'Control voting rounds, monitor suspicious trends and publish leaderboard updates.', quickActions: ['Open Voting', 'Pause Voting', 'Investigate Spikes', 'Export Vote Log'], primaryMetrics: [{ label: 'Total Votes', value: '5.2M' }, { label: 'Paid Vote Revenue', value: 'NGN 92.4M' }, { label: 'Alerts', value: '11' }] },
  { slug: 'stages-evictions', title: 'Stages & Evictions', description: 'Configure rounds, automate qualifiers and enforce auditable eviction decisions.', quickActions: ['Create Stage', 'Auto Qualify', 'Manual Override', 'Publish Stage Result'], primaryMetrics: [{ label: 'Active Stages', value: '23' }, { label: 'Eviction Rounds', value: '6' }, { label: 'Overrides', value: '3' }] },
  { slug: 'judges-scores', title: 'Judges & Scores', description: 'Assign judges, configure rubrics and combine weighted score outputs.', quickActions: ['Add Judge', 'Assign Rubric', 'Lock Scores', 'Publish Combined Result'], primaryMetrics: [{ label: 'Assigned Judges', value: '71' }, { label: 'Pending Scorecards', value: '39' }, { label: 'Locked Rubrics', value: '12' }] },
  { slug: 'badges-referrals', title: 'Badges & Referrals', description: 'Manage contestant badges, referral programs and promotion assets.', quickActions: ['Create Badge', 'Assign Badge', 'Generate Badge Image', 'Review Referral Rewards'], primaryMetrics: [{ label: 'Badges Assigned', value: '1,324' }, { label: 'Referral Codes', value: '462' }, { label: 'Boosted Votes', value: '41K' }] },
  { slug: 'payments-finance', title: 'Payments & Finance', description: 'Track all financial transactions, verify settlements and process controlled refunds.', quickActions: ['Reconcile Settlements', 'Verify Payment', 'Process Refund', 'Export Finance Report'], primaryMetrics: [{ label: 'Gross Revenue', value: 'NGN 148.7M' }, { label: 'Failed Payments', value: '87' }, { label: 'Refunds', value: '22' }] },
  { slug: 'sponsors-partners', title: 'Sponsors & Partners', description: 'Manage sponsor contracts, deliverables and exposure reporting.', quickActions: ['Add Sponsor', 'Assign Deliverables', 'Upload Contract', 'Export Activation Report'], primaryMetrics: [{ label: 'Active Sponsors', value: '19' }, { label: 'Pending Deliverables', value: '13' }, { label: 'Completed Deliverables', value: '91' }] },
  { slug: 'events', title: 'Events', description: 'Plan auditions, showcases, finale nights and activation events with operational control.', quickActions: ['Create Event', 'Assign Venue', 'Assign Staff', 'Publish Schedule'], primaryMetrics: [{ label: 'Upcoming Events', value: '28' }, { label: 'Finale Events', value: '5' }, { label: 'Capacity Booked', value: '82%' }] },
  { slug: 'media-cms', title: 'Media & CMS', description: 'Publish stories, galleries, videos and program pages with SEO controls.', quickActions: ['Create Content', 'Schedule Publish', 'Upload Media', 'Archive Content'], primaryMetrics: [{ label: 'Published Items', value: '744' }, { label: 'Drafts', value: '39' }, { label: 'Featured Stories', value: '22' }] },
  { slug: 'notifications', title: 'Notifications', description: 'Send targeted communication across application, voting and event workflows.', quickActions: ['Send Broadcast', 'Schedule Notification', 'Template Library', 'Delivery Report'], primaryMetrics: [{ label: 'Sent Today', value: '12,340' }, { label: 'Delivery Rate', value: '97.3%' }, { label: 'Failed', value: '218' }] },
  { slug: 'reports-analytics', title: 'Reports & Analytics', description: 'Boardroom-grade exports for sponsors, ministries, investors and internal leadership.', quickActions: ['Generate Program Report', 'Generate Voting Report', 'Export PDF Pack', 'Schedule Weekly Pack'], primaryMetrics: [{ label: 'Reports Generated', value: '1,108' }, { label: 'Automated Schedules', value: '16' }, { label: 'Last Export', value: '2h ago' }] },
  { slug: 'users-roles', title: 'Users & Roles', description: 'Provision admin accounts, role permissions and sensitive access controls.', quickActions: ['Create Admin User', 'Assign Role', 'Revoke Access', 'Review Permission Matrix'], primaryMetrics: [{ label: 'Admin Users', value: '54' }, { label: 'Privileged Roles', value: '8' }, { label: 'Pending Invites', value: '4' }] },
  { slug: 'audit-logs', title: 'Audit Logs', description: 'Track immutable admin activity across approvals, overrides and finance actions.', quickActions: ['View Recent Events', 'Filter High Risk Actions', 'Export Audit Trail', 'Compliance Snapshot'], primaryMetrics: [{ label: 'Events (30d)', value: '18,420' }, { label: 'High Risk Actions', value: '39' }, { label: 'Exports', value: '12' }] },
  { slug: 'settings', title: 'Settings', description: 'Configure global platform defaults, upload limits, links and operational controls.', quickActions: ['Update Site Settings', 'Configure Voting Defaults', 'Toggle Maintenance', 'Save Security Settings'], primaryMetrics: [{ label: 'Config Sets', value: '26' }, { label: 'Pending Changes', value: '3' }, { label: 'Last Updated', value: 'Today' }] },
];

export function getAdminModule(slug: string) {
  return adminModules.find((module) => module.slug === slug) || null;
}
