import React, { useEffect, useState } from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Target, Lightbulb, Trophy, Sparkles } from 'lucide-react-native';
import { Colors } from '@/constants/colors';
import { Typography } from '@/constants/typography';
import { Spacing } from '@/constants/spacing';
import { Radius } from '@/constants/radius';
import { shadow1, shadow3 } from '@/constants/shadows';
import { LinearGradient } from 'expo-linear-gradient';
import ScreenHeader from '@/components/ScreenHeader';
import PrimaryButton from '@/components/PrimaryButton';
import StateView from '@/components/StateView';
import OfflineBanner from '@/features/academy/components/OfflineBanner';
import QuestionCard from '@/features/academy/components/QuestionCard';
import ProgressBar from '@/features/academy/components/ProgressBar';
import { useAdaptiveSet, useSubmitPractice } from '@/features/academy/hooks';
import { formatPoints } from '@/features/academy/constants';
import type { AdaptiveSet, PracticeResult } from '@/features/academy/types';

/**
 * L11 — Adaptive practice. A personalised set targeting the learner's weakest
 * objectives (mastery < 60%), generated by POST /progression/practice/adaptive.
 * Reuses the Phase-1 QuestionCard + grading rail; mock-first, points queue offline.
 */
export default function AdaptivePractice() {
  const { subjectId } = useLocalSearchParams<{ subjectId?: string }>();
  const generate = useAdaptiveSet();
  const submit = useSubmitPractice();

  const [set, setSet] = useState<AdaptiveSet | null>(null);
  const [idx, setIdx] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string[]>>({});
  const [showHint, setShowHint] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [result, setResult] = useState<PracticeResult | null>(null);

  // Generate the adaptive set on mount.
  useEffect(() => {
    generate.mutate(subjectId, { onSuccess: (s) => setSet(s) });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [subjectId]);

  const list = set?.questions ?? [];
  const q = list[idx];
  const selected = q ? answers[q.id] ?? [] : [];
  const isLast = idx === list.length - 1;

  const select = (optionId: string) => {
    if (!q) return;
    setAnswers((a) => ({ ...a, [q.id]: q.type === 'multi' ? toggle(a[q.id] ?? [], optionId) : [optionId] }));
  };

  const checkOrNext = () => {
    if (!revealed) { setRevealed(true); return; }
    if (isLast) {
      submit.mutate(
        { answers: Object.entries(answers).map(([questionId, sel]) => ({ questionId, selected: sel })) },
        { onSuccess: (r) => setResult(r) },
      );
    } else {
      setIdx((i) => i + 1); setShowHint(false); setRevealed(false);
    }
  };

  if (generate.isPending && !set) return <SafeAreaView style={styles.safe} edges={['top']}><StateView kind="loading" message="Building your personalised set…" /></SafeAreaView>;
  if (generate.isError) return <SafeAreaView style={styles.safe} edges={['top']}><ScreenHeader title="Adaptive practice" /><StateView kind="error" title="Couldn’t build a set" message="Try again in a moment." actionLabel="Retry" onAction={() => generate.mutate(subjectId, { onSuccess: setSet })} /></SafeAreaView>;
  if (!set || !list.length) return <SafeAreaView style={styles.safe} edges={['top']}><ScreenHeader title="Adaptive practice" /><StateView kind="empty" title="Nothing to drill" message="You’re on top of your objectives. Check back after more practice." /></SafeAreaView>;

  if (result) {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <ScreenHeader title="Adaptive results" showBack={false} />
        <ScrollView contentContainerStyle={styles.scroll}>
          <View style={[styles.scoreCard, shadow1]}>
            <Trophy size={28} color={result.scorePct >= 70 ? Colors.gold : Colors.onSurfaceVariant} />
            <Text style={styles.scoreNum}>{result.scorePct}%</Text>
            <Text style={styles.scoreSub}>{result.correct} of {result.total} correct</Text>
            <View style={[styles.pointsPill, { backgroundColor: Colors.iconBgTeal }]}>
              <Text style={styles.pointsText}>+{formatPoints(result.pointsEarned)} earned</Text>
            </View>
            <Text style={styles.masteryNote}>{result.masteryGained ? `Mastery improved → ${result.newMastery}` : 'Keep going — remediation lessons recommended below.'}</Text>
          </View>

          <Text style={styles.section}>Worked explanations &amp; remediation</Text>
          {result.breakdown.map((b) => (
            <View key={b.questionId} style={[styles.reviewCard, shadow1, { borderLeftColor: b.correct ? Colors.teal : Colors.error }]}>
              <Text style={styles.reviewStem}>{b.stem}</Text>
              <Text style={[styles.reviewStatus, { color: b.correct ? Colors.teal : Colors.error }]}>{b.correct ? 'Correct' : 'Incorrect'}</Text>
              <Text style={styles.reviewExpl}>{b.explanation}</Text>
              {!b.correct ? (
                <Pressable style={styles.remediate} onPress={() => router.push('/learn/academy/subjects')}>
                  <Text style={styles.remediateText}>Revisit the lesson →</Text>
                </Pressable>
              ) : null}
            </View>
          ))}
        </ScrollView>
        <View style={styles.footer}><PrimaryButton label="Done" onPress={() => router.back()} /></View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <ScreenHeader title={`Adaptive · ${idx + 1}/${list.length}`} />
      <OfflineBanner />
      {idx === 0 && !revealed ? (
        <LinearGradient colors={Colors.gradientCard} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={[styles.why, shadow3]}>
          <View style={styles.whyTop}><Sparkles size={16} color={Colors.gold} /><Text style={styles.whyKicker}>PERSONALISED</Text></View>
          <Text style={styles.whyText}>{set.reason}</Text>
        </LinearGradient>
      ) : null}
      <View style={styles.progressWrap}><ProgressBar pct={(idx / list.length) * 100} /></View>
      <ScrollView contentContainerStyle={styles.scroll}>
        {q ? <QuestionCard question={q} selected={selected} onSelect={select} reveal={revealed} /> : null}
        {!revealed && q?.hint ? (
          showHint ? (
            <View style={styles.hintCard}><Lightbulb size={16} color={Colors.onWarning} /><Text style={styles.hintText}>{q.hint}</Text></View>
          ) : (
            <Pressable style={styles.hintBtn} onPress={() => setShowHint(true)}>
              <Lightbulb size={16} color={Colors.secondary} /><Text style={styles.hintBtnText}>Show hint</Text>
            </Pressable>
          )
        ) : null}
      </ScrollView>
      <View style={styles.footer}>
        <PrimaryButton
          label={!revealed ? 'Check' : isLast ? 'Finish' : 'Next question'}
          onPress={checkOrNext}
          disabled={!revealed && selected.length === 0}
          loading={submit.isPending}
        />
      </View>
    </SafeAreaView>
  );
}

function toggle(arr: string[], v: string): string[] {
  return arr.includes(v) ? arr.filter((x) => x !== v) : [...arr, v];
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  why: { marginHorizontal: Spacing.containerMargin, marginBottom: Spacing.sm, borderRadius: Radius.lg, padding: Spacing.md },
  whyTop: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  whyKicker: { ...Typography.labelSm, color: Colors.gold, letterSpacing: 1, fontWeight: '700' },
  whyText: { ...Typography.bodyMd, color: Colors.onPrimary, marginTop: 4 },
  progressWrap: { paddingHorizontal: Spacing.containerMargin, paddingBottom: Spacing.sm },
  scroll: { padding: Spacing.containerMargin, paddingBottom: Spacing.xxl, gap: Spacing.md },
  hintBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start' },
  hintBtnText: { ...Typography.labelMd, color: Colors.secondary },
  hintCard: { flexDirection: 'row', gap: Spacing.sm, backgroundColor: Colors.iconBgGold, padding: Spacing.md, borderRadius: Radius.md },
  hintText: { ...Typography.bodySm, color: Colors.onWarning, flex: 1 },
  footer: { padding: Spacing.containerMargin, borderTopWidth: 1, borderTopColor: Colors.outlineVariant },
  scoreCard: { alignItems: 'center', backgroundColor: Colors.surfaceContainerLowest, borderRadius: Radius.lg, padding: Spacing.lg, gap: 4 },
  scoreNum: { ...Typography.displayLg, color: Colors.onSurface, fontSize: 44, lineHeight: 50 },
  scoreSub: { ...Typography.bodyMd, color: Colors.onSurfaceVariant },
  pointsPill: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: Radius.full, marginTop: Spacing.sm },
  pointsText: { ...Typography.labelMd, color: Colors.teal, fontWeight: '700' },
  masteryNote: { ...Typography.bodySm, color: Colors.onSurfaceVariant, marginTop: Spacing.xs, textAlign: 'center' },
  section: { ...Typography.labelMd, color: Colors.onSurfaceVariant, textTransform: 'uppercase', marginTop: Spacing.lg, marginBottom: 2 },
  reviewCard: { backgroundColor: Colors.surfaceContainerLowest, borderRadius: Radius.lg, padding: Spacing.md, borderLeftWidth: 4 },
  reviewStem: { ...Typography.bodyMd, color: Colors.onSurface },
  reviewStatus: { ...Typography.labelSm, fontWeight: '700', marginTop: 4 },
  reviewExpl: { ...Typography.bodySm, color: Colors.onSurfaceVariant, marginTop: 4 },
  remediate: { marginTop: Spacing.sm },
  remediateText: { ...Typography.labelSm, color: Colors.secondary, fontWeight: '700' },
});
