// Package finance is the referral payout + treasury layer (FR-FIN, §6, §8B
// A-FIN): a Tier/KYC-gated, idempotent payout queue with approvals that posts to
// the beneficiary wallet via the finance ledger; reconciliation of the RB0 reward
// ledger against wallet postings; budget envelopes with burn monitoring + alerts;
// float positions; and reward-to-LTV reporting. Money is BIGINT kobo; every
// payout posting carries a unique Idempotency-Key.
package finance

import "time"

// Payout statuses.
const (
	PayoutQueued   = "queued"
	PayoutApproved = "approved"
	PayoutPaid     = "paid"
	PayoutRejected = "rejected"
	PayoutFailed   = "failed"
)

// Reconciliation statuses.
const (
	ReconOpen     = "open"
	ReconBalanced = "balanced"
	ReconVariance = "variance"
)

// Payout is a payout-queue row.
type Payout struct {
	ID            string     `json:"id"`
	BeneficiaryID string     `json:"beneficiary_id"`
	RewardID      string     `json:"reward_id,omitempty"`
	AmountKobo    int64      `json:"amount_kobo"`
	Currency      string     `json:"currency"`
	Status        string     `json:"status"`
	RequestedBy   string     `json:"requested_by,omitempty"`
	ApprovedBy    string     `json:"approved_by,omitempty"`
	LedgerEntryID string     `json:"ledger_entry_id,omitempty"`
	RejectReason  string     `json:"reject_reason,omitempty"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	DecidedAt     *time.Time `json:"decided_at,omitempty"`
}

// PayoutRequest queues a payout. IdempotencyKey is required (one payout per key).
type PayoutRequest struct {
	BeneficiaryID  string `json:"beneficiary_id"`
	RewardID       string `json:"reward_id"`
	AmountKobo     int64  `json:"amount_kobo"`
	Currency       string `json:"currency"`
	IdempotencyKey string `json:"idempotency_key"`
}

// Reconciliation is a recon snapshot row.
type Reconciliation struct {
	ID             string    `json:"id"`
	PeriodStart    time.Time `json:"period_start"`
	PeriodEnd      time.Time `json:"period_end"`
	LedgerPaidKobo int64     `json:"ledger_paid_kobo"`
	WalletPaidKobo int64     `json:"wallet_paid_kobo"`
	VarianceKobo   int64     `json:"variance_kobo"`
	Status         string    `json:"status"`
	CreatedBy      string    `json:"created_by,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
}

// Budget is a budget envelope with burn tracking.
type Budget struct {
	ID                string     `json:"id"`
	Scope             string     `json:"scope"`
	ScopeRef          string     `json:"scope_ref,omitempty"`
	BudgetKobo        int64      `json:"budget_kobo"`
	SpentKobo         int64      `json:"spent_kobo"`
	AlertThresholdPct int        `json:"alert_threshold_pct"`
	PeriodStart       *time.Time `json:"period_start,omitempty"`
	PeriodEnd         *time.Time `json:"period_end,omitempty"`
	Active            bool       `json:"active"`
	BurnPct           int        `json:"burn_pct"`
	AlertTriggered    bool       `json:"alert_triggered"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// BudgetInput creates/updates a budget envelope.
type BudgetInput struct {
	Scope             string `json:"scope"`
	ScopeRef          string `json:"scope_ref"`
	BudgetKobo        int64  `json:"budget_kobo"`
	AlertThresholdPct *int   `json:"alert_threshold_pct"`
}

// Float is a float / liability snapshot.
type Float struct {
	ID            string    `json:"id"`
	PositionKobo  int64     `json:"position_kobo"`
	LiabilityKobo int64     `json:"liability_kobo"`
	FundedKobo    int64     `json:"funded_kobo"`
	AsOf          time.Time `json:"as_of"`
	Note          string    `json:"note,omitempty"`
	CreatedAt     time.Time `json:"created_at"`
}

// RewardToLTV is the reward-to-LTV summary (A-FIN / A-BI). LTV is the verified
// activity value generated by referred users vs reward spend.
type RewardToLTV struct {
	RewardSpentKobo  int64   `json:"reward_spent_kobo"`
	ReferredLTVKobo  int64   `json:"referred_ltv_kobo"`
	RatioBps         int64   `json:"ratio_bps"` // LTV / spend in basis points
}
