#!/usr/bin/env python3
"""Nutrition Resolution Engine — composition_reference ingestion transformer.

Reads a food-composition CSV (WAFCT / NFCT / OFF / ...) and emits idempotent,
versioned INSERT statements for public.composition_reference.

Pure standard library (no third-party deps). See README.md for the runbook and
the expected column shape.

Idempotency: every row uses
    ON CONFLICT (food_code, source, prep_method, version) DO NOTHING
matching the table's UNIQUE constraint, so re-running an import is a no-op and a
correction ships as a NEW --version (additive-only — never mutate prior rows).
"""

import argparse
import csv
import sys

VALID_SOURCES = {"WAFCT", "NFCT", "OFF", "FALLBACK", "CUSTOM"}
VALID_PREP = {"raw", "boiled", "grilled", "stewed", "fried", "baked", "roasted"}

NUMERIC_COLS = [
    "energy_kcal", "protein_g", "carb_g", "sugar_g",
    "fat_g", "sat_fat_g", "fiber_g", "sodium_mg",
]
INSERT_COLS = ["food_code", "name", "source", "prep_method"] + NUMERIC_COLS + ["version"]


def sql_str(v: str) -> str:
    """Quote a SQL string literal, escaping single quotes."""
    return "'" + v.replace("'", "''") + "'"


def sql_num(v: str):
    """Return a numeric literal or NULL for an empty/invalid cell."""
    v = (v or "").strip()
    if v == "":
        return "NULL"
    try:
        return repr(float(v))
    except ValueError:
        return "NULL"


def norm_header(fieldnames):
    """Map lowercased header → actual header so lookups are case-insensitive."""
    return {(h or "").strip().lower(): h for h in (fieldnames or [])}


def transform(reader: csv.DictReader, version: int, out):
    hmap = norm_header(reader.fieldnames)
    for required in ("food_code", "name", "source"):
        if required not in hmap:
            sys.exit(f"error: required column '{required}' missing from CSV header")

    def cell(row, key):
        return (row.get(hmap.get(key, ""), "") or "").strip()

    rows_emitted = 0
    out.write("-- Generated by ingest_composition.py — composition_reference\n")
    out.write(f"-- version={version} (additive; ON CONFLICT DO NOTHING)\n")
    out.write("BEGIN;\n")
    out.write(
        "INSERT INTO public.composition_reference\n"
        "  (food_code, name, source, prep_method, energy_kcal, protein_g, carb_g, "
        "sugar_g, fat_g, sat_fat_g, fiber_g, sodium_mg, version)\nVALUES\n"
    )

    values = []
    for lineno, row in enumerate(reader, start=2):
        food_code = cell(row, "food_code")
        name = cell(row, "name")
        source = cell(row, "source").upper()
        if not food_code or not name or not source:
            sys.stderr.write(f"skip line {lineno}: missing food_code/name/source\n")
            continue
        if source not in VALID_SOURCES:
            sys.stderr.write(f"skip line {lineno}: invalid source {source!r}\n")
            continue
        prep = cell(row, "prep_method").lower() or "raw"
        if prep not in VALID_PREP:
            sys.stderr.write(f"skip line {lineno}: invalid prep_method {prep!r} — defaulting to 'raw'\n")
            prep = "raw"

        nums = [sql_num(cell(row, c)) for c in NUMERIC_COLS]
        tuple_sql = "  (" + ", ".join(
            [sql_str(food_code), sql_str(name), sql_str(source), sql_str(prep)]
            + nums + [str(version)]
        ) + ")"
        values.append(tuple_sql)
        rows_emitted += 1

    if not values:
        sys.exit("error: no valid rows to emit")

    out.write(",\n".join(values))
    out.write(
        "\nON CONFLICT (food_code, source, prep_method, version) DO NOTHING;\n"
    )
    out.write("COMMIT;\n")
    sys.stderr.write(f"emitted {rows_emitted} composition_reference rows (version {version})\n")


def main():
    ap = argparse.ArgumentParser(description="Emit composition_reference INSERTs from a food-composition CSV.")
    ap.add_argument("csv_path", help="Path to the WAFCT/NFCT/... CSV file")
    ap.add_argument("--version", type=int, default=1,
                    help="Reference version to tag rows with (default 1; bump for a correction pass)")
    args = ap.parse_args()

    with open(args.csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        transform(reader, args.version, sys.stdout)


if __name__ == "__main__":
    main()
