// ── Association — Engagement mock dataset ─────────────────────────────────────

import type {
  Announcement,
  AppNotification,
  Meeting,
  Task,
  DocumentDetail,
} from '../types/engagement.types';

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann1',
    title: 'Annual dues deadline extended to 31 July',
    preview: 'The National Executive Council has approved a one-month extension for 2026 annual dues…',
    body:
      'The National Executive Council has approved a one-month extension for 2026 annual dues. All members now have until 31 July 2026 to settle their dues without incurring the late-payment penalty.\n\nMembers with outstanding balances after this date will have their membership cards restricted until payment is confirmed. Please use the in-app payment option for instant confirmation.',
    audience: 'All members',
    postedAt: '2026-06-18T10:00:00Z',
    author: 'National Secretariat',
    urgent: true,
    read: false,
    requiresAck: true,
    acknowledged: false,
    attachments: [{ id: 'a1', name: 'Dues-extension-circular.pdf', sizeLabel: '180 KB', kind: 'pdf' }],
    readCount: 1840,
    totalRecipients: 6120,
  },
  {
    id: 'ann2',
    title: 'Lagos Chapter CPD seminar — register now',
    preview: 'Earn 6 CPD points at the quarterly clinical update seminar holding at NMA House…',
    body:
      'Earn 6 CPD points at the quarterly clinical update seminar holding at NMA House, Ikeja on 12 July 2026. Topics include emergency cardiology and ethics in practice. Seats are limited to 200; registration closes 8 July.',
    audience: 'Lagos State Chapter',
    postedAt: '2026-06-15T08:30:00Z',
    author: 'Lagos Chapter Secretary',
    urgent: false,
    read: true,
    requiresAck: false,
    acknowledged: false,
    attachments: [],
    readCount: 920,
    totalRecipients: 6120,
  },
  {
    id: 'ann3',
    title: 'Welfare contribution for Dr. Adeyemi’s family',
    preview: 'The welfare committee is coordinating support following the passing of our colleague…',
    body:
      'The welfare committee is coordinating support following the passing of our colleague, Dr. Adeyemi. Members wishing to contribute can do so under Dues → Welfare contribution. The committee thanks everyone for their compassion.',
    audience: 'All members',
    postedAt: '2026-06-10T14:00:00Z',
    author: 'Welfare Committee',
    urgent: false,
    read: true,
    requiresAck: false,
    acknowledged: false,
    attachments: [],
    readCount: 3110,
    totalRecipients: 6120,
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', kind: 'payment', title: 'Dues reminder', body: '2026 annual dues of ₦20,000 are due in 41 days.', createdAt: '2026-06-19T09:00:00Z', read: false, route: '/association/dues' },
  { id: 'n2', kind: 'announcement', title: 'New announcement', body: 'Annual dues deadline extended to 31 July.', createdAt: '2026-06-18T10:05:00Z', read: false, route: '/association/announcements/ann1' },
  { id: 'n3', kind: 'meeting', title: 'Meeting reminder', body: 'Lagos Chapter Monthly General Meeting starts in 2 days.', createdAt: '2026-06-18T07:00:00Z', read: false, route: '/association/meetings/mtg1' },
  { id: 'n4', kind: 'task', title: 'Task assigned', body: 'You were assigned “Compile welfare disbursement report”.', createdAt: '2026-06-16T12:30:00Z', read: true, route: '/association/tasks/tk1' },
  { id: 'n5', kind: 'membership', title: 'Card updated', body: 'Your membership card was refreshed for 2026.', createdAt: '2026-06-12T16:00:00Z', read: true, route: '/association/card' },
  { id: 'n6', kind: 'document', title: 'Acknowledgement required', body: 'Please acknowledge the updated Code of Ethics.', createdAt: '2026-06-09T11:00:00Z', read: true, route: '/association/documents/doc5' },
];

export const MOCK_MEETINGS: Meeting[] = [
  {
    id: 'mtg1',
    title: 'Lagos Chapter Monthly General Meeting',
    mode: 'HYBRID',
    startsAt: '2026-06-28T16:00:00Z',
    endsAt: '2026-06-28T18:00:00Z',
    location: 'NMA House, Ikeja + Zoom',
    state: 'UPCOMING',
    rsvp: null,
    attendeeCount: 184,
    description: 'Monthly general meeting covering chapter finances, CPD planning, and welfare matters.',
    agenda: [
      { id: 'ag1', order: 1, title: 'Opening & adoption of agenda', durationMin: 10 },
      { id: 'ag2', order: 2, title: 'Treasurer’s report', durationMin: 25 },
      { id: 'ag3', order: 3, title: 'CPD seminar planning', durationMin: 30 },
      { id: 'ag4', order: 4, title: 'Welfare matters', durationMin: 20 },
      { id: 'ag5', order: 5, title: 'AOB & closing', durationMin: 15 },
    ],
    documents: [{ id: 'md1', name: 'May meeting minutes.pdf' }, { id: 'md2', name: 'Treasurer report Q2.pdf' }],
    checkedIn: false,
    minutesPublished: false,
    attendanceCode: 'SPOTLIGHT:MTG:mtg1:checkin',
  },
  {
    id: 'mtg2',
    title: 'Emergency Executive Council Meeting',
    mode: 'VIRTUAL',
    startsAt: '2026-06-22T19:00:00Z',
    endsAt: '2026-06-22T20:00:00Z',
    location: 'Zoom',
    state: 'UPCOMING',
    rsvp: 'YES',
    attendeeCount: 22,
    description: 'Emergency session to review the dues extension circular.',
    agenda: [
      { id: 'ag6', order: 1, title: 'Dues extension review', durationMin: 40 },
      { id: 'ag7', order: 2, title: 'Resolutions', durationMin: 20 },
    ],
    documents: [],
    checkedIn: false,
    minutesPublished: false,
    attendanceCode: 'SPOTLIGHT:MTG:mtg2:checkin',
  },
  {
    id: 'mtg3',
    title: 'May Monthly General Meeting',
    mode: 'PHYSICAL',
    startsAt: '2026-05-31T16:00:00Z',
    endsAt: '2026-05-31T18:00:00Z',
    location: 'NMA House, Ikeja',
    state: 'PAST',
    rsvp: 'YES',
    attendeeCount: 203,
    description: 'Routine monthly general meeting.',
    agenda: [{ id: 'ag8', order: 1, title: 'Standard agenda', durationMin: 120 }],
    documents: [{ id: 'md3', name: 'April minutes.pdf' }],
    checkedIn: true,
    minutesPublished: true,
    attendanceCode: 'SPOTLIGHT:MTG:mtg3:checkin',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'tk1',
    title: 'Compile welfare disbursement report',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: '2026-06-25T23:59:59Z',
    assigneeName: 'Dr. Chidinma Okeke',
    committee: 'Welfare',
    description: 'Prepare the Q2 welfare disbursement report for review at the next general meeting. Include all approved cases and remaining balance.',
    checklist: [
      { id: 'c1', label: 'Collate approved cases', done: true },
      { id: 'c2', label: 'Reconcile disbursed amounts', done: true },
      { id: 'c3', label: 'Draft summary memo', done: false },
      { id: 'c4', label: 'Submit for chairperson review', done: false },
    ],
    comments: [
      { id: 'cm1', author: 'Welfare Chair', body: 'Please include the Adeyemi case in the summary.', createdAt: '2026-06-17T09:00:00Z' },
    ],
    createdBy: 'Welfare Chair',
    meetingId: 'mtg3',
    meetingTitle: 'May Monthly General Meeting',
  },
  {
    id: 'tk2',
    title: 'Confirm CPD seminar venue booking',
    status: 'ASSIGNED',
    priority: 'MEDIUM',
    dueDate: '2026-06-30T23:59:59Z',
    assigneeName: 'Dr. Chidinma Okeke',
    committee: 'Events',
    description: 'Confirm the NMA House hall booking for the 12 July CPD seminar and arrange AV equipment.',
    checklist: [],
    comments: [],
    createdBy: 'Chapter Secretary',
    meetingId: null,
    meetingTitle: null,
  },
  {
    id: 'tk3',
    title: 'Submit annual practising licence',
    status: 'OVERDUE',
    priority: 'HIGH',
    dueDate: '2026-06-10T23:59:59Z',
    assigneeName: 'Dr. Chidinma Okeke',
    committee: null,
    description: 'Upload your renewed MDCN practising licence to keep your verification badge active.',
    checklist: [],
    comments: [],
    createdBy: 'Membership Officer',
    meetingId: null,
    meetingTitle: null,
  },
  {
    id: 'tk4',
    title: 'Review draft chapter budget',
    status: 'COMPLETED',
    priority: 'LOW',
    dueDate: '2026-06-05T23:59:59Z',
    assigneeName: 'Dr. Chidinma Okeke',
    committee: 'Finance',
    description: 'Review and sign off on the draft Q3 chapter budget.',
    checklist: [{ id: 'c5', label: 'Review line items', done: true }, { id: 'c6', label: 'Sign off', done: true }],
    comments: [],
    createdBy: 'Treasurer',
    meetingId: null,
    meetingTitle: null,
  },
];

export const MOCK_DOCUMENTS: DocumentDetail[] = [
  {
    id: 'doc1', title: 'NMA Constitution (2023 revision)', category: 'constitution', kind: 'pdf',
    sizeLabel: '1.2 MB', updatedAt: '2024-01-15T00:00:00Z', restricted: false, requiresAck: false, acknowledged: false,
    description: 'The governing constitution of the association.', version: 'v4',
    versionHistory: [
      { version: 'v4', date: '2024-01-15', note: '2023 AGM amendments' },
      { version: 'v3', date: '2019-03-01', note: 'Chapter structure update' },
    ],
    aiSummary: 'Defines membership categories, the national/state/local chapter hierarchy, election procedures, and disciplinary processes. Article 7 covers dues obligations; Article 12 covers suspension.',
    uploadedBy: 'National Secretariat',
  },
  {
    id: 'doc2', title: 'May General Meeting Minutes', category: 'minutes', kind: 'pdf',
    sizeLabel: '320 KB', updatedAt: '2026-06-02T00:00:00Z', restricted: false, requiresAck: false, acknowledged: false,
    description: 'Approved minutes of the May 2026 general meeting.', version: 'v1',
    versionHistory: [{ version: 'v1', date: '2026-06-02', note: 'Published after approval' }],
    aiSummary: 'Treasurer reported ₦4.2M collected in Q2. Council approved the dues extension and the CPD seminar budget of ₦850,000.',
    uploadedBy: 'Chapter Secretary',
  },
  {
    id: 'doc3', title: 'Q2 Financial Report', category: 'financial', kind: 'pdf',
    sizeLabel: '540 KB', updatedAt: '2026-06-08T00:00:00Z', restricted: false, requiresAck: false, acknowledged: false,
    description: 'Quarterly financial statement.', version: 'v2',
    versionHistory: [{ version: 'v2', date: '2026-06-08', note: 'Audited figures' }, { version: 'v1', date: '2026-06-05', note: 'Draft' }],
    aiSummary: null,
    uploadedBy: 'Treasurer',
  },
  {
    id: 'doc4', title: 'Membership Certificate', category: 'certificates', kind: 'pdf',
    sizeLabel: '90 KB', updatedAt: '2026-01-02T00:00:00Z', restricted: false, requiresAck: false, acknowledged: false,
    description: 'Your personal membership certificate.', version: 'v1',
    versionHistory: [{ version: 'v1', date: '2026-01-02', note: 'Issued for 2026' }],
    aiSummary: null,
    uploadedBy: 'Membership Officer',
  },
  {
    id: 'doc5', title: 'Code of Ethics (updated)', category: 'policy', kind: 'pdf',
    sizeLabel: '260 KB', updatedAt: '2026-06-09T00:00:00Z', restricted: false, requiresAck: true, acknowledged: false,
    description: 'Updated professional code of ethics — acknowledgement required.', version: 'v2',
    versionHistory: [{ version: 'v2', date: '2026-06-09', note: 'Social media conduct clause added' }],
    aiSummary: 'Adds guidance on social media conduct and patient confidentiality online. All members must acknowledge by 30 June.',
    uploadedBy: 'Ethics Committee',
  },
  {
    id: 'doc6', title: 'Executive Council Resolutions (restricted)', category: 'reports', kind: 'pdf',
    sizeLabel: '410 KB', updatedAt: '2026-06-11T00:00:00Z', restricted: true, requiresAck: false, acknowledged: false,
    description: 'Confidential — Executive Council members only.', version: 'v1',
    versionHistory: [{ version: 'v1', date: '2026-06-11', note: 'Confidential' }],
    aiSummary: null,
    uploadedBy: 'National Secretariat',
  },
];
