package repositories

import "spotlight/backend/internal/domain"

type StemRepository interface {
	GetOverview() (domain.StemOverview, error)
	ListSchools(limit int) ([]domain.StemSchool, error)
	CreateSchool(input domain.StemSchoolCreateInput) (domain.StemSchool, error)
	UpdateSchoolVerification(schoolID string, status string, reason string, actorID string) error
	GetSchoolDashboard(schoolID string) (domain.StemSchoolDashboard, error)
	ListSchoolProfiles(limit int) ([]domain.StemSchoolProfile, error)
	CreateSchoolProfile(input domain.StemSchoolProfileCreateInput) (domain.StemSchoolProfile, error)
	ListSchoolTeams(limit int) ([]domain.StemSchoolTeam, error)
	CreateSchoolTeam(input domain.StemSchoolTeamCreateInput) (domain.StemSchoolTeam, error)
	ListEmergingInnovators(limit int) ([]domain.StemEmergingInnovator, error)
	CreateEmergingInnovator(input domain.StemEmergingInnovatorCreateInput) (domain.StemEmergingInnovator, error)
	ListEmergingTeams(limit int) ([]domain.StemEmergingTeam, error)
	CreateEmergingTeam(input domain.StemEmergingTeamCreateInput) (domain.StemEmergingTeam, error)
	ListEmergingProjects(limit int) ([]domain.StemEmergingProject, error)
	CreateEmergingProject(input domain.StemEmergingProjectCreateInput) (domain.StemEmergingProject, error)
	ListContests(limit int) ([]domain.StemContest, error)
	CreateContest(input domain.StemContestCreateInput) (domain.StemContest, error)
	GetContestByID(contestID string) (domain.StemContest, error)
	ListLeaderboard(contestID string, limit int) ([]domain.StemLeaderboardEntry, error)
	ListLeaderboardSlices(contestID string, by string, limit int) ([]domain.StemLeaderboardSlice, error)
	ListSubmissions(limit int, status string) ([]domain.StemSubmission, error)
	UpdateSubmissionStatus(submissionID string, status string, reviewStage string) error
	UpsertJudgingScore(score domain.StemJudgingScore) (domain.StemJudgingScore, error)
	ListJudgingScores(applicationID string, limit int) ([]domain.StemJudgingScore, error)
	UpdateJudgingScoreReviewState(scoreID string, reviewStatus string, isLocked bool, lockReason string, lockedBy string) error
	CreateJudgingRubric(rubric domain.StemJudgingRubric, criteria []domain.StemJudgingCriterion) (domain.StemJudgingRubric, []domain.StemJudgingCriterion, error)
	ListJudgingRubrics(contestID string, limit int) ([]domain.StemJudgingRubric, error)
	ListJudgingCriteria(rubricID string, limit int) ([]domain.StemJudgingCriterion, error)
	CreateJudgeAssignment(assignment domain.StemJudgeAssignment) (domain.StemJudgeAssignment, error)
	ListJudgeAssignments(contestID string, applicationID string, judgeUserID string, limit int) ([]domain.StemJudgeAssignment, error)
	UpdateJudgeAssignmentConflict(assignmentID string, hasConflict bool, conflictReason string, status string) error
	UpsertVotingRule(rule domain.StemVotingRule) (domain.StemVotingRule, error)
	ListVotingRules(contestID string, limit int) ([]domain.StemVotingRule, error)
	CreateVotePackage(pkg domain.StemVotePackage) (domain.StemVotePackage, error)
	ListVotePackages(contestID string, limit int) ([]domain.StemVotePackage, error)
	CreateVoteTransaction(tx domain.StemVoteTransaction) (domain.StemVoteTransaction, error)
	ListVoteTransactions(contestID string, limit int) ([]domain.StemVoteTransaction, error)
	CreateBootcampCohort(cohort domain.StemBootcampCohort) (domain.StemBootcampCohort, error)
	ListBootcampCohorts(contestID string, limit int) ([]domain.StemBootcampCohort, error)
	CreateBootcampTask(task domain.StemBootcampTask) (domain.StemBootcampTask, error)
	ListBootcampTasks(cohortID string, limit int) ([]domain.StemBootcampTask, error)
	UpsertBootcampScore(score domain.StemBootcampScore) (domain.StemBootcampScore, error)
	ListBootcampScores(cohortID string, applicationID string, limit int) ([]domain.StemBootcampScore, error)
	CreateSponsor(sponsor domain.StemSponsor) (domain.StemSponsor, error)
	ListSponsors(limit int) ([]domain.StemSponsor, error)
	CreateCertificate(cert domain.StemCertificate) (domain.StemCertificate, error)
	ListCertificates(limit int) ([]domain.StemCertificate, error)
	CreateBadge(badge domain.StemBadge) (domain.StemBadge, error)
	ListBadges(limit int) ([]domain.StemBadge, error)
	AwardBadge(award domain.StemBadgeAward) (domain.StemBadgeAward, error)
	ListBadgeAwards(applicationID string, limit int) ([]domain.StemBadgeAward, error)
	GetReportSummary() (domain.StemReportSummary, error)
	GetReportBuckets(kind string, contestID string, limit int) ([]domain.StemReportBucket, error)
}
