const fs = require('fs');
const path = require('path');
const {
  withAppBuildGradle,
  withDangerousMod,
  withGradleProperties,
} = require('expo/config-plugins');

// android/ is gitignored and regenerated by `expo prebuild`, so every setting
// below lives here instead of in the generated files.
const GRADLE_PROPERTIES = [
  // Pinned deliberately. The SDK 54 prebuild template writes
  // newArchEnabled=true, but this app targets the old architecture (its Android
  // releases have always shipped old-arch: only fbjni/c++_shared/
  // hermes/hermestooling are pickFirst-protected, not libjsi/libreactnative).
  // `expo prebuild --clean` regenerates gradle.properties and silently flipped
  // this to true once already; keep the pin here rather than in the generated
  // file. Also note the ABI filter below depends on RNGP's old-arch early
  // return, so flipping this changes how ABI filtering works too.
  ['newArchEnabled', 'false'],
  // Hand-set in gradle.properties before this plugin existed: with minify on,
  // lintVitalAnalyzeRelease runs in-process and OOM'd Metaspace at the 512m
  // default, failing 9 library modules.
  ['org.gradle.jvmargs', '-Xmx4096m -XX:MaxMetaspaceSize=2048m'],
  ['org.gradle.java.installations.auto-download', 'false'],
  [
    'org.gradle.java.installations.paths',
    '/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home',
  ],
];

// AssetSourceResolver turns `require('./img.png')` into a resource looked up by
// NAME at runtime (resourceIdentifierWithoutScale / file:///android_res/...), so
// R8's resource shrinker sees no code reference and strips every image and font.
// Images land in drawable-<density>/, everything else (fonts, ...) in raw/.
const KEEP_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@drawable/*,@raw/*" />
`;

function withGradleProperty(config, key, value) {
  return withGradleProperties(config, (config) => {
    const props = config.modResults;
    const existing = props.find((item) => item.type === 'property' && item.key === key);
    if (existing) {
      existing.value = value;
    } else {
      props.push({ type: 'property', key, value });
    }
    return config;
  });
}

function withLocaleFilter(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy' || config.modResults.contents.includes('localeFilters')) {
      return config;
    }
    // English-only app: without this, AAPT2 packages every locale that
    // AndroidX/MLKit/MapLibre resources ship into resources.arsc.
    config.modResults.contents = config.modResults.contents.replace(
      /\nandroid \{/,
      "\nandroid {\n    androidResources {\n        localeFilters.add('en')\n    }",
    );
    return config;
  });
}

// With newArchEnabled=false the RN gradle plugin returns early from
// NdkConfiguratorUtils.configureReactNativeNdk, so `reactNativeArchitectures`
// (gradle.properties, -P, or expo-build-properties buildArchs) never reaches
// ndk.abiFilters and all four ABIs ship in every release APK. Filter at the
// variant level instead: release keeps only the ABIs in `releaseAbis`
// (default arm64-v8a), debug stays untouched so the x86_64 emulator works.
// build-apk.sh passes -PreleaseAbis="$REACT_NATIVE_ARCHS".
//
// Two things are needed, both verified against the produced APK:
//  1. MergeNativeLibsTask only honours packaging.jniLibs excludes/pickFirsts
//     (it has no ABI input), so the dropped ABIs are excluded by directory.
//  2. RNGP registers ABI-agnostic pickFirsts for the libs Hermes/fbjni pull in
//     (NdkConfiguratorUtils old-arch branch), and pickFirsts outrank excludes.
//     Without step 2 those four libs ship for every ABI anyway (~10 MiB).
const ALL_ANDROID_ABIS = ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'];
const RN_OLD_ARCH_PICK_FIRSTS = [
  'libfbjni.so',
  'libc++_shared.so',
  'libhermes.so',
  'libhermestooling.so',
];

const ABI_FILTER_MARKER = '// withAndroidSizeOptimizations: release ABI filter';

function withReleaseAbiFilter(config) {
  return withAppBuildGradle(config, (config) => {
    if (
      config.modResults.language !== 'groovy' ||
      config.modResults.contents.includes(ABI_FILTER_MARKER)
    ) {
      return config;
    }
    config.modResults.contents += `
${ABI_FILTER_MARKER}
def sizeOptReleaseAbis = (findProperty("releaseAbis") ?: "arm64-v8a").toString().split(",")*.trim().findAll { it }
def sizeOptDroppedAbis = ${JSON.stringify(ALL_ANDROID_ABIS)}.findAll { !(it in sizeOptReleaseAbis) }
println "withAndroidSizeOptimizations: release ABIs " + sizeOptReleaseAbis + ", dropping " + sizeOptDroppedAbis
androidComponents {
    onVariants(selector().withBuildType("release"), { variant ->
        variant.packaging.jniLibs.excludes.addAll(sizeOptDroppedAbis.collect { "lib/" + it + "/**" })
        variant.packaging.jniLibs.pickFirsts.set(
            sizeOptReleaseAbis.collectMany { abi ->
                ${JSON.stringify(RN_OLD_ARCH_PICK_FIRSTS)}.collect { "lib/" + abi + "/" + it }
            }
        )
    })
}
`;
    return config;
  });
}

function withResourceKeepFile(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const rawDir = path.join(
        config.modRequest.platformProjectRoot,
        'app/src/main/res/raw',
      );
      await fs.promises.mkdir(rawDir, { recursive: true });
      await fs.promises.writeFile(path.join(rawDir, 'keep.xml'), KEEP_XML);
      return config;
    },
  ]);
}

module.exports = function withAndroidSizeOptimizations(config) {
  for (const [key, value] of GRADLE_PROPERTIES) {
    config = withGradleProperty(config, key, value);
  }
  config = withLocaleFilter(config);
  config = withReleaseAbiFilter(config);
  return withResourceKeepFile(config);
};
