const { withAppBuildGradle } = require('expo/config-plugins');

// android/ is gitignored and regenerated by `expo prebuild`, so the release
// signing config has to be re-injected on every prebuild. Without it the
// template signs release with app/debug.keystore (CN=Android Debug), which
// Play rejects and which cannot upgrade an install signed by a real key.
//
// Credentials are deliberately NOT baked in here: the appended block reads them
// at gradle configuration time from project properties (-P, gradle.properties)
// or the environment, so the keystore password never lands in a generated file.
// build-apk.sh sources $HOME/.android-keystores/paymax-release.properties and
// refuses to build without it.
const SIGNING_MARKER = '// withAndroidReleaseSigning: release signing config';

const SIGNING_CREDENTIAL_KEYS = [
  'PAYMAX_RELEASE_STORE_FILE',
  'PAYMAX_RELEASE_STORE_PASSWORD',
  'PAYMAX_RELEASE_KEY_ALIAS',
  'PAYMAX_RELEASE_KEY_PASSWORD',
];

const SIGNING_BLOCK = `
${SIGNING_MARKER}
def releaseSigningValue = { String name -> project.findProperty(name) ?: System.getenv(name) }
def releaseStoreFile = releaseSigningValue("PAYMAX_RELEASE_STORE_FILE") ? file(releaseSigningValue("PAYMAX_RELEASE_STORE_FILE")) : null
def releaseSigningReady = releaseStoreFile?.exists() && ${JSON.stringify(SIGNING_CREDENTIAL_KEYS)}
    .collect { releaseSigningValue(it) }.every { it }

if (releaseSigningReady) {
    println "withAndroidReleaseSigning: release builds signed with " + releaseStoreFile + " (alias " + releaseSigningValue("PAYMAX_RELEASE_KEY_ALIAS") + ")"
    android {
        signingConfigs {
            release {
                storeFile releaseStoreFile
                storePassword releaseSigningValue("PAYMAX_RELEASE_STORE_PASSWORD")
                keyAlias releaseSigningValue("PAYMAX_RELEASE_KEY_ALIAS")
                keyPassword releaseSigningValue("PAYMAX_RELEASE_KEY_PASSWORD")
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
} else {
    println "withAndroidReleaseSigning: no usable release signing credentials (${SIGNING_CREDENTIAL_KEYS.join(', ')}) — release builds stay debug-signed."
}
`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (
      config.modResults.language !== 'groovy' ||
      config.modResults.contents.includes(SIGNING_MARKER)
    ) {
      return config;
    }
    config.modResults.contents += SIGNING_BLOCK;
    return config;
  });
};
