// ── Insurance — Mock catalog & state (NG micro-insurance, both rails) ────────
// Realistic illustrative products. Underwriter/aggregator surfaced on every
// product (PRD §5 disclosure). Money in kobo. NOT a source of truth — the live
// backend supersedes this once USE_MOCK=false.

import type {
  InsuranceProduct,
  KycProfile,
  Policy,
} from '../types';

const day = 24 * 60 * 60 * 1000;
const iso = (offsetDays: number) => new Date(Date.now() + offsetDays * day).toISOString();

// ── KYC profile (prefills the schema-driven quote form; PRD §6.1) ────────────
export const MOCK_KYC: KycProfile = {
  tier: 'TIER_1',
  fullName: 'Adaeze Okonkwo',
  dateOfBirth: '1994-03-12',
  phone: '+2348031234567',
  email: 'adaeze@example.com',
  address: '14 Bourdillon Road, Ikoyi, Lagos',
  bvnLinked: true,
  ninLinked: false,
};

// ── Catalog ──────────────────────────────────────────────────────────────────
// MyCover.ai rail = financial/identity/Spotlight lines.
// Octamile rail = journey-of-goods-or-people lines.
export const MOCK_PRODUCTS: InsuranceProduct[] = [
  // ── MyCover.ai — Health ─────────────────────────────────────────────────────
  {
    code: 'mycover.health.micro.v1',
    displayName: 'MicroHealth Essential',
    shortDescription: 'Outpatient + hospital cover for everyday care',
    productLine: 'HEALTH',
    provider: 'MYCOVER',
    bindingMode: 'VOLUNTARY',
    premiumModel: 'TIERED',
    fromPremiumKobo: 1_200_00,
    premiumCadence: 'monthly',
    requiredKycTier: 'TIER_1',
    disclosure: { underwriter: 'Hygeia HMO', aggregator: 'MyCover.ai' },
    sumInsuredRules: { min: 250_000_00, max: 2_000_000_00, basis: 'fixed' },
    benefits: [
      'Outpatient consultations at partner clinics',
      'Hospital admission up to ₦2,000,000 / year',
      'Prescribed drugs & basic diagnostics',
      'Telemedicine access included',
    ],
    exclusions: [
      'Pre-existing conditions in first 90 days',
      'Cosmetic & elective procedures',
      'Treatment outside Nigeria',
    ],
    icon: 'HeartPulse',
    fieldsSchema: [
      { key: 'fullName', label: 'Full name', type: 'text', required: true, kycKey: 'fullName' },
      { key: 'dateOfBirth', label: 'Date of birth', type: 'date', required: true, kycKey: 'dateOfBirth' },
      { key: 'phone', label: 'Phone number', type: 'text', required: true, kycKey: 'phone' },
      { key: 'plan', label: 'Plan tier', type: 'select', required: true, options: [
        { value: 'bronze', label: 'Bronze — ₦250k cover' },
        { value: 'silver', label: 'Silver — ₦1m cover' },
        { value: 'gold', label: 'Gold — ₦2m cover' },
      ], helper: 'Higher tiers raise your annual cover limit.' },
      { key: 'dependents', label: 'Number of dependents', type: 'number', required: false, min: 0, max: 6, placeholder: '0' },
    ],
    active: true,
  },
  // ── MyCover.ai — Personal Accident ──────────────────────────────────────────
  {
    code: 'mycover.pa.income.v1',
    displayName: 'Personal Accident Shield',
    shortDescription: 'Lump-sum payout for injury, disability or loss of income',
    productLine: 'PERSONAL_ACCIDENT',
    provider: 'MYCOVER',
    bindingMode: 'VOLUNTARY',
    premiumModel: 'FLAT',
    fromPremiumKobo: 500_00,
    premiumCadence: 'monthly',
    requiredKycTier: 'TIER_1',
    disclosure: { underwriter: 'Leadway Assurance', aggregator: 'MyCover.ai' },
    sumInsuredRules: { min: 500_000_00, max: 5_000_000_00, basis: 'fixed' },
    benefits: [
      'Accidental death & permanent disability cover',
      'Weekly income benefit while hospitalised',
      'Medical expense reimbursement',
      'Beneficiary payout protection',
    ],
    exclusions: [
      'Self-inflicted injury',
      'Hazardous sports without rider',
      'Injury under the influence',
    ],
    icon: 'ShieldPlus',
    fieldsSchema: [
      { key: 'fullName', label: 'Full name', type: 'text', required: true, kycKey: 'fullName' },
      { key: 'dateOfBirth', label: 'Date of birth', type: 'date', required: true, kycKey: 'dateOfBirth' },
      { key: 'occupation', label: 'Occupation', type: 'text', required: true, placeholder: 'e.g. Trader' },
      { key: 'coverAmount', label: 'Cover amount (₦)', type: 'currency', required: true, min: 500_000, max: 5_000_000, helper: 'Sum insured paid to your beneficiary.' },
    ],
    active: true,
  },
  // ── MyCover.ai — Device ─────────────────────────────────────────────────────
  {
    code: 'mycover.device.gadget.v1',
    displayName: 'Gadget Guard',
    shortDescription: 'Theft & accidental damage cover for your phone or laptop',
    productLine: 'DEVICE',
    provider: 'MYCOVER',
    bindingMode: 'VOLUNTARY',
    premiumModel: 'TIERED',
    fromPremiumKobo: 800_00,
    premiumCadence: 'annual',
    requiredKycTier: 'TIER_1',
    disclosure: { underwriter: 'Sovereign Trust Insurance', aggregator: 'MyCover.ai' },
    sumInsuredRules: { min: 50_000_00, max: 3_000_000_00, basis: 'declared_value' },
    benefits: [
      'Accidental & liquid damage repair',
      'Theft & burglary replacement',
      'Cracked screen repair',
      'Worldwide cover for the device',
    ],
    exclusions: [
      'Pre-existing damage',
      'Loss without a police report',
      'Devices over 3 years old',
    ],
    icon: 'Smartphone',
    fieldsSchema: [
      { key: 'fullName', label: 'Full name', type: 'text', required: true, kycKey: 'fullName' },
      { key: 'deviceType', label: 'Device type', type: 'select', required: true, options: [
        { value: 'phone', label: 'Smartphone' },
        { value: 'laptop', label: 'Laptop' },
        { value: 'tablet', label: 'Tablet' },
      ] },
      { key: 'deviceValue', label: 'Device value (₦)', type: 'currency', required: true, min: 50_000, max: 3_000_000, helper: 'Your premium scales with declared value.' },
      { key: 'imei', label: 'IMEI / serial', type: 'text', required: true, placeholder: '15-digit IMEI' },
    ],
    active: true,
  },
  // ── MyCover.ai — SME ────────────────────────────────────────────────────────
  {
    code: 'mycover.sme.bundle.v1',
    displayName: 'SME Protect Bundle',
    shortDescription: 'Fire, burglary & public liability for small businesses',
    productLine: 'SME',
    provider: 'MYCOVER',
    bindingMode: 'VOLUNTARY',
    premiumModel: 'TIERED',
    fromPremiumKobo: 3_500_00,
    premiumCadence: 'annual',
    requiredKycTier: 'TIER_2',
    disclosure: { underwriter: 'AIICO Insurance', aggregator: 'MyCover.ai' },
    sumInsuredRules: { min: 1_000_000_00, max: 20_000_000_00, basis: 'declared_value' },
    benefits: [
      'Fire & special perils on stock and premises',
      'Burglary & theft of business assets',
      'Public liability cover',
      'Business interruption support',
    ],
    exclusions: [
      'Unoccupied premises over 30 days',
      'Cash in transit (separate rider)',
      'Wear & tear',
    ],
    icon: 'Building2',
    fieldsSchema: [
      { key: 'businessName', label: 'Business name', type: 'text', required: true, placeholder: 'Registered name' },
      { key: 'sector', label: 'Sector', type: 'select', required: true, options: [
        { value: 'retail', label: 'Retail / Trading' },
        { value: 'food', label: 'Food & Hospitality' },
        { value: 'services', label: 'Services' },
        { value: 'manufacturing', label: 'Manufacturing' },
      ] },
      { key: 'assetValue', label: 'Total asset value (₦)', type: 'currency', required: true, min: 1_000_000, max: 20_000_000 },
      { key: 'address', label: 'Business address', type: 'text', required: true, kycKey: 'address' },
    ],
    active: true,
  },
  // ── Octamile — Motor ────────────────────────────────────────────────────────
  {
    code: 'octamile.motor.comprehensive.v1',
    displayName: 'Comprehensive Motor',
    shortDescription: 'Full cover for your vehicle — own damage, theft & third-party',
    productLine: 'MOTOR',
    provider: 'OCTAMILE',
    bindingMode: 'VOLUNTARY',
    premiumModel: 'TIERED',
    fromPremiumKobo: 25_000_00,
    premiumCadence: 'annual',
    requiredKycTier: 'TIER_2',
    disclosure: { underwriter: 'AXA Mansard', aggregator: 'Octamile' },
    sumInsuredRules: { min: 1_500_000_00, max: 50_000_000_00, basis: 'declared_value' },
    benefits: [
      'Own damage & accident repair',
      'Theft of vehicle',
      'Third-party property & injury liability',
      'Fast-track claims with remote inspection',
    ],
    exclusions: [
      'Driving without a valid licence',
      'Wear, tear & mechanical breakdown',
      'Use outside declared purpose',
    ],
    icon: 'Car',
    fieldsSchema: [
      { key: 'fullName', label: 'Full name', type: 'text', required: true, kycKey: 'fullName' },
      { key: 'plateNumber', label: 'Plate number', type: 'text', required: true, placeholder: 'e.g. LAG-123-XY' },
      { key: 'vehicleValue', label: 'Vehicle value (₦)', type: 'currency', required: true, min: 1_500_000, max: 50_000_000, helper: 'Current market value of the vehicle.' },
      { key: 'usage', label: 'Usage', type: 'select', required: true, options: [
        { value: 'private', label: 'Private' },
        { value: 'commercial', label: 'Commercial' },
        { value: 'ride-hailing', label: 'Ride-hailing' },
      ] },
    ],
    active: true,
  },
  // ── Octamile — Third-party Motor (illustrative low-cost) ─────────────────────
  {
    code: 'octamile.motor.thirdparty.v1',
    displayName: 'Third-Party Motor',
    shortDescription: 'NAICOM-compliant third-party liability cover',
    productLine: 'MOTOR',
    provider: 'OCTAMILE',
    bindingMode: 'VOLUNTARY',
    premiumModel: 'FLAT',
    fromPremiumKobo: 15_000_00,
    premiumCadence: 'annual',
    requiredKycTier: 'TIER_1',
    disclosure: { underwriter: 'AXA Mansard', aggregator: 'Octamile' },
    sumInsuredRules: { min: 3_000_000_00, max: 3_000_000_00, basis: 'fixed' },
    benefits: [
      'Third-party property damage up to ₦3,000,000',
      'Third-party bodily injury & death',
      'Compulsory NAICOM-compliant cover',
      'Instant digital certificate',
    ],
    exclusions: [
      'Own vehicle damage (use comprehensive)',
      'Driving without a valid licence',
    ],
    icon: 'Car',
    fieldsSchema: [
      { key: 'fullName', label: 'Full name', type: 'text', required: true, kycKey: 'fullName' },
      { key: 'plateNumber', label: 'Plate number', type: 'text', required: true, placeholder: 'e.g. LAG-123-XY' },
      { key: 'vehicleType', label: 'Vehicle type', type: 'select', required: true, options: [
        { value: 'saloon', label: 'Saloon car' },
        { value: 'suv', label: 'SUV / Jeep' },
        { value: 'bus', label: 'Bus' },
        { value: 'truck', label: 'Truck' },
      ] },
    ],
    active: true,
  },
  // ── Octamile — Goods-in-Transit ─────────────────────────────────────────────
  {
    code: 'octamile.git.parcel.v1',
    displayName: 'Parcel Protection (GIT)',
    shortDescription: 'Cover for parcels & freight while in transit',
    productLine: 'GOODS_IN_TRANSIT',
    provider: 'OCTAMILE',
    bindingMode: 'EMBEDDED_PER_SHIPMENT',
    premiumModel: 'PER_SHIPMENT',
    fromPremiumKobo: 200_00,
    premiumCadence: 'per-shipment',
    requiredKycTier: 'TIER_1',
    disclosure: { underwriter: 'AXA Mansard', aggregator: 'Octamile' },
    sumInsuredRules: { min: 10_000_00, max: 5_000_000_00, basis: 'declared_value' },
    benefits: [
      'Loss or damage in transit',
      'Warehouse-to-warehouse cover',
      'Premium scales with declared value',
      'Fast-track claims with photo evidence',
    ],
    exclusions: [
      'Perishables without cold-chain rider',
      'Cash & jewellery',
      'Inherent vice / poor packaging',
    ],
    icon: 'Truck',
    fieldsSchema: [
      { key: 'origin', label: 'Pickup location', type: 'text', required: true, placeholder: 'City / area' },
      { key: 'destination', label: 'Delivery location', type: 'text', required: true, placeholder: 'City / area' },
      { key: 'declaredValue', label: 'Declared value (₦)', type: 'currency', required: true, min: 10_000, max: 5_000_000, helper: 'Premium is a % of declared value.' },
      { key: 'contents', label: 'Contents', type: 'text', required: true, placeholder: 'e.g. Electronics' },
    ],
    active: true,
  },
];

// ── Policy wallet (mock) ──────────────────────────────────────────────────────
export const MOCK_POLICIES: Policy[] = [
  {
    id: 'pol-001',
    productCode: 'mycover.health.micro.v1',
    productName: 'MicroHealth Essential',
    productLine: 'HEALTH',
    provider: 'MYCOVER',
    disclosure: { underwriter: 'Hygeia HMO', aggregator: 'MyCover.ai' },
    state: 'ACTIVE',
    bindingMode: 'VOLUNTARY',
    sumInsuredKobo: 1_000_000_00,
    premiumKobo: 1_200_00,
    premiumCadence: 'monthly',
    currency: 'NGN',
    effectiveAt: iso(-40),
    expiresAt: iso(325),
    certificateRef: 'cert/pol-001-signed.pdf',
    beneficiaries: [],
    icon: 'HeartPulse',
    refundState: 'NONE',
    createdAt: iso(-40),
  },
  {
    id: 'pol-002',
    productCode: 'octamile.motor.comprehensive.v1',
    productName: 'Comprehensive Motor',
    productLine: 'MOTOR',
    provider: 'OCTAMILE',
    disclosure: { underwriter: 'AXA Mansard', aggregator: 'Octamile' },
    state: 'RENEWAL_DUE',
    bindingMode: 'VOLUNTARY',
    sumInsuredKobo: 8_500_000_00,
    premiumKobo: 42_000_00,
    premiumCadence: 'annual',
    currency: 'NGN',
    effectiveAt: iso(-358),
    expiresAt: iso(7),
    renewalDueAt: iso(7),
    certificateRef: 'cert/pol-002-signed.pdf',
    beneficiaries: [],
    icon: 'Car',
    refundState: 'NONE',
    createdAt: iso(-358),
  },
  {
    id: 'pol-003',
    productCode: 'mycover.pa.income.v1',
    productName: 'Personal Accident Shield',
    productLine: 'PERSONAL_ACCIDENT',
    provider: 'MYCOVER',
    disclosure: { underwriter: 'Leadway Assurance', aggregator: 'MyCover.ai' },
    state: 'ACTIVE',
    bindingMode: 'VOLUNTARY',
    sumInsuredKobo: 2_000_000_00,
    premiumKobo: 750_00,
    premiumCadence: 'monthly',
    currency: 'NGN',
    effectiveAt: iso(-15),
    expiresAt: iso(350),
    certificateRef: 'cert/pol-003-signed.pdf',
    beneficiaries: [
      { id: 'ben-1', fullName: 'Chidi Okonkwo', relationship: 'Spouse', phone: '+2348039876543', sharePercent: 60 },
      { id: 'ben-2', fullName: 'Ngozi Okonkwo', relationship: 'Child', sharePercent: 40 },
    ],
    icon: 'ShieldPlus',
    refundState: 'NONE',
    createdAt: iso(-15),
  },
  {
    id: 'pol-004',
    productCode: 'mycover.device.gadget.v1',
    productName: 'Gadget Guard',
    productLine: 'DEVICE',
    provider: 'MYCOVER',
    disclosure: { underwriter: 'Sovereign Trust Insurance', aggregator: 'MyCover.ai' },
    state: 'CANCELLED',
    bindingMode: 'VOLUNTARY',
    sumInsuredKobo: 450_000_00,
    premiumKobo: 1_100_00,
    premiumCadence: 'annual',
    currency: 'NGN',
    effectiveAt: iso(-120),
    expiresAt: iso(-5),
    certificateRef: 'cert/pol-004-signed.pdf',
    beneficiaries: [],
    icon: 'Smartphone',
    refundState: 'REFUNDED',
    refundKobo: 412_50,
    createdAt: iso(-120),
  },
];
