// ── Crowdfunding — Mock dataset ──────────────────────────────────────────────
// Realistic Nigeria-first sample data. All money is in kobo.
// Flip USE_MOCK in crowdfunding.api.ts to false once real endpoints land.

import type {
  Campaign,
  Contribution,
  CampaignCreator,
} from '../types/crowdfunding.types';

const creator = (over: Partial<CampaignCreator> & Pick<CampaignCreator, 'id' | 'name' | 'type'>): CampaignCreator => ({
  avatarUrl: null,
  verification: 'KYC',
  location: 'Lagos, Nigeria',
  campaignsCreated: 1,
  totalRaisedKobo: 0,
  bio: null,
  joinedAt: '2025-01-12T00:00:00Z',
  followed: false,
  ...over,
});

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'cf1',
    title: 'Help Baby Zara Get Open-Heart Surgery',
    summary: 'Zara was born with a congenital heart defect. Her surgery in India must happen within 8 weeks.',
    story:
      "Zara is 14 months old and full of life, but she was born with Tetralogy of Fallot — a serious heart defect that needs corrective surgery. Doctors at Lagos University Teaching Hospital have referred us to a specialist cardiac centre in India.\n\nThe total cost — surgery, travel, and 3 weeks of post-op care — is ₦18,500,000. Our family has raised ₦4.2M by selling our shop and borrowing from relatives, but we cannot do this alone.\n\nEvery contribution, no matter how small, brings Zara closer to the surgery that will let her grow up like any other child. We will post hospital receipts and updates at every milestone.",
    type: 'DONATION',
    status: 'ACTIVE',
    category: 'medical',
    categoryLabel: 'Medical',
    coverImage: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&q=80',
    media: [
      { id: 'm1', type: 'image', url: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&q=80', thumbnailUrl: null },
      { id: 'm2', type: 'image', url: 'https://images.unsplash.com/photo-1559757175-7b21671636f0?w=800&q=80', thumbnailUrl: null },
      { id: 'm3', type: 'image', url: 'https://images.unsplash.com/photo-1612277795421-9bc7706a4a34?w=800&q=80', thumbnailUrl: null },
    ],
    goalKobo: 1_850_000_000,
    raisedKobo: 1_213_400_000,
    currency: 'NGN',
    contributorCount: 1_842,
    deadline: '2026-08-14T23:59:59Z',
    createdAt: '2026-05-20T09:00:00Z',
    creator: creator({ id: 'u1', name: 'Aisha Bello', type: 'INDIVIDUAL', verification: 'FULL', campaignsCreated: 1, totalRaisedKobo: 1_213_400_000, bio: "Zara's mother. Verified by Spotlight Trust & Safety." }),
    beneficiary: { id: 'b1', name: 'Zara Bello', relationship: 'Daughter', description: '14-month-old patient', verified: true },
    disbursementModel: 'MILESTONE',
    refundPolicy: 'Contributions are non-refundable once a surgical milestone is released. If the campaign is cancelled before any disbursement, full refunds are issued within 7 business days.',
    riskDisclosure: null,
    verified: true,
    featured: true,
    trending: true,
    urgent: true,
    saved: false,
    budget: [
      { id: 'bd1', label: 'Surgical procedure & hospital', amountKobo: 1_200_000_000, note: 'Cardiac centre, Chennai' },
      { id: 'bd2', label: 'Flights (2 adults + infant)', amountKobo: 250_000_000, note: null },
      { id: 'bd3', label: 'Post-op care & accommodation', amountKobo: 300_000_000, note: '3 weeks' },
      { id: 'bd4', label: 'Visas & medical reports', amountKobo: 100_000_000, note: null },
    ],
    milestones: [
      { id: 'ms1', title: 'Secure surgery deposit', targetKobo: 600_000_000, status: 'RELEASED', dueAt: '2026-06-10T00:00:00Z', evidenceCount: 3 },
      { id: 'ms2', title: 'Book travel & visas', targetKobo: 1_000_000_000, status: 'ACTIVE', dueAt: '2026-07-15T00:00:00Z', evidenceCount: 1 },
      { id: 'ms3', title: 'Final surgery balance', targetKobo: 1_850_000_000, status: 'LOCKED', dueAt: '2026-08-10T00:00:00Z', evidenceCount: 0 },
    ],
    updates: [
      { id: 'up1', title: 'Surgery date confirmed!', body: 'The cardiac centre has confirmed Zara’s slot for August 20th. Thank you to everyone who got us to the first milestone.', imageUrl: 'https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?w=800&q=80', createdAt: '2026-06-12T10:00:00Z', likeCount: 421 },
      { id: 'up2', title: 'Deposit paid — receipts attached', body: 'We’ve paid the ₦6M surgery deposit. Hospital receipt uploaded to the documents section for full transparency.', imageUrl: null, createdAt: '2026-06-09T14:30:00Z', likeCount: 388 },
    ],
    rewardTiers: [],
    documents: [
      { id: 'doc1', label: 'Hospital referral letter', type: 'pdf', sizeLabel: '240 KB', verified: true },
      { id: 'doc2', label: 'Surgery cost estimate', type: 'pdf', sizeLabel: '180 KB', verified: true },
    ],
    faqs: [
      { id: 'f1', question: 'How will I know the funds are used correctly?', answer: 'Funds are released per milestone only after evidence (receipts, hospital confirmation) is reviewed by Spotlight admin.' },
      { id: 'f2', question: 'Can I get a refund?', answer: 'Yes, before any milestone is released. See the refund policy above.' },
    ],
    tags: ['surgery', 'infant', 'urgent', 'verified'],
    location: 'Lagos, Nigeria',
  },
  {
    id: 'cf2',
    title: 'Solar Power for Ajegunle Community School',
    summary: 'Give 600 pupils reliable light and a computer lab powered by clean solar energy.',
    story:
      'Ajegunle Community School serves 600 children from low-income families. Frequent power cuts mean no computer lessons and dark classrooms during the rainy season.\n\nWe are raising ₦7,500,000 to install a 10kVA solar system, batteries, and 15 refurbished computers. This unlocks digital literacy classes and evening study sessions for the whole community.',
    type: 'COMMUNITY',
    status: 'ACTIVE',
    category: 'education',
    categoryLabel: 'Education',
    coverImage: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800&q=80',
    media: [
      { id: 'm4', type: 'image', url: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=800&q=80', thumbnailUrl: null },
      { id: 'm5', type: 'image', url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80', thumbnailUrl: null },
    ],
    goalKobo: 750_000_000,
    raisedKobo: 489_750_000,
    currency: 'NGN',
    contributorCount: 612,
    deadline: '2026-09-30T23:59:59Z',
    createdAt: '2026-05-02T09:00:00Z',
    creator: creator({ id: 'u2', name: 'Ajegunle Education Trust', type: 'NGO', verification: 'KYB', campaignsCreated: 4, totalRaisedKobo: 2_100_000_000, location: 'Lagos, Nigeria', bio: 'Registered NGO (RC 1402887) improving education in underserved communities.' }),
    beneficiary: { id: 'b2', name: 'Ajegunle Community School', relationship: 'Beneficiary school', description: '600 pupils, Lagos', verified: true },
    disbursementModel: 'ALL_OR_NOTHING',
    refundPolicy: 'All-or-nothing: if the ₦7.5M goal is not reached by the deadline, every contributor is automatically refunded in full.',
    riskDisclosure: null,
    verified: true,
    featured: true,
    trending: false,
    urgent: false,
    saved: true,
    budget: [
      { id: 'bd5', label: '10kVA solar inverter + panels', amountKobo: 420_000_000, note: null },
      { id: 'bd6', label: 'Battery bank', amountKobo: 180_000_000, note: null },
      { id: 'bd7', label: '15 refurbished computers', amountKobo: 120_000_000, note: null },
      { id: 'bd8', label: 'Installation & training', amountKobo: 30_000_000, note: null },
    ],
    milestones: [],
    updates: [
      { id: 'up3', title: 'Halfway there!', body: 'We crossed ₦4.8M this week. Quotes from three solar vendors are now posted in documents.', imageUrl: null, createdAt: '2026-06-15T11:00:00Z', likeCount: 96 },
    ],
    rewardTiers: [],
    documents: [
      { id: 'doc3', label: 'CAC registration', type: 'pdf', sizeLabel: '320 KB', verified: true },
      { id: 'doc4', label: 'Solar vendor quotes', type: 'pdf', sizeLabel: '510 KB', verified: false },
    ],
    faqs: [],
    tags: ['solar', 'school', 'community'],
    location: 'Lagos, Nigeria',
  },
  {
    id: 'cf3',
    title: 'Àdìre: A Documentary on Yoruba Textile Art',
    summary: 'Back an independent film preserving the dying craft of hand-dyed àdìre cloth.',
    story:
      'Àdìre is a centuries-old Yoruba resist-dyeing tradition at risk of disappearing. Our team of three filmmakers will spend 6 months with master dyers in Abeokuta to document their stories and techniques.\n\nBack us to fund production, and choose a reward tier — from a digital download to a hand-dyed àdìre scarf and an executive-producer credit.',
    type: 'REWARD',
    status: 'ACTIVE',
    category: 'creative',
    categoryLabel: 'Creative',
    coverImage: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
    media: [
      { id: 'm6', type: 'image', url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80', thumbnailUrl: null },
    ],
    goalKobo: 320_000_000,
    raisedKobo: 96_500_000,
    currency: 'NGN',
    contributorCount: 214,
    deadline: '2026-07-05T23:59:59Z',
    createdAt: '2026-05-10T09:00:00Z',
    creator: creator({ id: 'u3', name: 'Tunde Akande', type: 'INDIVIDUAL', verification: 'KYC', campaignsCreated: 2, location: 'Abeokuta, Nigeria', bio: 'Documentary filmmaker. Previous film screened at AFRIFF 2024.' }),
    beneficiary: null,
    disbursementModel: 'FLEXIBLE',
    refundPolicy: 'Reward-based: contributions fund production immediately. If a reward cannot be delivered, you may request a refund of that reward’s value within 30 days of the stated delivery date.',
    riskDisclosure: 'Creative projects carry delivery risk. Estimated delivery dates are not guarantees.',
    verified: true,
    featured: false,
    trending: true,
    urgent: false,
    saved: false,
    budget: [
      { id: 'bd9', label: 'Production & crew (6 months)', amountKobo: 180_000_000, note: null },
      { id: 'bd10', label: 'Equipment rental', amountKobo: 80_000_000, note: null },
      { id: 'bd11', label: 'Post-production & scoring', amountKobo: 60_000_000, note: null },
    ],
    milestones: [],
    updates: [],
    rewardTiers: [
      { id: 'r1', title: 'Digital Supporter', amountKobo: 500_000, description: 'HD digital download + your name in the credits.', estimatedDelivery: '2027-03-01', claimed: 88, limit: null, requiresShipping: false },
      { id: 'r2', title: 'Àdìre Scarf', amountKobo: 2_500_000, description: 'A hand-dyed àdìre scarf + digital download.', estimatedDelivery: '2027-04-01', claimed: 41, limit: 200, requiresShipping: true },
      { id: 'r3', title: 'Executive Producer', amountKobo: 25_000_000, description: 'Executive-producer credit, premiere invite, signed poster + scarf.', estimatedDelivery: '2027-04-01', claimed: 6, limit: 20, requiresShipping: true },
    ],
    documents: [],
    faqs: [
      { id: 'f3', question: 'When will rewards ship?', answer: 'Physical rewards ship after the film wraps, estimated Q1–Q2 2027. You’ll get tracking updates.' },
    ],
    tags: ['film', 'culture', 'rewards'],
    location: 'Abeokuta, Nigeria',
  },
  {
    id: 'cf4',
    title: 'Flood Relief for Bayelsa Families',
    summary: 'Emergency food, clean water, and shelter kits for 400 displaced families.',
    story:
      'Severe flooding has displaced hundreds of families across Bayelsa. Our volunteer network is distributing emergency kits — food, water purification tablets, and tarpaulins — directly to affected communities.\n\nWe need ₦12,000,000 to reach 400 families this month. Funds are released weekly against distribution photos and beneficiary lists.',
    type: 'DONATION',
    status: 'ACTIVE',
    category: 'emergency',
    categoryLabel: 'Emergency',
    coverImage: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&q=80',
    media: [{ id: 'm7', type: 'image', url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&q=80', thumbnailUrl: null }],
    goalKobo: 1_200_000_000,
    raisedKobo: 342_000_000,
    currency: 'NGN',
    contributorCount: 503,
    deadline: '2026-06-30T23:59:59Z',
    createdAt: '2026-06-05T09:00:00Z',
    creator: creator({ id: 'u4', name: 'RapidAid Nigeria', type: 'NGO', verification: 'KYB', campaignsCreated: 9, totalRaisedKobo: 8_400_000_000, location: 'Yenagoa, Nigeria', bio: 'Disaster-response NGO active since 2018.' }),
    beneficiary: { id: 'b4', name: '400 displaced families', relationship: 'Beneficiaries', description: 'Bayelsa flood victims', verified: true },
    disbursementModel: 'MILESTONE',
    refundPolicy: 'Emergency funds are disbursed weekly and are non-refundable once distributed. Undistributed funds at campaign close are carried to the next relief effort or refunded on request.',
    riskDisclosure: null,
    verified: true,
    featured: false,
    trending: false,
    urgent: true,
    saved: false,
    budget: [
      { id: 'bd12', label: 'Food kits (400)', amountKobo: 600_000_000, note: null },
      { id: 'bd13', label: 'Water purification', amountKobo: 240_000_000, note: null },
      { id: 'bd14', label: 'Shelter tarpaulins', amountKobo: 360_000_000, note: null },
    ],
    milestones: [
      { id: 'ms4', title: 'Week 1 distribution (100 families)', targetKobo: 300_000_000, status: 'RELEASED', dueAt: null, evidenceCount: 2 },
      { id: 'ms5', title: 'Week 2 distribution (150 families)', targetKobo: 750_000_000, status: 'ACTIVE', dueAt: null, evidenceCount: 0 },
    ],
    updates: [],
    rewardTiers: [],
    documents: [],
    faqs: [],
    tags: ['flood', 'relief', 'urgent'],
    location: 'Yenagoa, Nigeria',
  },
  {
    id: 'cf5',
    title: 'Mama Ngozi’s Garri Processing Expansion',
    summary: 'Help a women-led cooperative buy a mechanical grater and double their output.',
    story:
      'Mama Ngozi leads a 12-woman cassava-processing cooperative in Enugu. Manual grating limits them to 50 bags of garri a week. A mechanical grater and a drying rack would triple output and create 6 new jobs.\n\nWe’re raising ₦2,800,000. This is a flexible-funding SME campaign — every naira raised goes toward equipment, with a use-of-funds report after purchase.',
    type: 'SME',
    status: 'ACTIVE',
    category: 'sme',
    categoryLabel: 'SME',
    coverImage: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80',
    media: [{ id: 'm8', type: 'image', url: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80', thumbnailUrl: null }],
    goalKobo: 280_000_000,
    raisedKobo: 280_000_000,
    currency: 'NGN',
    contributorCount: 178,
    deadline: '2026-06-18T23:59:59Z',
    createdAt: '2026-04-28T09:00:00Z',
    creator: creator({ id: 'u5', name: 'Ngozi Eze', type: 'SME', verification: 'KYB', campaignsCreated: 1, location: 'Enugu, Nigeria', bio: 'Cooperative lead, Enugu Women in Agriculture.' }),
    beneficiary: { id: 'b5', name: 'Enugu Women’s Cassava Co-op', relationship: 'Business', description: '12-member cooperative', verified: true },
    disbursementModel: 'FLEXIBLE',
    refundPolicy: 'Flexible funding: funds are released to the cooperative after the campaign closes. Non-refundable once disbursed.',
    riskDisclosure: 'SME campaigns carry business risk. Returns are not guaranteed; this is not an investment.',
    verified: true,
    featured: false,
    trending: false,
    urgent: false,
    saved: false,
    budget: [
      { id: 'bd15', label: 'Mechanical grater', amountKobo: 180_000_000, note: null },
      { id: 'bd16', label: 'Drying rack & trays', amountKobo: 70_000_000, note: null },
      { id: 'bd17', label: 'Installation & training', amountKobo: 30_000_000, note: null },
    ],
    milestones: [],
    updates: [
      { id: 'up4', title: 'Goal reached — thank you!', body: 'We hit 100%! Equipment order placed. Use-of-funds report coming after delivery.', imageUrl: null, createdAt: '2026-06-16T08:00:00Z', likeCount: 54 },
    ],
    rewardTiers: [],
    documents: [],
    faqs: [],
    tags: ['agriculture', 'women', 'sme'],
    location: 'Enugu, Nigeria',
  },
  {
    id: 'cf6',
    title: 'St. Andrew’s Parish Hall Rebuild',
    summary: 'Rebuild the community hall that hosts weddings, classes, and town meetings.',
    story:
      'Our 40-year-old parish hall has structural damage and is no longer safe. The hall hosts weekly youth classes, weddings, and community meetings. We’re raising ₦15,000,000 to rebuild the roof and reinforce the walls.',
    type: 'COMMUNITY',
    status: 'COMPLETED',
    category: 'religious',
    categoryLabel: 'Religious',
    coverImage: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?w=800&q=80',
    media: [{ id: 'm9', type: 'image', url: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?w=800&q=80', thumbnailUrl: null }],
    goalKobo: 1_500_000_000,
    raisedKobo: 1_560_000_000,
    currency: 'NGN',
    contributorCount: 921,
    deadline: '2026-05-31T23:59:59Z',
    createdAt: '2026-02-01T09:00:00Z',
    creator: creator({ id: 'u6', name: 'St. Andrew’s Parish', type: 'ORGANISATION', verification: 'KYB', campaignsCreated: 3, location: 'Ibadan, Nigeria' }),
    beneficiary: { id: 'b6', name: 'St. Andrew’s Parish community', relationship: 'Community', description: null, verified: true },
    disbursementModel: 'ESCROW',
    refundPolicy: 'Goal met and funds disbursed. Campaign closed.',
    riskDisclosure: null,
    verified: true,
    featured: false,
    trending: false,
    urgent: false,
    saved: false,
    budget: [
      { id: 'bd18', label: 'Roof rebuild', amountKobo: 900_000_000, note: null },
      { id: 'bd19', label: 'Wall reinforcement', amountKobo: 600_000_000, note: null },
    ],
    milestones: [],
    updates: [
      { id: 'up5', title: 'Construction complete 🎉', body: 'The new hall is finished and back in use. Final report and photos attached. God bless every contributor.', imageUrl: 'https://images.unsplash.com/photo-1473177104440-ffee2f376098?w=800&q=80', createdAt: '2026-06-01T08:00:00Z', likeCount: 612 },
    ],
    rewardTiers: [],
    documents: [],
    faqs: [],
    tags: ['church', 'rebuild', 'completed'],
    location: 'Ibadan, Nigeria',
  },
];

// ─── Recently viewed (ids, most-recent first) ────────────────────────────────
export const MOCK_RECENTLY_VIEWED = ['cf3', 'cf1', 'cf4'];

// ─── Contribution history (current user) ─────────────────────────────────────
export const MOCK_CONTRIBUTIONS: Contribution[] = [
  {
    id: 'ct1', reference: 'SPL-CF-1001', campaignId: 'cf1', campaignTitle: 'Help Baby Zara Get Open-Heart Surgery',
    campaignCover: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=400&q=80',
    amountKobo: 500_000, feeKobo: 12_500, totalKobo: 512_500, currency: 'NGN', status: 'SUCCESSFUL',
    paymentMethod: 'WALLET', anonymous: false, message: 'Praying for Zara’s full recovery 🙏', rewardTierTitle: null,
    createdAt: '2026-06-14T10:22:00Z', refundEligible: true,
  },
  {
    id: 'ct2', reference: 'SPL-CF-1002', campaignId: 'cf3', campaignTitle: 'Àdìre: A Documentary on Yoruba Textile Art',
    campaignCover: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&q=80',
    amountKobo: 2_500_000, feeKobo: 100_500, totalKobo: 2_600_500, currency: 'NGN', status: 'SUCCESSFUL',
    paymentMethod: 'CARD', anonymous: false, message: null, rewardTierTitle: 'Àdìre Scarf',
    createdAt: '2026-06-08T16:40:00Z', refundEligible: false,
  },
  {
    id: 'ct3', reference: 'SPL-CF-1003', campaignId: 'cf4', campaignTitle: 'Flood Relief for Bayelsa Families',
    campaignCover: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400&q=80',
    amountKobo: 200_000, feeKobo: 8_000, totalKobo: 208_000, currency: 'NGN', status: 'REFUND_REQUESTED',
    paymentMethod: 'CARD', anonymous: true, message: null, rewardTierTitle: null,
    createdAt: '2026-06-06T09:05:00Z', refundEligible: true,
  },
];
