'use client';

// Public landing page for a contestant profile share link
// (spotlight.ng/vote-link/{token}, generated by POST /api/v1/connect/contestants/:id/share).
//
// The person opening this has no session — they followed a link a friend
// sent, not something the app itself linked to. So this page:
//   1. Resolves the token via the public GET /api/v1/connect/share/:token
//      (no auth — see that route's own comment for why it's split out of
//      the authenticated /api/v1/connect/[...path] catch-all).
//   2. Shows who they're being asked to vote for.
//   3. Tries the app's custom-scheme deep link (works only if the app is
//      already installed on this device); if nothing happens after a short
//      wait, falls back to store links — which are genuinely not configured
//      yet (see APP_STORE_URL/PLAY_STORE_URL below), so a first-time visitor
//      sees an honest "not available yet" message instead of a dead link.
//      Deferred deep linking (skip the store-fallback confusion entirely,
//      landing straight in the vote flow after a fresh install) needs a
//      provider like Branch.io and was explicitly scoped OUT of this feature.

import { useEffect, useState } from 'react';

interface ResolvedContestant {
  contestant_id: string;
  contest_id?: string;
  name: string;
  stage_name?: string;
  photo_url?: string;
  category?: string;
  state?: string;
  total_votes: number;
  like_count?: number;
}

type Status = 'loading' | 'found' | 'not_found' | 'error';

// Genuinely unset until the app is actually published — see this file's
// header comment. Rendered only when present, never as a dead placeholder link.
const APP_STORE_URL = process.env.NEXT_PUBLIC_IOS_APP_STORE_URL || '';
const PLAY_STORE_URL = process.env.NEXT_PUBLIC_ANDROID_PLAY_STORE_URL || '';

export default function VoteLinkClient({ token }: { token: string }) {
  const [status, setStatus] = useState<Status>('loading');
  const [contestant, setContestant] = useState<ResolvedContestant | null>(null);
  const [triedDeepLink, setTriedDeepLink] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/v1/connect/share/${encodeURIComponent(token)}`);
        if (cancelled) return;
        if (res.status === 404) {
          setStatus('not_found');
          return;
        }
        if (!res.ok) {
          setStatus('error');
          return;
        }
        const json = await res.json();
        setContestant((json?.data ?? json) as ResolvedContestant);
        setStatus('found');
      } catch {
        if (!cancelled) setStatus('error');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [token]);

  const openInApp = () => {
    if (!contestant) return;
    setTriedDeepLink(true);
    const deepLink =
      `paymaxrn://voting/contestant-profile` +
      `?contestantId=${encodeURIComponent(contestant.contestant_id)}` +
      `&contestId=${encodeURIComponent(contestant.contest_id ?? '')}`;
    window.location.href = deepLink;
  };

  const displayName = contestant?.stage_name || contestant?.name || '';

  return (
    <main className="min-h-screen bg-gray-950 flex items-center justify-center px-4">
      <div className="bg-gray-900 rounded-2xl p-8 max-w-md w-full text-center shadow-2xl">
        {status === 'loading' && (
          <>
            <div className="w-14 h-14 border-4 border-amber-500 border-t-transparent rounded-full animate-spin mx-auto mb-5" />
            <h1 className="text-xl font-bold text-white">Loading…</h1>
          </>
        )}

        {status === 'not_found' && (
          <>
            <div className="w-16 h-16 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-5">
              <span className="text-4xl">🔗</span>
            </div>
            <h1 className="text-xl font-bold text-white mb-2">Link not found</h1>
            <p className="text-gray-400 text-sm">
              This share link has expired or doesn&apos;t exist. Ask for a fresh one.
            </p>
          </>
        )}

        {status === 'error' && (
          <>
            <div className="w-16 h-16 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-5">
              <span className="text-4xl">⚠️</span>
            </div>
            <h1 className="text-xl font-bold text-white mb-2">Something went wrong</h1>
            <p className="text-gray-400 text-sm">Please try this link again in a moment.</p>
          </>
        )}

        {status === 'found' && contestant && (
          <>
            {contestant.photo_url ? (
              // Plain <img>, not next/image: photo_url is R2/arbitrary-origin
              // and this page has no reason to maintain a remotePatterns
              // allowlist just for a share-link avatar.
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={contestant.photo_url}
                alt={displayName}
                className="w-24 h-24 rounded-full object-cover mx-auto mb-5 border-2 border-amber-500"
              />
            ) : (
              <div className="w-24 h-24 rounded-full bg-gray-800 flex items-center justify-center mx-auto mb-5 border-2 border-amber-500">
                <span className="text-3xl font-bold text-amber-500">{displayName.charAt(0)}</span>
              </div>
            )}
            <h1 className="text-2xl font-bold text-white mb-1">{displayName}</h1>
            {(contestant.category || contestant.state) && (
              <p className="text-gray-400 text-sm mb-4">
                {[contestant.category, contestant.state].filter(Boolean).join(' · ')}
              </p>
            )}
            <p className="text-amber-400 text-lg font-semibold mb-6">
              {contestant.total_votes.toLocaleString()} votes so far
            </p>

            <button
              onClick={openInApp}
              className="w-full bg-amber-500 hover:bg-amber-400 text-black font-bold py-3 rounded-xl transition-all mb-3"
            >
              Vote for {displayName} in the app
            </button>

            {triedDeepLink && (
              <p className="text-gray-500 text-xs mb-4">
                Nothing happened? You probably don&apos;t have the app installed yet.
              </p>
            )}

            {(APP_STORE_URL || PLAY_STORE_URL) ? (
              <div className="flex gap-3">
                {APP_STORE_URL && (
                  <a
                    href={APP_STORE_URL}
                    className="flex-1 border border-gray-700 text-gray-300 py-3 rounded-xl text-sm"
                  >
                    App Store
                  </a>
                )}
                {PLAY_STORE_URL && (
                  <a
                    href={PLAY_STORE_URL}
                    className="flex-1 border border-gray-700 text-gray-300 py-3 rounded-xl text-sm"
                  >
                    Google Play
                  </a>
                )}
              </div>
            ) : (
              <p className="text-gray-500 text-xs">
                The Paymax Spotlight app isn&apos;t publicly downloadable yet — check back soon.
              </p>
            )}
          </>
        )}
      </div>
    </main>
  );
}
