// @ts-nocheck
import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Pressable,
  ActivityIndicator,
  SafeAreaView,
  Share,
  Modal,
  Platform,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { getAppointment } from '@/api/telemedicine.api';

// NOTE: expo-print and expo-sharing are not in package.json.
// Sharing falls back to React Native's built-in Share API.
// To upgrade to PDF export: install expo-print + expo-sharing, then replace
// shareAppointmentSummary() with Print.printToFileAsync + Sharing.shareAsync.

const C = {
  primary: '#059669',
  primaryDark: '#065f46',
  primaryContainer: '#d1fae5',
  secondary: '#0EA5E9',
  secondaryContainer: '#e0f2fe',
  tertiary: '#F59E0B',
  error: '#EF4444',
  bg: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceVariant: '#F1F5F9',
  text: '#0F172A',
  textMuted: '#64748B',
  border: '#E2E8F0',
};

// Fallback data for offline / dev mode
const FALLBACK_APPOINTMENT = {
  id: 'appt-001',
  doctor_name: 'Dr. Adebayo Chen',
  doctor_specialty: 'Consultant Cardiologist',
  date: '2026-06-15',
  time: '10:30 AM',
  consultation_type: 'video',
  status: 'completed',
  notes:
    'Patient presented with mild chest discomfort and shortness of breath on exertion. ECG within normal limits. Blood pressure slightly elevated at 138/88.',
  diagnosis: 'Hypertension Stage 1 with cardiac monitoring advised.',
  prescription: 'Amlodipine 5mg once daily for 30 days. Review in 4 weeks.',
  follow_up_date: '2026-07-15',
  fee_kobo: 1500000,
};

function formatDate(dateStr) {
  if (!dateStr) return '—';
  try {
    return new Date(dateStr).toLocaleDateString('en-NG', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

function buildSummaryText(appt) {
  return [
    'APPOINTMENT SUMMARY',
    '===================',
    '',
    `Appointment ID : ${appt.id ?? '—'}`,
    `Date & Time    : ${formatDate(appt.date)} at ${appt.time ?? '—'}`,
    `Doctor         : ${appt.doctor_name ?? '—'}`,
    `Specialty      : ${appt.doctor_specialty ?? '—'}`,
    `Type           : ${appt.consultation_type === 'video' ? 'Video Consultation' : 'In-Person Visit'}`,
    `Status         : ${String(appt.status ?? '').toUpperCase()}`,
    '',
    'CLINICAL NOTES',
    '--------------',
    appt.notes ?? 'No notes recorded.',
    '',
    'DIAGNOSIS',
    '---------',
    appt.diagnosis ?? 'No diagnosis recorded.',
    '',
    'PRESCRIPTION',
    '------------',
    appt.prescription ?? 'No prescription issued.',
    '',
    'FOLLOW-UP',
    '---------',
    appt.follow_up_date
      ? `Next appointment: ${formatDate(appt.follow_up_date)}`
      : 'No follow-up scheduled.',
    '',
    '---',
    'Generated by Paymax Health · Spotlight Super App',
  ].join('\n');
}

async function shareAppointmentSummary(appt) {
  const message = buildSummaryText(appt);
  await Share.share({
    title: `Appointment Summary — ${appt.doctor_name ?? 'Doctor'}`,
    message,
  });
}

export default function AppointmentSummaryScreen() {
  const { id } = useLocalSearchParams();
  const router = useRouter();
  const [shareModalVisible, setShareModalVisible] = useState(false);
  const [sharing, setSharing] = useState(false);

  const { data: appointment, isLoading } = useQuery({
    queryKey: ['appointment', id],
    queryFn: () => getAppointment(id),
    enabled: !!id,
    retry: 1,
  });

  const appt = appointment ?? FALLBACK_APPOINTMENT;

  const handleShare = async () => {
    try {
      setSharing(true);
      await shareAppointmentSummary(appt);
    } catch {
      // Share dialog dismissed — not an error
    } finally {
      setSharing(false);
    }
  };

  if (isLoading) {
    return (
      <SafeAreaView style={s.safe}>
        <View style={s.loadingContainer}>
          <ActivityIndicator size="large" color={C.primary} />
          <Text style={s.loadingText}>Loading summary…</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={s.safe}>
      {/* Header */}
      <View style={s.header}>
        <Pressable onPress={() => router.back()} style={s.iconBtn} hitSlop={8}>
          <Ionicons name="arrow-back" size={22} color={C.text} />
        </Pressable>
        <Text style={s.headerTitle}>Appointment Summary</Text>
        <Pressable onPress={() => setShareModalVisible(true)} style={s.iconBtn} hitSlop={8}>
          <Ionicons name="share-outline" size={22} color={C.text} />
        </Pressable>
      </View>

      <ScrollView
        style={s.scroll}
        contentContainerStyle={s.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Status banner */}
        <View style={[s.statusBanner, appt.status === 'completed' ? s.bannerGreen : s.bannerAmber]}>
          <Ionicons
            name={appt.status === 'completed' ? 'checkmark-circle' : 'time-outline'}
            size={18}
            color={appt.status === 'completed' ? C.primary : C.tertiary}
          />
          <Text style={[s.statusText, { color: appt.status === 'completed' ? C.primary : C.tertiary }]}>
            {appt.status === 'completed'
              ? 'Consultation Completed'
              : String(appt.status ?? 'Pending').toUpperCase()}
          </Text>
        </View>

        {/* Doctor summary card */}
        <View style={s.card}>
          <View style={s.cardHeader}>
            <View style={s.doctorAvatar}>
              <Ionicons name="person" size={32} color={C.primary} />
            </View>
            <View style={s.doctorInfo}>
              <Text style={s.doctorName}>{appt.doctor_name ?? '—'}</Text>
              <Text style={s.doctorSpecialty}>{appt.doctor_specialty ?? '—'}</Text>
            </View>
          </View>
          <View style={s.divider} />
          <View style={s.detailRow}>
            <Ionicons name="calendar-outline" size={16} color={C.textMuted} />
            <Text style={s.detailLabel}>Date</Text>
            <Text style={s.detailValue}>{formatDate(appt.date)}</Text>
          </View>
          <View style={s.detailRow}>
            <Ionicons name="time-outline" size={16} color={C.textMuted} />
            <Text style={s.detailLabel}>Time</Text>
            <Text style={s.detailValue}>{appt.time ?? '—'}</Text>
          </View>
          <View style={s.detailRow}>
            <Ionicons
              name={appt.consultation_type === 'video' ? 'videocam-outline' : 'business-outline'}
              size={16}
              color={C.textMuted}
            />
            <Text style={s.detailLabel}>Type</Text>
            <Text style={s.detailValue}>
              {appt.consultation_type === 'video' ? 'Video Consultation' : 'In-Person Visit'}
            </Text>
          </View>
        </View>

        {/* Clinical Notes */}
        <View style={s.sectionHeader}>
          <Ionicons name="document-text-outline" size={16} color={C.primary} />
          <Text style={s.sectionTitle}>Clinical Notes</Text>
        </View>
        <View style={s.card}>
          <Text style={s.bodyText}>{appt.notes ?? 'No notes recorded.'}</Text>
        </View>

        {/* Diagnosis */}
        <View style={s.sectionHeader}>
          <Ionicons name="medkit-outline" size={16} color={C.primary} />
          <Text style={s.sectionTitle}>Diagnosis</Text>
        </View>
        <View style={s.card}>
          <Text style={s.bodyText}>{appt.diagnosis ?? 'No diagnosis recorded.'}</Text>
        </View>

        {/* Prescription */}
        <View style={s.sectionHeader}>
          <Ionicons name="flask-outline" size={16} color={C.primary} />
          <Text style={s.sectionTitle}>Prescription</Text>
        </View>
        <View style={s.card}>
          {appt.prescription ? (
            <Text style={s.bodyText}>{appt.prescription}</Text>
          ) : (
            <View style={s.emptyRow}>
              <Ionicons name="remove-circle-outline" size={16} color={C.textMuted} />
              <Text style={s.emptyText}>No prescription issued</Text>
            </View>
          )}
        </View>

        {/* Follow-up */}
        {!!appt.follow_up_date && (
          <>
            <View style={s.sectionHeader}>
              <Ionicons name="calendar" size={16} color={C.primary} />
              <Text style={s.sectionTitle}>Follow-Up</Text>
            </View>
            <View style={[s.card, s.followUpCard]}>
              <Ionicons name="calendar-outline" size={20} color={C.primary} />
              <View style={{ marginLeft: 12 }}>
                <Text style={s.followUpLabel}>Next Appointment</Text>
                <Text style={s.followUpDate}>{formatDate(appt.follow_up_date)}</Text>
              </View>
            </View>
          </>
        )}

        <View style={{ height: 100 }} />
      </ScrollView>

      {/* Sticky export footer */}
      <View style={s.footer}>
        <Pressable
          style={[s.exportBtn, sharing && { opacity: 0.65 }]}
          onPress={handleShare}
          disabled={sharing}
        >
          {sharing ? (
            <ActivityIndicator size="small" color="#fff" />
          ) : (
            <>
              <Ionicons name="share-social-outline" size={18} color="#fff" />
              <Text style={s.exportBtnText}>Export PDF / Share</Text>
            </>
          )}
        </Pressable>
      </View>

      {/* Preview modal */}
      <Modal
        visible={shareModalVisible}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setShareModalVisible(false)}
      >
        <SafeAreaView style={s.modal}>
          <View style={s.modalHeader}>
            <Text style={s.modalTitle}>Summary Preview</Text>
            <Pressable onPress={() => setShareModalVisible(false)} hitSlop={8}>
              <Ionicons name="close" size={24} color={C.text} />
            </Pressable>
          </View>
          <ScrollView contentContainerStyle={{ padding: 16 }}>
            <Text style={s.previewText}>{buildSummaryText(appt)}</Text>
          </ScrollView>
          <View style={s.modalFooter}>
            <Pressable
              style={s.exportBtn}
              onPress={async () => {
                setShareModalVisible(false);
                await handleShare();
              }}
            >
              <Ionicons name="share-outline" size={18} color="#fff" />
              <Text style={s.exportBtnText}>Share</Text>
            </Pressable>
          </View>
        </SafeAreaView>
      </Modal>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { fontSize: 14, color: C.textMuted },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  iconBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 16, fontWeight: '700', color: C.text },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 24 },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    marginBottom: 16,
  },
  bannerGreen: { backgroundColor: C.primaryContainer },
  bannerAmber: { backgroundColor: '#fef3c7' },
  statusText: { fontSize: 13, fontWeight: '700' },
  card: {
    backgroundColor: C.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  doctorAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: C.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  doctorInfo: { flex: 1 },
  doctorName: { fontSize: 18, fontWeight: '800', color: C.text },
  doctorSpecialty: { fontSize: 13, color: C.textMuted, marginTop: 3 },
  divider: { height: 1, backgroundColor: C.border, marginBottom: 12 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  detailLabel: { fontSize: 13, color: C.textMuted, width: 48 },
  detailValue: { fontSize: 13, fontWeight: '600', color: C.text, flex: 1 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: C.text },
  bodyText: { fontSize: 14, color: C.text, lineHeight: 22 },
  emptyRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  emptyText: { fontSize: 14, color: C.textMuted },
  followUpCard: { flexDirection: 'row', alignItems: 'center' },
  followUpLabel: { fontSize: 12, color: C.textMuted },
  followUpDate: { fontSize: 15, fontWeight: '700', color: C.primary, marginTop: 2 },
  footer: {
    backgroundColor: C.surface,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  exportBtn: {
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: 14,
    gap: 8,
  },
  exportBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  modal: { flex: 1, backgroundColor: C.bg },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: { fontSize: 16, fontWeight: '700', color: C.text },
  modalFooter: { padding: 16, borderTopWidth: 1, borderTopColor: C.border },
  previewText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    fontSize: 12,
    color: C.text,
    lineHeight: 19,
  },
});
