import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams } from 'expo-router';
import { CheckCircle2, ShieldCheck, ListChecks } from 'lucide-react-native';
import { Colors } from '@/constants/colors';
import { Typography } from '@/constants/typography';
import { Spacing } from '@/constants/spacing';
import { Radius } from '@/constants/radius';
import { shadow1 } from '@/constants/shadows';
import ScreenHeader from '@/components/ScreenHeader';
import StateView from '@/components/StateView';
import PrimaryButton from '@/components/PrimaryButton';
import { useAiNote, useApproveAiNote } from '@/features/ainotes/hooks';
import { AI_NOTE_STATUS_META } from '@/features/ainotes/api';

export default function AiNoteDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const noteId = String(id);
  const { data: note, isLoading, isError, refetch } = useAiNote(noteId);
  const approve = useApproveAiNote();

  if (isLoading) return <Wrap><StateView kind="loading" message="Loading…" /></Wrap>;
  if (isError || !note) return <Wrap><StateView kind="error" title="Couldn't load" message="Please try again." actionLabel="Retry" onAction={() => refetch()} /></Wrap>;

  const meta = AI_NOTE_STATUS_META[note.status];
  const approved = !!note.approvedAt;

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <ScreenHeader title={note.title} subtitle={note.model ? `Generated by ${note.model}` : 'Meeting notes'} />
      <ScrollView contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>
        <View style={styles.row}>
          <View style={[styles.statusBadge, { backgroundColor: meta.bg }]}>
            <Text style={[styles.statusText, { color: meta.color }]}>{meta.label}</Text>
          </View>
          {approved ? (
            <View style={styles.approvedBadge}>
              <ShieldCheck size={14} color={Colors.teal} strokeWidth={2} />
              <Text style={styles.approvedText}>Approved</Text>
            </View>
          ) : null}
        </View>

        <Section title="Summary">
          <Text style={styles.summary}>{note.summary || '—'}</Text>
        </Section>

        {note.actionItems.length > 0 ? (
          <Section title="Action items" icon={<ListChecks size={16} color={Colors.onSurface} strokeWidth={2} />}>
            {note.actionItems.map((a, i) => (
              <View key={i} style={styles.actionRow}>
                <CheckCircle2 size={16} color={Colors.teal} strokeWidth={1.8} />
                <Text style={styles.actionText}>
                  {a.task}
                  {a.assignee ? <Text style={styles.dim}>{`  · ${a.assignee}`}</Text> : null}
                  {a.dueDate ? <Text style={styles.dim}>{`  · due ${a.dueDate}`}</Text> : null}
                </Text>
              </View>
            ))}
          </Section>
        ) : null}

        {note.decisions.length > 0 ? (
          <Section title="Decisions">
            {note.decisions.map((d, i) => (
              <Text key={i} style={styles.decision}>• {d}</Text>
            ))}
          </Section>
        ) : null}

        {note.status === 'complete' && !approved ? (
          <PrimaryButton
            label={approve.isPending ? 'Approving…' : 'Approve notes'}
            onPress={() => approve.mutate(noteId)}
            loading={approve.isPending}
          />
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
}

function Wrap({ children }: { children: React.ReactNode }) {
  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <ScreenHeader title="AI Note" />
      {children}
    </SafeAreaView>
  );
}

function Section({ title, icon, children }: { title: string; icon?: React.ReactNode; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <View style={styles.sectionHead}>
        {icon}
        <Text style={styles.sectionTitle}>{title}</Text>
      </View>
      {children}
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  body: { padding: Spacing.containerMargin, gap: Spacing.md, paddingBottom: Spacing.xxl },
  row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  statusBadge: { borderRadius: Radius.full, paddingHorizontal: 10, paddingVertical: 4 },
  statusText: { ...Typography.labelSm, fontWeight: '700' },
  approvedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.iconBgTeal, borderRadius: Radius.full, paddingHorizontal: 10, paddingVertical: 4 },
  approvedText: { ...Typography.labelSm, color: Colors.teal, fontWeight: '700' },
  section: { backgroundColor: Colors.surfaceContainerLowest, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.surfaceContainerLow, padding: Spacing.md, gap: Spacing.sm, ...shadow1 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  sectionTitle: { ...Typography.titleMd, color: Colors.onSurface },
  summary: { ...Typography.bodyMd, color: Colors.onSurfaceVariant },
  actionRow: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm },
  actionText: { ...Typography.bodyMd, color: Colors.onSurface, flex: 1 },
  decision: { ...Typography.bodyMd, color: Colors.onSurface },
  dim: { ...Typography.bodySm, color: Colors.outline },
});
