'use client';

// A2 — Referral Analytics Dashboard. Program health at a glance. Reward cost as a
// % of platform margin is the north-star number, shown prominently.
// RBAC: referral.admin.analytics (Finance / Product / Executive).

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { getAnalytics, formatNaira } from '@/services/referralRewardsAdminService';
import type { ReferralAnalytics } from '@/types/referralRewardsAdmin';
import { Page, PageHeader, Card, Button, Badge, colors, tint, thCell, tdCell } from '@/components/ui/vuexy';
import { timeAgo } from '../_ui';

const REWARDS_TABS = [
  { href: '/admin/referral-rewards/config', label: 'A1 · Config', key: 'config' },
  { href: '/admin/referral-rewards/analytics', label: 'A2 · Analytics', key: 'analytics' },
  { href: '/admin/referral-rewards/fraud', label: 'A3 · Fraud queue', key: 'fraud' },
  { href: '/admin/referral-rewards/ledger', label: 'A4 · Ledger', key: 'ledger' },
  { href: '/admin/referral-rewards/case', label: 'A5 · Case view', key: 'case' },
  { href: '/admin/referral-rewards/milestones', label: 'A6 · Milestones', key: 'milestones' },
  { href: '/admin/referral-rewards/module-status', label: 'A7 · Module status', key: 'module-status' },
];

function RewardsTabs({ active }: { active: string }) {
  return (
    <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 20, borderBottom: `1px solid ${colors.border}`, paddingBottom: 8 }}>
      {REWARDS_TABS.map((t) => (
        <Link
          key={t.key}
          href={t.href}
          style={{
            textDecoration: 'none', padding: '6px 12px', borderRadius: 6, fontSize: 13, fontWeight: 600,
            color: active === t.key ? '#fff' : colors.text,
            background: active === t.key ? colors.primary : tint(colors.primary, 0.06),
          }}
        >
          {t.label}
        </Link>
      ))}
    </div>
  );
}

const TIER_BADGE: Record<string, string> = {
  starter: colors.secondary,
  growth: colors.info,
  pro: colors.primary,
  elite: colors.warning,
};

function Kpi({ label: lbl, value, sub, accent }: { label: string; value: string; sub?: string; accent?: string }) {
  return (
    <div style={{ border: `1px solid ${colors.border}`, borderRadius: 8, padding: '14px 16px', background: colors.card }}>
      <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.4, color: colors.muted, fontWeight: 700 }}>{lbl}</div>
      <div style={{ fontSize: 22, fontWeight: 800, marginTop: 4, color: accent ?? colors.text }}>{value}</div>
      {sub ? <div style={{ fontSize: 12, color: colors.muted, marginTop: 2 }}>{sub}</div> : null}
    </div>
  );
}

export default function ReferralRewardsAnalyticsPage() {
  const [data, setData] = useState<ReferralAnalytics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true); setError(null);
    try { setData(await getAnalytics()); }
    catch (e) { setError(String(e)); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);

  return (
    <Page>
      <PageHeader
        title="Referral Analytics Dashboard"
        subtitle="Program health at a glance. The north-star metric is reward cost as a % of the margin generated by referred users — the number that tells us whether the program is sustainable at scale. (A2)"
        actions={<Button variant="outline" onClick={load}>Refresh</Button>}
      />
      <RewardsTabs active="analytics" />

      {loading ? (
        <p style={{ color: colors.muted }}>Loading…</p>
      ) : error ? (
        <p style={{ color: colors.danger }}>{error}</p>
      ) : data ? (
        <>
          {/* North-star, prominent */}
          <div style={{ border: `1px solid ${colors.primary}`, background: tint(colors.primary, 0.06), borderRadius: 12, padding: '20px 24px', marginBottom: 20 }}>
            <div style={{ fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4, color: colors.primary, fontWeight: 700 }}>North-star · Reward cost as % of margin</div>
            <div style={{ fontSize: 44, fontWeight: 800, color: colors.primary, lineHeight: 1.1, marginTop: 4 }}>{data.reward_cost_pct.toFixed(2)}%</div>
            <div style={{ fontSize: 13, color: colors.muted, marginTop: 4 }}>
              {formatNaira(data.total_rewards_paid_kobo)} rewards paid ÷ {formatNaira(data.total_margin_kobo)} platform margin from referred users
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px,1fr))', gap: 12, marginBottom: 20 }}>
            <Kpi label="Active referrers" value={data.active_referrers.toLocaleString()} />
            <Kpi label="Active referred users" value={data.active_referred_users.toLocaleString()} />
            <Kpi label="Total rewards paid" value={formatNaira(data.total_rewards_paid_kobo)} accent={colors.success} />
            <Kpi label="Total margin (referred)" value={formatNaira(data.total_margin_kobo)} />
          </div>

          <Card title="Breakdown by module" style={{ marginBottom: 16 }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 12 }}>
              <thead><tr><th style={thCell}>Module</th><th style={thCell}>Rewards paid</th><th style={thCell}>Reward count</th><th style={thCell}>Last event</th></tr></thead>
              <tbody>
                {data.by_module.map((m) => (
                  <tr key={m.module}>
                    <td style={tdCell}><strong style={{ textTransform: 'capitalize' }}>{m.module}</strong></td>
                    <td style={tdCell}>{formatNaira(m.reward_kobo)}</td>
                    <td style={tdCell}>{m.reward_count.toLocaleString()}</td>
                    <td style={{ ...tdCell, color: colors.muted }}>{timeAgo(m.last_event_at)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>

          <Card title="Breakdown by tier">
            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 12 }}>
              <thead><tr><th style={thCell}>Tier</th><th style={thCell}>Referrers</th></tr></thead>
              <tbody>
                {data.by_tier.map((t) => (
                  <tr key={t.tier}>
                    <td style={tdCell}><Badge text={t.tier} color={TIER_BADGE[t.tier.toLowerCase()] ?? colors.secondary} /></td>
                    <td style={tdCell}>{t.referrer_count.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        </>
      ) : null}
    </Page>
  );
}
