'use client';

// A2 — Referral Analytics Dashboard. Program health at a glance. Reward cost as a
// % of platform margin is the north-star number, shown prominently.
// RBAC: referral.admin.analytics (Finance / Product / Executive).

import { useEffect, useState } from 'react';
import { getAnalytics, formatNaira } from '@/services/referralRewardsAdminService';
import type { ReferralAnalytics } from '@/types/referralRewardsAdmin';
import { PageHeader, RewardsTabs, Card, Kpi, Badge, StateBlock, btn, th, td, timeAgo } from '../_ui';

export default function ReferralRewardsAnalyticsPage() {
  const [data, setData] = useState<ReferralAnalytics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true); setError(null);
    try { setData(await getAnalytics()); }
    catch (e) { setError(String(e)); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);

  return (
    <div style={{ padding: '0.5rem 0.5rem 2rem' }}>
      <PageHeader
        title="Referral Analytics Dashboard"
        subtitle="Program health at a glance. The north-star metric is reward cost as a % of the margin generated by referred users — the number that tells us whether the program is sustainable at scale. (A2)"
        action={<button onClick={load} style={btn()}>Refresh</button>}
      />
      <RewardsTabs active="analytics" />

      <StateBlock loading={loading} error={error} empty={false}>
        {data && (
          <>
            {/* North-star, prominent */}
            <div style={{ border: '1px solid #340075', background: '#f5f3ff', borderRadius: '0.75rem', padding: '1.25rem 1.5rem', marginBottom: '1.25rem' }}>
              <div style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: 0.4, color: '#5b21b6', fontWeight: 700 }}>North-star · Reward cost as % of margin</div>
              <div style={{ fontSize: '2.75rem', fontWeight: 800, color: '#340075', lineHeight: 1.1, marginTop: '0.25rem' }}>{data.reward_cost_pct.toFixed(2)}%</div>
              <div style={{ fontSize: '0.85rem', color: '#6b7280', marginTop: '0.25rem' }}>
                {formatNaira(data.total_rewards_paid_kobo)} rewards paid ÷ {formatNaira(data.total_margin_kobo)} platform margin from referred users
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px,1fr))', gap: '0.75rem', marginBottom: '1.25rem' }}>
              <Kpi label="Active referrers" value={data.active_referrers.toLocaleString()} />
              <Kpi label="Active referred users" value={data.active_referred_users.toLocaleString()} />
              <Kpi label="Total rewards paid" value={formatNaira(data.total_rewards_paid_kobo)} accent="#15803d" />
              <Kpi label="Total margin (referred)" value={formatNaira(data.total_margin_kobo)} />
            </div>

            <Card title="Breakdown by module">
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead><tr><th style={th()}>Module</th><th style={th()}>Rewards paid</th><th style={th()}>Reward count</th><th style={th()}>Last event</th></tr></thead>
                <tbody>
                  {data.by_module.map((m) => (
                    <tr key={m.module}>
                      <td style={td()}><strong style={{ textTransform: 'capitalize' }}>{m.module}</strong></td>
                      <td style={td()}>{formatNaira(m.reward_kobo)}</td>
                      <td style={td()}>{m.reward_count.toLocaleString()}</td>
                      <td style={{ ...td(), color: '#6b7280' }}>{timeAgo(m.last_event_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Card>

            <Card title="Breakdown by tier">
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead><tr><th style={th()}>Tier</th><th style={th()}>Referrers</th></tr></thead>
                <tbody>
                  {data.by_tier.map((t) => (
                    <tr key={t.tier}>
                      <td style={td()}><Badge status={t.tier} /></td>
                      <td style={td()}>{t.referrer_count.toLocaleString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Card>
          </>
        )}
      </StateBlock>
    </div>
  );
}
