#!/usr/bin/env bash
# ============================================================================
#  apply-env.sh — split launch/master.env into each surface's .env file.
#  Fill launch/master.env (from master.env.template), then run this script.
#  Re-run after rotating any key. Existing targets are backed up first.
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MASTER="$ROOT/launch/master.env"
STAMP="$(date +%Y%m%d%H%M%S)"

if [[ ! -f "$MASTER" ]]; then
  echo "ERROR: $MASTER not found."
  echo "  Run: cp launch/master.env.template launch/master.env  then fill it in."
  exit 1
fi

# Load master.env into the environment (all keys become shell vars).
set -a; # shellcheck disable=SC1090
. "$MASTER"; set +a

# Defaults for anything left blank in master.env (keeps output valid).
: "${PAYSTACK_DVA_BANK:=wema-bank}"
: "${MAPLERAD_PROD:=false}"; : "${EVERSEND_PROD:=false}"
# R2_BUCKET is deliberately NOT defaulted. It used to fall back to
# "spotlight-open-mic", a bucket that does not exist in the account, which
# made every generated environment look configured and then fail at upload
# time with NoSuchBucket. Blank flows through to the backend, where an empty
# bucket fails closed as "uploads are not configured" — an honest 503 rather
# than a broken PUT. Set it in master.env.
: "${MAPS_PROVIDER:=mock}"
: "${SITE_URL_WEB:=http://localhost:3000}"
: "${API_BASE_URL_PUBLIC:=http://localhost:8080/api/v1}"
: "${GO_BACKEND_URL:=http://localhost:8080}"
: "${ADMIN_API_BASE_URL:=http://localhost:8080/api/v1}"
: "${CORS_ALLOW_ORIGINS:=http://localhost:3000,http://localhost:4030}"
: "${REDIS_URL:=redis://localhost:6379}"
: "${TERMII_SENDER_ID:=Paymax}"
: "${RESEND_FROM_EMAIL:=Spotlight <no-reply@spotlightng.com>}"
: "${EMAIL_FROM:=Spotlight <no-reply@spotlightng.com>}"
: "${MAILGUN_REGION:=us}"

# Derive the R2 S3 endpoint from the account id when not given explicitly.
if [[ -z "${R2_ACCOUNT_ENDPOINT:-}" && -n "${R2_ACCOUNT_ID:-}" ]]; then
  R2_ACCOUNT_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
fi

# ---- Core+Payments launch feature flags. Edit here to widen the launch. -----
# Foundational money path ON; risk-sensitive features default OFF until ready.
read -r -d '' FEATURE_FLAGS <<'FLAGS' || true
FEATURE_WALLET_ENABLED=true
FEATURE_KYC_ENABLED=true
FEATURE_VIRTUAL_ACCOUNTS_ENABLED=true
FEATURE_TIER_LIMITS_ENABLED=true
FEATURE_REFERRALS_ENABLED=false
FEATURE_TRANSFERS_ENABLED=false
FEATURE_WALLET_TRANSFERS_ENABLED=false
FEATURE_BANK_TRANSFERS_ENABLED=false
FEATURE_DISPUTES_ENABLED=false
FEATURE_RATINGS_ENABLED=false
FEATURE_FX_ENABLED=false
FEATURE_FX_ORCHESTRATION_ENABLED=false
FEATURE_UTILITY_PAYMENTS_ENABLED=false
FEATURE_ESTATE_ENABLED=false
FEATURE_REALTOR_ENABLED=false
FEATURE_PROPERTY_SUITE_ENABLED=false
FEATURE_MAPS_ENABLED=false
FLAGS

backup() { if [[ -f "$1" ]]; then cp "$1" "$1.bak.$STAMP"; echo "  backed up $1 → $1.bak.$STAMP"; fi; return 0; }
write() { local p="$1"; shift; mkdir -p "$(dirname "$p")"; backup "$p"; cat > "$p"; chmod 600 "$p"; echo "  wrote $p (chmod 600)"; }

echo "Applying launch/master.env → per-surface .env files ..."

# ---- backend/.env -----------------------------------------------------------
write "$ROOT/backend/.env" <<EOF
# Generated by launch/apply-env.sh on $STAMP — DO NOT COMMIT.
APP_PORT=8080
CORS_ALLOW_ORIGINS=$CORS_ALLOW_ORIGINS
DATABASE_URL=${DATABASE_URL:-}
REDIS_URL=$REDIS_URL
SUPABASE_URL=${SUPABASE_URL:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
ADMIN_API_KEY=${ADMIN_API_KEY:-}
PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY:-}
PAYSTACK_WEBHOOK_SECRET=${PAYSTACK_WEBHOOK_SECRET:-}
MAPLERAD_SECRET_KEY=${MAPLERAD_SECRET_KEY:-}
MAPLERAD_PUBLIC_KEY=${MAPLERAD_PUBLIC_KEY:-}
MAPLERAD_PROD=$MAPLERAD_PROD
MAPLERAD_WEBHOOK_SECRET=${MAPLERAD_WEBHOOK_SECRET:-}
EVERSEND_CLIENT_ID=${EVERSEND_CLIENT_ID:-}
EVERSEND_CLIENT_SECRET=${EVERSEND_CLIENT_SECRET:-}
EVERSEND_PROD=$EVERSEND_PROD
EVERSEND_WEBHOOK_SECRET=${EVERSEND_WEBHOOK_SECRET:-}
R2_ACCOUNT_ENDPOINT=${R2_ACCOUNT_ENDPOINT:-}
R2_BUCKET=${R2_BUCKET:-}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID:-}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY:-}
R2_REGION=auto
RESEND_API_KEY=${RESEND_API_KEY:-}
RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
TERMII_API_KEY=${TERMII_API_KEY:-}
TERMII_SENDER_ID=$TERMII_SENDER_ID
EXPO_PUSH_TOKEN=${EXPO_PUSH_TOKEN:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
AGORA_APP_ID=${AGORA_APP_ID:-}
AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE:-}
VIDEOSDK_API_KEY=${VIDEOSDK_API_KEY:-}
VIDEOSDK_SECRET=${VIDEOSDK_SECRET:-}
MAPS_PROVIDER=$MAPS_PROVIDER
MAPS_GEOAPIFY_KEY=${MAPS_GEOAPIFY_KEY:-}
MAPS_MAPTILER_KEY=${MAPS_MAPTILER_KEY:-}
MAPS_OSRM_BASE_URL=${MAPS_OSRM_BASE_URL:-}
MAPS_GOOGLE_KEY=${MAPS_GOOGLE_KEY:-}
MAPS_MAPBOX_TOKEN=${MAPS_MAPBOX_TOKEN:-}
INVEST_BROKER_BASE_URL=${INVEST_BROKER_BASE_URL:-}
INVEST_BROKER_API_KEY=${INVEST_BROKER_API_KEY:-}
INVEST_BROKER_WEBHOOK_SECRET=${INVEST_BROKER_WEBHOOK_SECRET:-}
INVEST_MARKETDATA_BASE_URL=${INVEST_MARKETDATA_BASE_URL:-}
INVEST_MARKETDATA_API_KEY=${INVEST_MARKETDATA_API_KEY:-}
PAYMAX_WEBHOOK_OUT_URL=${PAYMAX_WEBHOOK_OUT_URL:-}
PAYMAX_WEBHOOK_SECRET=${PAYMAX_WEBHOOK_SECRET:-}
CONNECT_VERIFICATION_PEPPER=${CONNECT_VERIFICATION_PEPPER:-}
$FEATURE_FLAGS
EOF

# ---- frontend-web/.env.local ------------------------------------------------
write "$ROOT/frontend-web/.env.local" <<EOF
# Generated by launch/apply-env.sh on $STAMP — DO NOT COMMIT.
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY:-}
PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY:-}
PAYSTACK_DVA_BANK=$PAYSTACK_DVA_BANK
R2_ACCOUNT_ID=${R2_ACCOUNT_ID:-}
CLOUDFLARE_ACCOUNT_ID=${R2_ACCOUNT_ID:-}
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID:-}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY:-}
R2_BUCKET=${R2_BUCKET:-}
R2_ENDPOINT=${R2_ACCOUNT_ENDPOINT:-}
R2_PUBLIC_BASE_URL=${R2_PUBLIC_BASE_URL:-}
MAILGUN_API_KEY=${MAILGUN_API_KEY:-}
MAILGUN_DOMAIN=${MAILGUN_DOMAIN:-}
MAILGUN_REGION=$MAILGUN_REGION
RESEND_API_KEY=${RESEND_API_KEY:-}
EMAIL_FROM=$EMAIL_FROM
VTPASS_ENVIRONMENT=${VTPASS_ENVIRONMENT:-}
VTPASS_API_KEY=${VTPASS_API_KEY:-}
VTPASS_PUBLIC_KEY=${VTPASS_PUBLIC_KEY:-}
VTPASS_SECRET_KEY=${VTPASS_SECRET_KEY:-}
UTILITY_PROVIDER_CREDENTIALS_KEY=${UTILITY_PROVIDER_CREDENTIALS_KEY:-}
NEXT_PUBLIC_SITE_URL=$SITE_URL_WEB
NEXT_PUBLIC_API_BASE_URL=$API_BASE_URL_PUBLIC
GO_BACKEND_URL=$GO_BACKEND_URL
GO_API_BASE_URL=$GO_BACKEND_URL
DATABASE_URL=${DATABASE_URL:-}
REDIS_URL=$REDIS_URL
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
ANTHROPIC_REALTOR_MODEL=claude-haiku-4-5-20251001
MAPLERAD_SECRET_KEY=${MAPLERAD_SECRET_KEY:-}
MAPLERAD_PROD=$MAPLERAD_PROD
SPOTLIGHT_ADMIN_API_KEY=${ADMIN_API_KEY:-}
STITCH_API_KEY=${STITCH_API_KEY:-}
$FEATURE_FLAGS
EOF

# ---- frontend-admin/.env.local ----------------------------------------------
write "$ROOT/frontend-admin/.env.local" <<EOF
# Generated by launch/apply-env.sh on $STAMP — DO NOT COMMIT.
NEXT_PUBLIC_ADMIN_API_BASE_URL=$ADMIN_API_BASE_URL
NEXT_PUBLIC_LEGACY_ADMIN_BASE_URL=${LEGACY_ADMIN_BASE_URL:-http://localhost:4028}
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
NEXT_PUBLIC_ADMIN_API_KEY=${ADMIN_API_KEY:-}
# Module mock flags: flip a module to false only after its backend is live.
# (Defaults live in code; uncomment to override per go-live.)
# NEXT_PUBLIC_ESTATE_ADMIN_USE_MOCK=false
# NEXT_PUBLIC_REALTOR_ADMIN_USE_MOCK=false
EOF

# ---- mobile-app/reactnative/.env --------------------------------------------
write "$ROOT/mobile-app/reactnative/.env" <<EOF
# Generated by launch/apply-env.sh on $STAMP — DO NOT COMMIT.
EXPO_PUBLIC_APP_ENV=${APP_ENV:-production}
EXPO_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
EXPO_PUBLIC_API_BASE_URL=$SITE_URL_WEB
EXPO_PUBLIC_MAPS_BASE_URL=$API_BASE_URL_PUBLIC
EXPO_PUBLIC_PASSWORD_RESET_REDIRECT_URL=paymaxrn://auth/reset-password
# Module mock flags: see mobile-app/reactnative/.env.production.example for the
# full list. Flip a module to false only once its backend is live & smoke-tested.
EOF

echo
echo "Done. Review the generated files, then start each service."
echo "Reminder: master.env and all generated .env files are git-ignored."
