#!/bin/bash
set -euo pipefail

# React Native APK Build Script
# Sets up Java environment, builds a release APK, then VERIFIES what got baked in.
#
# Why the verification step exists (2026-09-11):
#   A release APK shipped with `http://localhost:8091` as its API base and zero
#   references to the remote backend, so the app showed "internet connection
#   issue" on an emulator. Cause: `.env.local` outranks `.env.production` in
#   Expo's precedence (.env.<mode>.local > .env.local > .env.<mode> > .env), and
#   `getDevUrl()` short-circuits on `if (!__DEV__) return url`, so nothing
#   rewrites a loopback host in a release build. The env file was renamed to
#   `.env.development.local`; this check is the backstop that catches any
#   recurrence BEFORE the APK reaches a device.

JAVA_HOME=/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
export JAVA_HOME

# Expo picks its .env files from NODE_ENV. Set it explicitly: if it is unset,
# @expo/env falls back to only `.env.local` and `.env` and silently skips
# `.env.production` entirely.
export NODE_ENV="${NODE_ENV:-production}"

# arm64-v8a only: the APK shipped 4 ABIs (armeabi-v7a, arm64-v8a, x86, x86_64),
# i.e. four copies of libreactnative.so/libhermes.so/libjsc.so etc. Play Store
# devices are all arm64 now. Override to add 32-bit or x86_64 for local emulator
# smoke tests: REACT_NATIVE_ARCHS=arm64-v8a,x86_64 ./build-apk.sh
REACT_NATIVE_ARCHS="${REACT_NATIVE_ARCHS:-arm64-v8a}"
export REACT_NATIVE_ARCHS

# `npx expo prebuild --clean` wipes android/local.properties, which is where
# gradle normally reads sdk.dir from. Without it the build dies with
# "SDK location not found. Define a valid SDK location with an ANDROID_HOME
# environment variable or by setting the sdk.dir path in .../local.properties".
if [[ -z "${ANDROID_HOME:-}" && -z "${ANDROID_SDK_ROOT:-}" ]]; then
  for sdk_candidate in "$HOME/Library/Android/sdk" "$HOME/Android/Sdk" /usr/local/share/android-sdk; do
    if [[ -d "$sdk_candidate" ]]; then
      export ANDROID_HOME="$sdk_candidate"
      break
    fi
  done
fi

# @sentry/react-native hooks a source-map upload into every release build and
# hard-fails gradle when it has no credentials:
#   error: An organization ID or slug is required (provide with --org)
# (android/sentry.properties is regenerated by prebuild with only defaults.url).
# Source maps are never packaged into the APK, so skipping the upload changes
# nothing about the artifact — it only leaves crashes unsymbolicated in Sentry
# for builds made without credentials.
if [[ -z "${SENTRY_AUTH_TOKEN:-}" ]]; then
  export SENTRY_DISABLE_AUTO_UPLOAD=true
  SENTRY_UPLOAD="skipped (no SENTRY_AUTH_TOKEN)"
else
  SENTRY_UPLOAD="enabled"
fi

# Production signing. Without this gradle signs release with app/debug.keystore
# (CN=Android Debug): Play rejects those uploads, and a debug-signed APK cannot
# upgrade an install signed with the real key. The keystore lives in $HOME --
# never in android/, which `expo prebuild --clean` deletes in full, and never in
# the repo, because it is the one file that must not leak. Credentials are read
# into the environment here and passed to gradle as project properties; nothing
# in this script prints them.
RELEASE_SIGNING_PROPS="${PAYMAX_RELEASE_SIGNING_PROPS:-$HOME/.android-keystores/paymax-release.properties}"
if [[ -f "$RELEASE_SIGNING_PROPS" ]]; then
  set -a
  . "$RELEASE_SIGNING_PROPS"
  set +a
fi

# Failing here rather than after the build: gradle only warns when credentials
# are unusable and quietly falls back to the debug key.
MISSING_SIGNING_VARS=""
for signing_var in PAYMAX_RELEASE_STORE_FILE PAYMAX_RELEASE_KEY_ALIAS PAYMAX_RELEASE_STORE_PASSWORD PAYMAX_RELEASE_KEY_PASSWORD; do
  if [[ -z "${!signing_var:-}" ]]; then
    MISSING_SIGNING_VARS="${MISSING_SIGNING_VARS}${MISSING_SIGNING_VARS:+, }$signing_var"
  fi
done
if [[ -z "$MISSING_SIGNING_VARS" && ! -f "$PAYMAX_RELEASE_STORE_FILE" ]]; then
  MISSING_SIGNING_VARS="PAYMAX_RELEASE_STORE_FILE (set to a path that does not exist)"
fi

if [[ -n "$MISSING_SIGNING_VARS" ]]; then
  if [[ "${ALLOW_DEBUG_SIGNING:-0}" == "1" ]]; then
    SIGNING_DESC="DEBUG key (ALLOW_DEBUG_SIGNING=1; missing: $MISSING_SIGNING_VARS)"
  else
    echo "❌ Release signing credentials unavailable: $MISSING_SIGNING_VARS" >&2
    echo "   Expected in $RELEASE_SIGNING_PROPS (override with PAYMAX_RELEASE_SIGNING_PROPS)," >&2
    echo "   or in the environment under those exact names." >&2
    echo "   The keystore lives outside android/ because 'expo prebuild --clean' wipes it." >&2
    echo "   For a throwaway debug-signed build: ALLOW_DEBUG_SIGNING=1 ./build-apk.sh" >&2
    exit 1
  fi
else
  SIGNING_DESC="$(basename "$PAYMAX_RELEASE_STORE_FILE"), alias $PAYMAX_RELEASE_KEY_ALIAS"
fi

cd "$(dirname "$0")"
PROJECT_DIR="$PWD"

ENV_FILE=".env.${NODE_ENV}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "❌ $ENV_FILE not found — a release build has no API URLs to bake in." >&2
  exit 1
fi

# `|| true`: under `set -e`+pipefail a non-matching grep would abort the script
# before it could print the explanatory error below.
EXPECTED_API="$(grep -E '^EXPO_PUBLIC_API_BASE_URL=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
EXPECTED_SUPABASE="$(grep -E '^EXPO_PUBLIC_SUPABASE_URL=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"

if [[ -z "$EXPECTED_API" ]]; then
  echo "❌ EXPO_PUBLIC_API_BASE_URL is not set in $ENV_FILE." >&2
  exit 1
fi

# A higher-priority file would silently override $ENV_FILE. Refuse to build blind.
for shadow in ".env.${NODE_ENV}.local" ".env.local"; do
  if [[ -f "$shadow" ]] && grep -qE '^EXPO_PUBLIC_(API_BASE_URL|SUPABASE_URL)=' "$shadow"; then
    echo "❌ $shadow sets API/Supabase URLs and OUTRANKS $ENV_FILE." >&2
    echo "   Expo precedence: .env.<mode>.local > .env.local > .env.<mode> > .env" >&2
    echo "   Rename it to .env.development.local so it applies to dev only." >&2
    exit 1
  fi
done

echo "🔨 Building React Native APK..."
echo "   JAVA_HOME: $JAVA_HOME"
echo "   NODE_ENV:  $NODE_ENV  (env file: $ENV_FILE)"
echo "   API base:  $EXPECTED_API"
echo "   Supabase:  $EXPECTED_SUPABASE"
echo "   ABIs:      $REACT_NATIVE_ARCHS"
echo "   Sentry:    $SENTRY_UPLOAD"
echo "   Signing:   $SIGNING_DESC"
echo ""

if [[ -z "${ANDROID_HOME:-}" && -z "${ANDROID_SDK_ROOT:-}" && ! -f android/local.properties ]]; then
  echo "❌ Android SDK not found. Set ANDROID_HOME, or put sdk.dir=<path> in android/local.properties." >&2
  exit 1
fi

# -PreactNativeArchitectures is inert here (newArchEnabled=false makes RNGP skip
# ndk.abiFilters entirely). -PreleaseAbis is what plugins/withAndroidSizeOptimizations.js
# reads to scope variant.packaging.jniLibs excludes/pickFirsts for release builds.
# `clean` triggers :app:externalNativeBuildCleanRelease, which re-runs CMake when
# app/.cxx holds a stale cache. That re-run races the parallel <lib>:clean tasks
# that delete node_modules/<lib>/android/build/generated/source/codegen/jni, so
# CMake dies with "add_subdirectory given source ... which is not an existing
# directory". Dropping .cxx (CMake's own scratch dir, rebuilt either way) makes
# the clean step a no-op instead of a failure.
rm -rf android/app/.cxx

# Signing credentials go through -P, not the environment: a warm gradle daemon
# keeps the environment it was started with, so System.getenv() in the build
# script can return a stale value, while project properties always travel with
# the invocation. (-P values are readable via `ps` on this machine; that is the
# accepted trade for a working daemon.) plugins/withAndroidReleaseSigning.js
# reads exactly these names.
if [[ "${ALLOW_DEBUG_SIGNING:-0}" == "1" ]]; then
  echo "⚠️  ALLOW_DEBUG_SIGNING=1 — the APK will be signed with the debug key and is NOT publishable."
fi

cd android
./gradlew clean assembleRelease \
  -PreactNativeArchitectures="$REACT_NATIVE_ARCHS" \
  -PreleaseAbis="$REACT_NATIVE_ARCHS" \
  -PPAYMAX_RELEASE_STORE_FILE="${PAYMAX_RELEASE_STORE_FILE:-}" \
  -PPAYMAX_RELEASE_KEY_ALIAS="${PAYMAX_RELEASE_KEY_ALIAS:-}" \
  -PPAYMAX_RELEASE_STORE_PASSWORD="${PAYMAX_RELEASE_STORE_PASSWORD:-}" \
  -PPAYMAX_RELEASE_KEY_PASSWORD="${PAYMAX_RELEASE_KEY_PASSWORD:-}"
cd "$PROJECT_DIR"

APK="$(find android/app/build/outputs/apk -name '*.apk' -type f | head -1 || true)"
if [[ -z "$APK" ]]; then
  echo "❌ Build reported success but produced no APK." >&2
  exit 1
fi

echo ""
echo "🔍 Verifying baked-in configuration: $APK"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
unzip -o -q "$APK" 'assets/index.android.bundle' -d "$WORK"
BUNDLE="$WORK/assets/index.android.bundle"

if [[ ! -f "$BUNDLE" ]]; then
  echo "❌ APK contains no JS bundle at assets/index.android.bundle." >&2
  exit 1
fi

fail=0

# 1. The remote host must actually be present in the shipped bundle.
EXPECTED_HOST="$(printf '%s' "$EXPECTED_API" | sed -E 's#^https?://##; s#/.*$##')"
if grep -aq "$EXPECTED_HOST" "$BUNDLE"; then
  echo "   ✅ API host present: $EXPECTED_HOST"
else
  echo "   ❌ API host MISSING from bundle: $EXPECTED_HOST" >&2
  fail=1
fi

# 2. No loopback host may survive as a *configured base URL*. `getDevUrl()`
#    legitimately contains the literals "127.0.0.1" and "10.0.2.2" as replace()
#    arguments, so match host:port pairs, which only appear in baked config.
if grep -aoE '(localhost|127\.0\.0\.1|10\.0\.2\.2):(8091|54321|3000|3001)' "$BUNDLE" | sort -u | grep -q .; then
  echo "   ❌ Loopback backend URLs baked into the release bundle:" >&2
  grep -aoE '(localhost|127\.0\.0\.1|10\.0\.2\.2):(8091|54321|3000|3001)' "$BUNDLE" | sort -u | sed 's/^/      /' >&2
  echo "      A device cannot reach these — this is the \"internet connection issue\" bug." >&2
  fail=1
else
  echo "   ✅ No loopback backend URLs in bundle"
fi

# 3. Only the requested ABIs may ship. This is the backstop for the ABI filter:
#    RNGP's old-arch pickFirsts (libfbjni/libc++_shared/libhermes/libhermestooling)
#    outrank jniLibs excludes, so a filter regression silently re-adds ~10 MiB of
#    foreign-ABI .so instead of failing the build.
EXPECTED_ABIS="$(printf '%s' "$REACT_NATIVE_ARCHS" | tr ',' '\n' | sed 's/^ *//; s/ *$//' | grep . | sort -u)"
ACTUAL_ABIS="$(unzip -Z1 "$APK" 'lib/*/*.so' 2>/dev/null | cut -d/ -f2 | sort -u)"
if [[ -z "$ACTUAL_ABIS" ]]; then
  echo "   ❌ APK contains no native libraries at all." >&2
  fail=1
elif ! diff <(printf '%s\n' "$EXPECTED_ABIS") <(printf '%s\n' "$ACTUAL_ABIS") >/dev/null; then
  echo "   ❌ ABI mismatch — requested [$REACT_NATIVE_ARCHS], APK has:" >&2
  printf '%s\n' "$ACTUAL_ABIS" | sed 's/^/      /' >&2
  fail=1
else
  echo "   ✅ ABIs as requested: $(printf '%s' "$ACTUAL_ABIS" | tr '\n' ' ')"
fi

# 4. The APK must carry the production certificate. A credential typo or an
#    unreadable keystore degrades to a debug-signed APK rather than an error,
#    and that failure otherwise only surfaces at upload time.
SDK_DIR="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
if [[ -z "$SDK_DIR" && -f android/local.properties ]]; then
  SDK_DIR="$(sed -n 's/^sdk\.dir=//p' android/local.properties | tail -1)"
fi
APKSIGNER="$(command -v apksigner || true)"
if [[ -z "$APKSIGNER" && -n "$SDK_DIR" ]]; then
  APKSIGNER="$(ls -1 "$SDK_DIR"/build-tools/*/apksigner 2>/dev/null | sort -V | tail -1 || true)"
fi

if [[ -z "$APKSIGNER" ]]; then
  echo "   ❌ apksigner not found (PATH and ${SDK_DIR:-<no SDK dir>}/build-tools/*) — cannot prove how this APK is signed." >&2
  fail=1
else
  # The signer label differs by build-tools version ("Signer #1 certificate DN:"
  # through 36.x, "V2 Signer: certificate DN:" in 37.x), so match the label text
  # they share. Matching a version-specific prefix reports a correctly signed
  # APK as unsigned, which is how this check first failed.
  APKSIGNER_RC=0
  SIGNER_REPORT="$("$APKSIGNER" verify --print-certs "$APK" 2>&1)" || APKSIGNER_RC=$?
  SIGNER_DN="$(printf '%s\n' "$SIGNER_REPORT" | grep -m1 'certificate DN:' || true)"
  if [[ "$APKSIGNER_RC" -ne 0 || -z "$SIGNER_DN" ]]; then
    echo "   ❌ apksigner could not verify the APK's signature:" >&2
    printf '%s\n' "$SIGNER_REPORT" | sed 's/^/      /' >&2
    fail=1
  elif [[ "$SIGNER_DN" == *"CN=Android Debug"* ]]; then
    if [[ "${ALLOW_DEBUG_SIGNING:-0}" == "1" ]]; then
      echo "   ⚠️  DEBUG-signed (allowed by ALLOW_DEBUG_SIGNING=1) — not publishable."
    else
      echo "   ❌ DEBUG-signed: ${SIGNER_DN#*certificate DN: }" >&2
      echo "      Play rejects debug uploads, and this APK cannot upgrade an install signed" >&2
      echo "      with the production key. Check $RELEASE_SIGNING_PROPS." >&2
      fail=1
    fi
  else
    echo "   ✅ Signed with: ${SIGNER_DN#*certificate DN: }"
  fi
fi

if [[ "$fail" -ne 0 ]]; then
  echo "" >&2
  echo "❌ APK built but is MISCONFIGURED. Do not install it." >&2
  exit 1
fi

echo ""
echo "✅ Build complete and verified!"
echo "APK location:"
find android/app/build/outputs/apk -name "*.apk" -type f
