// ── Spotlight Realtor — Mock data ────────────────────────────────────────────
// Realistic NG inventory so loading/empty/filled states render in mock mode.
// All prices are integer minor units (kobo).

import type {
  Listing,
  AgentRef,
  InspectionBooking,
  RentalApplication,
  InspectionSlot,
} from '../types/realtor.types';

const IMG = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;

const AGENTS: AgentRef[] = [
  { id: 'ag_01', name: 'Adaeze Okafor', verified: true, rating: 4.8, reviewCount: 126, responseTime: '~20 min', avatarUrl: IMG('agent1') },
  { id: 'ag_02', name: 'Tunde Bakare', verified: true, rating: 4.6, reviewCount: 84, responseTime: '~1 hr', avatarUrl: IMG('agent2') },
  { id: 'ag_03', name: 'Kingsway Realty', verified: false, rating: 4.1, reviewCount: 19, responseTime: '~3 hr', avatarUrl: IMG('agent3') },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'ls_001',
    unitId: 'un_001',
    propertyId: 'pr_001',
    title: '3-Bedroom Serviced Apartment, Lekki Phase 1',
    mode: 'long_rent',
    propertyType: 'apartment',
    status: 'published',
    verification: 'verified',
    escrowProtected: true,
    price: 6_500_000_00,
    currency: 'NGN',
    rentSchedule: 'annual',
    cautionDeposit: 650_000_00,
    serviceCharge: 800_000_00,
    fees: [
      { label: 'Annual rent', amount: 6_500_000_00 },
      { label: 'Caution deposit (refundable)', amount: 650_000_00, refundable: true },
      { label: 'Service charge', amount: 800_000_00 },
      { label: 'Agency fee (10%)', amount: 650_000_00 },
    ],
    bedrooms: 3,
    bathrooms: 3,
    toilets: 4,
    sizeSqm: 145,
    furnishing: 'serviced',
    area: 'Lekki Phase 1',
    city: 'Lagos',
    state: 'Lagos',
    geo: { lat: 6.4474, lng: 3.4699 },
    amenities: ['security', 'power_backup', 'parking', 'air_conditioning', 'cctv', 'gated_estate', 'water', 'kitchen_fitted'],
    description:
      'Beautifully finished 3-bedroom serviced apartment in a secure, gated estate in the heart of Lekki Phase 1. Enjoy 24/7 power, treated water, fitted kitchen, and dedicated parking. Walking distance to schools, supermarkets and the waterfront.',
    media: [IMG('lekki1a'), IMG('lekki1b'), IMG('lekki1c'), IMG('lekki1d')],
    agent: AGENTS[0],
    inspectionRequired: true,
    applicationRequired: true,
    featured: true,
    createdAt: '2026-06-16T09:00:00Z',
    viewCount: 1240,
  },
  {
    id: 'ls_002',
    unitId: 'un_002',
    propertyId: 'pr_002',
    title: 'Mini Flat (1 Bed) Self-Contained, Yaba',
    mode: 'long_rent',
    propertyType: 'self_contain',
    status: 'published',
    verification: 'document_backed',
    escrowProtected: true,
    price: 1_200_000_00,
    currency: 'NGN',
    rentSchedule: 'annual',
    cautionDeposit: 100_000_00,
    fees: [
      { label: 'Annual rent', amount: 1_200_000_00 },
      { label: 'Caution deposit (refundable)', amount: 100_000_00, refundable: true },
      { label: 'Agency fee (10%)', amount: 120_000_00 },
    ],
    bedrooms: 1,
    bathrooms: 1,
    toilets: 1,
    sizeSqm: 42,
    furnishing: 'unfurnished',
    area: 'Yaba',
    city: 'Lagos',
    state: 'Lagos',
    geo: { lat: 6.5095, lng: 3.3711 },
    amenities: ['security', 'water', 'parking', 'power_backup'],
    description:
      'Compact, well-maintained self-contained apartment close to UNILAG and the Yaba tech cluster. Prepaid meter, steady water supply, and gated compound. Ideal for a young professional or student.',
    media: [IMG('yaba1a'), IMG('yaba1b'), IMG('yaba1c')],
    agent: AGENTS[1],
    inspectionRequired: true,
    applicationRequired: true,
    priceDropFrom: 1_350_000_00,
    createdAt: '2026-06-18T14:30:00Z',
    viewCount: 530,
  },
  {
    id: 'ls_003',
    unitId: 'un_003',
    propertyId: 'pr_003',
    title: '4-Bedroom Detached Duplex with BQ, Maitama',
    mode: 'for_sale',
    propertyType: 'duplex',
    status: 'published',
    verification: 'verified',
    escrowProtected: true,
    price: 320_000_000_00,
    currency: 'NGN',
    fees: [
      { label: 'Purchase price', amount: 320_000_000_00 },
      { label: 'Legal & documentation (5%)', amount: 16_000_000_00 },
    ],
    bedrooms: 4,
    bathrooms: 5,
    toilets: 5,
    sizeSqm: 480,
    furnishing: 'unfurnished',
    area: 'Maitama',
    city: 'Abuja',
    state: 'FCT',
    geo: { lat: 9.0875, lng: 7.4983 },
    amenities: ['security', 'power_backup', 'parking', 'cctv', 'gated_estate', 'borehole', 'pool'],
    description:
      'Premium 4-bedroom fully detached duplex with a boys quarters on a 480sqm plot in Maitama. C of O title, ample parking, private pool, and round-the-clock estate security. A rare buy in one of Abuja\'s most prestigious districts.',
    media: [IMG('maitama1a'), IMG('maitama1b'), IMG('maitama1c'), IMG('maitama1d')],
    agent: AGENTS[0],
    inspectionRequired: true,
    applicationRequired: false,
    featured: true,
    createdAt: '2026-06-12T08:00:00Z',
    viewCount: 2110,
  },
  {
    id: 'ls_004',
    unitId: 'un_004',
    propertyId: 'pr_004',
    title: 'Luxury 2-Bed Shortlet, Victoria Island',
    mode: 'short_stay',
    propertyType: 'apartment',
    status: 'published',
    verification: 'inspected',
    escrowProtected: true,
    price: 0,
    nightlyPrice: 85_000_00,
    currency: 'NGN',
    cautionDeposit: 150_000_00,
    fees: [
      { label: 'Nightly rate', amount: 85_000_00 },
      { label: 'Cleaning fee', amount: 25_000_00 },
      { label: 'Security deposit (refundable)', amount: 150_000_00, refundable: true },
    ],
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    sizeSqm: 98,
    furnishing: 'furnished',
    area: 'Victoria Island',
    city: 'Lagos',
    state: 'Lagos',
    geo: { lat: 6.4281, lng: 3.4219 },
    amenities: ['security', 'power_backup', 'wifi', 'air_conditioning', 'pool', 'gym', 'cctv', 'elevator'],
    description:
      'Stylish, fully furnished 2-bedroom apartment on Victoria Island — perfect for business travellers and weekend stays. 24/7 power, fast Wi-Fi, rooftop pool and gym. Self check-in with secure access code.',
    media: [IMG('vi1a'), IMG('vi1b'), IMG('vi1c')],
    agent: AGENTS[1],
    inspectionRequired: false,
    applicationRequired: false,
    createdAt: '2026-06-19T10:00:00Z',
    viewCount: 870,
  },
  {
    id: 'ls_005',
    unitId: 'un_005',
    propertyId: 'pr_005',
    title: '2-Bedroom Flat, Gbagada Phase 2',
    mode: 'long_rent',
    propertyType: 'flat',
    status: 'published',
    verification: 'unverified',
    escrowProtected: false,
    price: 1_800_000_00,
    currency: 'NGN',
    rentSchedule: 'annual',
    cautionDeposit: 150_000_00,
    fees: [
      { label: 'Annual rent', amount: 1_800_000_00 },
      { label: 'Caution deposit (refundable)', amount: 150_000_00, refundable: true },
      { label: 'Agency fee (10%)', amount: 180_000_00 },
    ],
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    sizeSqm: 78,
    furnishing: 'unfurnished',
    area: 'Gbagada',
    city: 'Lagos',
    state: 'Lagos',
    geo: { lat: 6.5483, lng: 3.3897 },
    amenities: ['parking', 'water', 'security'],
    description:
      'Spacious 2-bedroom flat in a quiet residential area of Gbagada Phase 2. Close to the Third Mainland Bridge for an easy commute to the Island. Tiled floors, en-suite master, and secure compound.',
    media: [IMG('gbagada1a'), IMG('gbagada1b')],
    agent: AGENTS[2],
    inspectionRequired: true,
    applicationRequired: true,
    createdAt: '2026-06-17T16:45:00Z',
    viewCount: 320,
  },
  {
    id: 'ls_006',
    unitId: 'un_006',
    propertyId: 'pr_006',
    title: 'Open-Plan Office Space, Ikeja GRA',
    mode: 'for_lease',
    propertyType: 'office',
    status: 'published',
    verification: 'document_backed',
    escrowProtected: true,
    price: 4_500_000_00,
    currency: 'NGN',
    rentSchedule: 'annual',
    serviceCharge: 600_000_00,
    fees: [
      { label: 'Annual lease', amount: 4_500_000_00 },
      { label: 'Service charge', amount: 600_000_00 },
      { label: 'Agency fee (10%)', amount: 450_000_00 },
    ],
    bedrooms: 0,
    bathrooms: 2,
    toilets: 2,
    sizeSqm: 160,
    furnishing: 'unfurnished',
    area: 'Ikeja GRA',
    city: 'Lagos',
    state: 'Lagos',
    geo: { lat: 6.5818, lng: 3.3515 },
    amenities: ['security', 'power_backup', 'parking', 'air_conditioning', 'elevator', 'cctv'],
    description:
      'Bright, open-plan office on the second floor of a serviced commercial building in Ikeja GRA. Dedicated parking, backup power, lift access and on-site security. Move-in ready for a growing team.',
    media: [IMG('ikeja1a'), IMG('ikeja1b'), IMG('ikeja1c')],
    agent: AGENTS[0],
    inspectionRequired: true,
    applicationRequired: true,
    createdAt: '2026-06-15T11:20:00Z',
    viewCount: 410,
  },
];

export const MOCK_POPULAR_AREAS = [
  { area: 'Lekki Phase 1', city: 'Lagos', listingCount: 184 },
  { area: 'Yaba', city: 'Lagos', listingCount: 96 },
  { area: 'Maitama', city: 'Abuja', listingCount: 72 },
  { area: 'Victoria Island', city: 'Lagos', listingCount: 153 },
  { area: 'Ikeja GRA', city: 'Lagos', listingCount: 64 },
];

/** Generate the next N days of slots (09:00–17:00) for a listing. */
export function buildSlots(days = 7): InspectionSlot[] {
  const times = ['09:00', '11:00', '13:00', '15:00', '17:00'];
  const out: InspectionSlot[] = [];
  const today = new Date();
  for (let d = 1; d <= days; d++) {
    const date = new Date(today);
    date.setDate(today.getDate() + d);
    const iso = date.toISOString().slice(0, 10);
    times.forEach((t, i) => {
      out.push({
        id: `${iso}_${t}`,
        date: iso,
        time: t,
        // Pseudo-random unavailability so the picker shows blocked slots.
        available: !((d + i) % 4 === 0),
      });
    });
  }
  return out;
}

// In-memory funnel stores (reset on reload — fine for mock mode).
export const MOCK_INSPECTIONS: InspectionBooking[] = [
  {
    id: 'in_seed1',
    listingId: 'ls_001',
    listingTitle: '3-Bedroom Serviced Apartment, Lekki Phase 1',
    listingCoverUrl: IMG('lekki1a'),
    area: 'Lekki Phase 1',
    city: 'Lagos',
    address: 'Block 4, Admiralty Way, Lekki Phase 1',
    geo: { lat: 6.4474, lng: 3.4699 },
    status: 'confirmed',
    viewingMode: 'physical',
    date: new Date(Date.now() + 2 * 86_400_000).toISOString().slice(0, 10),
    time: '11:00',
    attendeeName: 'Demo User',
    attendeePhone: '0803 000 0000',
    agent: AGENTS[0],
    canConvertToApplication: false,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_APPLICATIONS: RentalApplication[] = [
  {
    id: 'ap_seed1',
    listingId: 'ls_001',
    listingTitle: '3-Bedroom Serviced Apartment, Lekki Phase 1',
    listingCoverUrl: IMG('lekki1a'),
    area: 'Lekki Phase 1',
    city: 'Lagos',
    status: 'approved',
    rentSchedule: 'annual',
    rent: 6_500_000_00,
    cautionDeposit: 650_000_00,
    applicant: { fullName: 'Demo User', email: 'demo@spotlight.ng', phone: '0803 000 0000' },
    monthlyIncome: 1_200_000_00,
    documents: [
      { id: 'doc_id', label: 'Government ID', uploaded: true, required: true },
      { id: 'doc_pay', label: 'Proof of income / payslip', uploaded: true, required: true },
      { id: 'doc_bank', label: 'Bank statement (3 months)', uploaded: true, required: true },
    ],
    timeline: [
      { key: 'submitted', label: 'Application submitted', state: 'done' },
      { key: 'under_review', label: 'Screening & review', state: 'done' },
      { key: 'approved', label: 'Approved — lease offer ready', state: 'current' },
      { key: 'lease', label: 'Lease & e-sign', state: 'upcoming' },
      { key: 'payment', label: 'Rent & deposit payment', state: 'upcoming' },
      { key: 'move_in', label: 'Move-in', state: 'upcoming' },
    ],
    createdAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    agent: AGENTS[0],
  },
];
