package referrals

import "time"

// ============================================================================
// Direct Referral Rewards ENGINE — types.
//
// Single-level, purchase-triggered revenue share (no network depth). This file
// carries the NEW engine's models; the legacy Code/Event/Summary types in
// model.go are left intact (brownfield additive rule). Money is always integer
// minor units (kobo): the PRD writes ₦, everything here is ×100.
// ============================================================================

// Reward status state machine (§4.1).
const (
	RewardStatusPending  = "PENDING"
	RewardStatusCredited = "CREDITED"
	RewardStatusReversed = "REVERSED"
)

// Tier names (§2.2).
const (
	TierStarter = "STARTER"
	TierGrowth  = "GROWTH"
	TierPro     = "PRO"
	TierElite   = "ELITE"
)

// Milestone status state machine (§4.2).
const (
	MilestoneStatusAchieved = "ACHIEVED"
	MilestoneStatusPaid     = "PAID"
	MilestoneStatusVoided   = "VOIDED"
)

// ActiveWindowDays is the trailing window used to classify a referred user as
// "active" (§2.2: at least one qualifying purchase in the last 30 days).
const ActiveWindowDays = 30

// ---------------------------------------------------------------------------
// EMIT HOOK CONTRACT — the integration agent builds against these two structs.
// Every revenue-bearing module emits PurchaseSettled on a settled purchase and
// PurchaseRefunded on a refund/chargeback (§7.1).
// ---------------------------------------------------------------------------

// PurchaseSettled is the common event every revenue-bearing module emits into
// the engine when a referred user completes a settled purchase. MarginKobo is
// the platform margin on that purchase in kobo (integer minor units).
type PurchaseSettled struct {
	Module        string    `json:"module"`         // e.g. "bills", "marketplace", "insurance"
	TransactionID string    `json:"transaction_id"` // idempotency anchor — one reward per txn, ever
	PayerUserID   string    `json:"payer_user_id"`  // the referred user who paid
	MarginKobo    int64     `json:"margin_kobo"`    // platform margin in kobo (integer minor units)
	Currency      string    `json:"currency"`       // ISO code, e.g. "NGN"
	SettledAt     time.Time `json:"settled_at"`
}

// PurchaseRefunded reverses the reward generated by a previously-settled
// purchase (§2.4). TransactionID must match a prior PurchaseSettled.
type PurchaseRefunded struct {
	TransactionID string    `json:"transaction_id"`
	RefundedAt    time.Time `json:"refunded_at"`
}

// ---------------------------------------------------------------------------
// Persisted rows.
// ---------------------------------------------------------------------------

// Link is a referrer's canonical referral code (referral_links).
type Link struct {
	ID         string    `json:"id"`
	ReferrerID string    `json:"referrer_id"`
	Code       string    `json:"code"`
	CreatedAt  time.Time `json:"created_at"`
}

// Reward is one per-purchase ongoing-share accrual (referral_rewards).
type Reward struct {
	ID                  string     `json:"id"`
	ReferrerID          string     `json:"referrer_id"`
	ReferredUserID      string     `json:"referred_user_id"`
	SourceTransactionID string     `json:"source_transaction_id"`
	Module              string     `json:"module"`
	MarginKobo          int64      `json:"margin_kobo"`
	AppliedRate         float64    `json:"applied_rate"`
	RewardKobo          int64      `json:"reward_kobo"`
	Status              string     `json:"status"`
	ConfigVersion       int        `json:"config_version"`
	CreatedAt           time.Time  `json:"created_at"`
	CreditedAt          *time.Time `json:"credited_at,omitempty"`
	ReversedAt          *time.Time `json:"reversed_at,omitempty"`
}

// TierStatus is a referrer's rolling tier snapshot (referral_tier_status).
type TierStatus struct {
	ReferrerID          string    `json:"referrer_id"`
	ActiveReferralCount int       `json:"active_referral_count"`
	CurrentTier         string    `json:"current_tier"`
	CurrentRate         float64   `json:"current_rate"`
	LastRecalculatedAt  time.Time `json:"last_recalculated_at"`
}

// Milestone is a one-time count-threshold bonus (referral_milestones).
type Milestone struct {
	ID         string     `json:"id"`
	ReferrerID string     `json:"referrer_id"`
	Threshold  int        `json:"threshold"`
	BonusKobo  int64      `json:"bonus_kobo"`
	Status     string     `json:"status"`
	AchievedAt time.Time  `json:"achieved_at"`
	PaidAt     *time.Time `json:"paid_at,omitempty"`
	VoidedAt   *time.Time `json:"voided_at,omitempty"`
}

// ---------------------------------------------------------------------------
// Program config (referral_program_config).
// ---------------------------------------------------------------------------

// TierBand is one row of the versioned tier table. MaxCount == nil means
// open-ended (the top tier). Rate is a fraction (0.05 = 5%).
type TierBand struct {
	Tier     string  `json:"tier"`
	MinCount int     `json:"min_count"`
	MaxCount *int    `json:"max_count"`
	Rate     float64 `json:"rate"`
}

// MilestoneBand is one row of the versioned milestone table.
type MilestoneBand struct {
	Threshold int   `json:"threshold"`
	BonusKobo int64 `json:"bonus_kobo"`
}

// ProgramConfig is one versioned config row. The engine reads the active version
// whose EffectiveFrom <= now(); new versions apply from EffectiveFrom forward and
// never retroactively recompute past rewards (§3 invariant).
type ProgramConfig struct {
	ID             string          `json:"id"`
	Version        int             `json:"version"`
	TierTable      []TierBand      `json:"tier_table"`
	MilestoneTable []MilestoneBand `json:"milestone_table"`
	IsActive       bool            `json:"is_active"`
	EffectiveFrom  time.Time       `json:"effective_from"`
	CreatedAt      time.Time       `json:"created_at"`
}

// TierForCount returns the tier band whose [min,max] range contains count.
// Returns (band, true) on a match; (zero, false) when count is below the lowest
// band (i.e. 0 active referrals → no tier / rate 0).
func (c ProgramConfig) TierForCount(count int) (TierBand, bool) {
	for _, b := range c.TierTable {
		if count < b.MinCount {
			continue
		}
		if b.MaxCount == nil || count <= *b.MaxCount {
			return b, true
		}
	}
	return TierBand{}, false
}

// ComputeReward returns floor(marginKobo * rate) in kobo. Integer math on the
// kobo amount — no floats in the persisted value. rate is a fraction (0.05).
func ComputeReward(marginKobo int64, rate float64) int64 {
	if marginKobo <= 0 || rate <= 0 {
		return 0
	}
	// marginKobo is an exact integer; multiplying by a fractional rate and
	// flooring yields the reward in kobo. We never store a float amount.
	return int64(float64(marginKobo) * rate)
}

// ---------------------------------------------------------------------------
// API response shapes (snake_case to match the existing referrals handler).
// ---------------------------------------------------------------------------

// Dashboard is the response for GET /v1/referrals/me/dashboard.
type Dashboard struct {
	Code               string         `json:"code"`
	CurrentTier        string         `json:"current_tier"`
	CurrentRate        float64        `json:"current_rate"`
	ActiveReferralCount int           `json:"active_referral_count"`
	ThisMonthEarnedKobo int64         `json:"this_month_earned_kobo"`
	LifetimeEarnedKobo  int64         `json:"lifetime_earned_kobo"`
	NextMilestone      *NextMilestone `json:"next_milestone,omitempty"`
}

// NextMilestone previews the upcoming count-threshold bonus.
type NextMilestone struct {
	Threshold int   `json:"threshold"`
	BonusKobo int64 `json:"bonus_kobo"`
	Remaining int   `json:"remaining"`
}

// ReferredUser is a row in GET /v1/referrals/me/referrals. Contact is masked.
type ReferredUser struct {
	ReferredUserID    string    `json:"referred_user_id"`
	MaskedContact     string    `json:"masked_contact"`
	JoinedAt          time.Time `json:"joined_at"`
	Active            bool      `json:"active"` // qualifying purchase in trailing 30d
	LifetimeEarnedKobo int64    `json:"lifetime_earned_kobo"`
}
