-- 20260922002000_naija_driver_frsc_supplement.sql
-- ADDITIVE ONLY. Supplements the Naija Driver safe-driving assessment bank with
-- fresh, original MCQs grounded in FACTS from the FRSC DRC Compendium 2023
-- (road-sign meanings, traffic rules, speed-limit concepts, documents, FRSC
-- procedures, emergency/first-aid, vehicle control/condition). No text is copied
-- verbatim from the compendium; every prompt, option and explanation is original.
-- Same bank_key + rubric_version + template shape as 20260921000000. New external
-- ids continue the ND-S{stage}-Q{n} series (S1 from Q31, S2 from Q31, S3 from Q31).
-- Idempotent: ON CONFLICT (bank_key, rubric_version, external_id) [template] DO NOTHING.
-- image_url '' + trailing "-- SIGN:" comment marks rows that should get an
-- illustration attached later; non-visual rows carry image_url ''.
-- No DROP / RENAME / type-narrowing. Safe to re-run.

BEGIN;

INSERT INTO arena_quiz_question
  (competition_id, bank_key, rubric_version, external_id, stage, category, prompt, options, correct_index, correct_answer, explanation, time_limit_seconds, pass_mark_percent, image_url)
VALUES
-- ── STAGE 1 · Foundation (pass 70): road_signs, traffic_rules, documentation ──
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q31', 1, 'road_signs', 'A blue circular sign showing a white arrow that points left is telling you to:', '["Beware of a bend to the left", "Turn left here — it is a compulsory instruction", "No left turn is allowed", "There is a car park to the left"]'::jsonb, 1, 'Turn left here — it is a compulsory instruction', 'Blue circular signs give positive, compulsory instructions you must obey, unlike red-bordered signs that forbid.', 120, 70, 'sign:turn-left'), -- SIGN: 'Turn Left (mandatory)' (blue circle, white left arrow)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q32', 1, 'road_signs', 'A round sign with a red background crossed by one thick white horizontal bar means:', '["No entry for vehicles", "One-way street ahead", "Parking area", "End of all restrictions"]'::jsonb, 0, 'No entry for vehicles', 'This prohibitory sign bars you from entering; passing it means driving against the permitted flow.', 120, 70, 'sign:no-entry'), -- SIGN: 'No Entry' (red disc, white horizontal bar)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q33', 1, 'road_signs', 'A red-bordered white circle showing two cars side by side (one red, one dark) tells you that:', '["Overtaking is not allowed on this stretch", "Two lanes merge ahead", "A car park is nearby", "Convoys have priority"]'::jsonb, 0, 'Overtaking is not allowed on this stretch', 'Overtaking is prohibited here because of limited sight or a hazard; wait for a clearer, legal stretch.', 120, 70, 'sign:no-overtaking'), -- SIGN: 'No Overtaking' (red circle, two cars)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q34', 1, 'road_signs', 'A red-bordered circle containing a U-shaped arrow with a line struck through it means:', '["U-turns are prohibited here", "U-turns are recommended", "Sharp bend ahead", "Roundabout ahead"]'::jsonb, 0, 'U-turns are prohibited here', 'Making a U-turn where it is barred endangers oncoming traffic and is a bookable offence.', 120, 70, 'sign:no-u-turn'), -- SIGN: 'No U-Turn' (red circle, crossed U-arrow)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q35', 1, 'road_signs', 'A blue circle bordered in red with a single red diagonal line across it means:', '["No waiting at this point", "Free parking", "Bus stop", "Loading bay"]'::jsonb, 0, 'No waiting at this point', 'No-waiting signs keep the road clear; stopping here obstructs the flow of traffic.', 120, 70, 'sign:no-waiting'), -- SIGN: 'No Waiting' (blue circle, red border, one red diagonal)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q36', 1, 'road_signs', 'A white circle with a red border displaying the number 50 means:', '["Minimum speed of 50 km/h", "Maximum speed of 50 km/h", "50 km to the next town", "Route number 50"]'::jsonb, 1, 'Maximum speed of 50 km/h', 'Red-bordered number circles set the maximum legal speed; exceeding it is speeding even if the road feels clear.', 120, 70, 'sign:speed-limit-50'), -- SIGN: 'Speed Limit 50' (white circle, red border, number 50)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q37', 1, 'road_signs', 'A downward-pointing (inverted) triangle with a red border at a junction instructs you to:', '["Stop completely every time", "Give way to traffic on the major road", "Speed up to merge", "Sound your horn and proceed"]'::jsonb, 1, 'Give way to traffic on the major road', 'Give way means yield to traffic already on the priority road; you only stop if there is something to give way to.', 120, 70, 'sign:give-way'), -- SIGN: 'Give Way' (inverted red-bordered triangle)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q38', 1, 'road_signs', 'A triangular warning sign showing three curved arrows chasing each other in a circle warns that:', '["A roundabout is ahead", "A car wash is ahead", "A whirlpool crossing", "No entry ahead"]'::jsonb, 0, 'A roundabout is ahead', 'Slow down and prepare to give way to traffic already on the roundabout, usually approaching from your right.', 120, 70, 'sign:roundabout-ahead'), -- SIGN: 'Roundabout Ahead' (triangle, three circular arrows)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q39', 1, 'road_signs', 'A triangular sign showing a car with two wavy skid lines behind its wheels warns of:', '["A slippery road surface ahead", "A car wash", "A river crossing", "A racing track"]'::jsonb, 0, 'A slippery road surface ahead', 'Ease off the accelerator and avoid harsh braking or steering where the surface may be slippery.', 120, 70, 'sign:slippery-road'), -- SIGN: 'Slippery Road' (triangle, car with skid marks)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q40', 1, 'road_signs', 'A triangular warning sign showing a figure walking on stripes alerts you to:', '["A pedestrian crossing ahead", "A tailoring shop", "A school gate only", "A parking zone"]'::jsonb, 0, 'A pedestrian crossing ahead', 'Reduce speed and be ready to stop for people using the crossing ahead.', 120, 70, 'sign:pedestrian-crossing'), -- SIGN: 'Pedestrian Crossing Ahead' (triangle, person on stripes)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q41', 1, 'road_signs', 'A triangular sign showing two children walking together usually warns that:', '["A children''s park is closed", "You are near a school or children''s area — drive with care", "Only children may cross here", "Children ride free of charge"]'::jsonb, 1, 'You are near a school or children''s area — drive with care', 'Expect sudden movements from children near schools; slow right down and watch the roadside.', 120, 70, 'sign:children-crossing'), -- SIGN: 'Children / School Ahead' (triangle, two children)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q42', 1, 'road_signs', 'A triangular sign whose inner lines lean inward toward the top (narrowing) warns that:', '["The road widens ahead", "The road narrows ahead", "A bridge is closed", "Two roads merge into a roundabout"]'::jsonb, 1, 'The road narrows ahead', 'Where the carriageway narrows, adjust your position and speed and give way as space allows.', 120, 70, 'sign:road-narrows-both'), -- SIGN: 'Road Narrows' (triangle, inward-leaning lines)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q43', 1, 'road_signs', 'A triangular sign showing a vehicle on a steep slope with a percentage figure warns of:', '["A steep hill or descent ahead", "A ski resort", "A speed bump", "A bridge toll"]'::jsonb, 0, 'A steep hill or descent ahead', 'Select a lower gear early so engine braking helps you control speed down the slope.', 120, 70, 'sign:steep-hill-downwards'), -- SIGN: 'Steep Descent/Hill' (triangle, vehicle on gradient with %)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q44', 1, 'road_signs', 'A triangular sign showing two vertical arrows pointing in opposite directions warns of:', '["A one-way street", "Two-way traffic ahead", "A pedestrian bridge", "A lay-by ahead"]'::jsonb, 1, 'Two-way traffic ahead', 'Traffic will be coming toward you again; keep to your side and do not overtake unless it is clearly safe.', 120, 70, 'sign:two-way-traffic'), -- SIGN: 'Two-Way Traffic' (triangle, two opposite vertical arrows)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q45', 1, 'road_signs', 'A triangular warning sign showing a gate or barrier symbol usually warns of:', '["A level (railway) crossing ahead", "A farm entrance", "A prison gate", "A hotel gate"]'::jsonb, 0, 'A level (railway) crossing ahead', 'Approach a railway crossing ready to stop; never cross while a train is coming or the barriers are down.', 120, 70, 'sign:level-crossing-with-gate'), -- SIGN: 'Level Crossing with Gate' (triangle, gate/barrier symbol)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q46', 1, 'road_signs', 'Diagonal white ''hatched'' markings in the middle of the road bounded by broken lines mean you should:', '["Park within the striped area", "Keep out of the striped area unless it is safe to enter", "Overtake only within the stripes", "Use it as a bus lane"]'::jsonb, 1, 'Keep out of the striped area unless it is safe to enter', 'Hatched markings separate opposing streams or protect turning vehicles; enter only when it is clearly safe.', 120, 70, 'sign:hatched-marking'), -- SIGN: 'Hatched Road Marking' (diagonal white lines within broken lines)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q47', 1, 'road_signs', 'A continuous (unbroken) white line along the centre of the road tells you that:', '["You may cross it to overtake at any time", "You must not cross or straddle it except in an emergency", "It marks a cycle lane", "It shows where to park"]'::jsonb, 1, 'You must not cross or straddle it except in an emergency', 'A solid centre line forbids crossing except to avoid a hazard; a broken line is what permits overtaking when safe.', 120, 70, 'sign:continuous-centre-line'), -- SIGN: 'Continuous White Centre Line' (solid road-centre marking)
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q48', 1, 'road_signs', 'Nigerian road signs are grouped into three main families. Which set names them correctly?', '["Warning, regulatory and informative signs", "Big, medium and small signs", "Painted, printed and carved signs", "City, town and village signs"]'::jsonb, 0, 'Warning, regulatory and informative signs', 'Every sign is a warning (hazard), a regulatory (order) or an informative (guidance) sign, read by its shape and colour.', 120, 70, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q49', 1, 'road_signs', 'Prohibitory signs, which give negative ''do not'' instructions, are generally:', '["Rectangular and green", "Circular in shape", "Star-shaped", "Diamond and pink"]'::jsonb, 1, 'Circular in shape', 'Prohibitory signs are circular; the octagonal STOP and the blue No-Waiting/No-Stopping signs are the special exceptions.', 120, 70, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q50', 1, 'traffic_rules', 'When a traffic light shows red and amber together, you should:', '["Go immediately", "Wait — do not move off until the green light shows", "Turn left only", "Reverse to the stop line"]'::jsonb, 1, 'Wait — do not move off until the green light shows', 'Red-and-amber together still means stop; it only warns that green is about to appear.', 120, 70, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q51', 1, 'traffic_rules', 'A lit green arrow shown beside the main traffic signal means you may:', '["Ignore the other lights and go anywhere", "Move only in the direction the arrow points, if the way is clear", "Park under the light", "Demand right of way with your horn"]'::jsonb, 1, 'Move only in the direction the arrow points, if the way is clear', 'A filter arrow lets you proceed only in the direction shown, regardless of the other signals.', 120, 70, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q52', 1, 'documentation', 'A visitor keeping a foreign-registered vehicle in Nigeria is expected to change to a Nigerian number plate within about:', '["24 hours of arrival", "90 days of arrival", "5 years", "There is no need to change it"]'::jsonb, 1, '90 days of arrival', 'Long-stay visitors must regularise the vehicle, including switching to a Nigerian plate, within roughly ninety days.', 120, 70, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q53', 1, 'documentation', 'To drive legally as a foreign visitor in Nigeria, alongside a valid licence from your own country you should carry:', '["Only a passport photograph", "An International Driving Permit", "A hotel booking receipt", "A return air ticket"]'::jsonb, 1, 'An International Driving Permit', 'An International Driving Permit together with your national licence proves your entitlement to drive here.', 120, 70, ''),
-- ── STAGE 2 · Intermediate (pass 75): safe_practice, speed_limits, night_weather, frsc_regulations ──
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q31', 2, 'safe_practice', 'Before overtaking a slow vehicle that will not pull over, a careful driver first checks that overtaking is:', '["Fast, loud and fun", "Legal, safe and necessary", "Cheap, quick and quiet", "Uphill, downhill or flat"]'::jsonb, 1, 'Legal, safe and necessary', 'If overtaking is not legal, safe and necessary, stay back — impatience causes head-on crashes.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q32', 2, 'safe_practice', 'When following a large truck or tanker, you should keep well back mainly because:', '["Their exhaust smells", "A bigger gap improves your view ahead and your room to stop", "It is simply polite", "Trucks dislike being followed"]'::jsonb, 1, 'A bigger gap improves your view ahead and your room to stop', 'Hanging back widens your field of view past the vehicle and gives more time to react to hazards.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q33', 2, 'safe_practice', 'Even when driving in an official convoy, drivers are expected to:', '["Chase other road users off the road", "Obey normal traffic rules and avoid tailgating", "Ignore all speed limits", "Drive bumper to bumper"]'::jsonb, 1, 'Obey normal traffic rules and avoid tailgating', 'Convoys enjoy no exemption from road rules; safe spacing and courtesy to others still apply.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q34', 2, 'safe_practice', 'A herd of cattle strays onto the highway ahead of you. The safest response is to:', '["Swerve into the oncoming lane at once", "Slow down and be ready to stop, checking that traffic behind can also stop", "Speed through the gap", "Sound the horn and keep full speed"]'::jsonb, 1, 'Slow down and be ready to stop, checking that traffic behind can also stop', 'Sudden swerving invites a worse crash; ease down early and make sure following traffic can react too.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q35', 2, 'speed_limits', 'A posted speed limit represents:', '["A target you must always reach", "The maximum a vehicle may travel under ideal conditions", "The speed to use only in fog", "A suggestion you can ignore in traffic"]'::jsonb, 1, 'The maximum a vehicle may travel under ideal conditions', 'Limits are ceilings for good conditions; poor weather or heavy traffic means driving well below them.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q36', 2, 'speed_limits', 'When leaving an open highway and entering a built-up town, you should:', '["Keep your highway speed", "Reduce speed to suit the lower built-up limit and heavier activity", "Speed up to clear the town quickly", "Slow only if you see an officer"]'::jsonb, 1, 'Reduce speed to suit the lower built-up limit and heavier activity', 'Towns bring pedestrians, junctions and cyclists; drop to the lower posted limit even when the road looks clear.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q37', 2, 'speed_limits', 'FRSC requires speed limiting devices to be fitted mainly on:', '["Bicycles", "Commercial vehicles such as buses, trucks and tankers", "Private saloon cars only", "Motorcycles only"]'::jsonb, 1, 'Commercial vehicles such as buses, trucks and tankers', 'Speed limiters cap the top speed of heavy commercial vehicles, a major factor in fatal highway crashes.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q38', 2, 'speed_limits', 'Driving at exactly the posted limit during heavy rain is:', '["Always correct because it is legal", "Often too fast, because the limit assumes ideal conditions", "Required by law in rain", "Only risky at night"]'::jsonb, 1, 'Often too fast, because the limit assumes ideal conditions', 'The limit is a maximum for good conditions; wet, slippery roads demand a slower, safer speed.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q39', 2, 'night_weather', 'When another vehicle approaches at night with headlights on, you should:', '["Keep full beam to see better", "Dip (lower) your headlights to avoid dazzling the other driver", "Flash your lights repeatedly", "Switch your lights off"]'::jsonb, 1, 'Dip (lower) your headlights to avoid dazzling the other driver', 'Dipping your beams for oncoming and leading vehicles prevents dazzle that can blind them momentarily.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q40', 2, 'night_weather', 'In thick fog or smoke, the recommended lighting and behaviour is:', '["Full main beam", "Low-beam headlights, slower speed and hazard lights if needed", "No lights, to reduce glare", "Interior lights only"]'::jsonb, 1, 'Low-beam headlights, slower speed and hazard lights if needed', 'Main beam reflects off fog and dazzles you; low beam plus low speed keeps you visible and in control.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q41', 2, 'night_weather', 'On a wet, slippery road your stopping distance compared with a dry road can be:', '["Shorter", "Several times longer", "Exactly the same", "Reduced to zero"]'::jsonb, 1, 'Several times longer', 'Reduced tyre grip in the rain can multiply stopping distance, so leave a much larger following gap.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q42', 2, 'night_weather', 'Blinding sun glare at sunrise or sunset is best managed by:', '["Closing your eyes briefly", "Using the sun visor or sunglasses and slowing down", "Speeding up to pass through it", "Staring straight into the sun"]'::jsonb, 1, 'Using the sun visor or sunglasses and slowing down', 'A visor or sunglasses cuts the glare, and a lower speed buys time to react to what you cannot yet see.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q43', 2, 'frsc_regulations', 'During an FRSC vehicle check, the reflective warning triangles a vehicle must carry should be:', '["A single small triangle", "A pair of triangles kept in the vehicle", "Optional decorations", "Needed only by trucks"]'::jsonb, 1, 'A pair of triangles kept in the vehicle', 'A pair of reflective triangles warns approaching traffic when you break down, protecting you and others.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q44', 2, 'frsc_regulations', 'When an FRSC marshal books a driver for an offence, correct procedure is to:', '["Seize the vehicle keys immediately", "Explain the offence and issue the driver a copy of the Notice of Offence", "Remove the number plate by force", "Refuse to answer the driver''s questions"]'::jsonb, 1, 'Explain the offence and issue the driver a copy of the Notice of Offence', 'The offender is told the offence and given the original Notice of Offence; forceful seizure of vehicle parts is not allowed.', 120, 75, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q45', 2, 'frsc_regulations', 'Which pair are recognised traffic offences enforced by the FRSC?', '["Playing music and eating snacks", "Using a phone while driving and failing to wear a seat belt", "Driving a clean car and waving", "Parking at home and washing a car"]'::jsonb, 1, 'Using a phone while driving and failing to wear a seat belt', 'Using a phone while driving and seat-belt violations are booked offences because both sharply raise crash risk.', 120, 75, ''),
-- ── STAGE 3 · Advanced (pass 80): hazard_perception, emergency_response, vehicle_control, vehicle_condition ──
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q31', 3, 'hazard_perception', 'Defensive driving is best described as:', '["Driving as fast as the car allows", "Scanning for, predicting and avoiding hazards before they develop", "Only braking when a crash is unavoidable", "Relying on other drivers to keep you safe"]'::jsonb, 1, 'Scanning for, predicting and avoiding hazards before they develop', 'A defensive driver reads the road ahead and plans an escape rather than reacting at the last moment.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q32', 3, 'hazard_perception', 'As you near the crest of a hill where you cannot see the road beyond, you should:', '["Overtake quickly while you have room", "Slow down and keep to your side, since a hazard may be hidden", "Move to the centre for a better view", "Accelerate to get over faster"]'::jsonb, 1, 'Slow down and keep to your side, since a hazard may be hidden', 'You cannot judge oncoming traffic over a blind crest, so approach ready for the unseen.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q33', 3, 'hazard_perception', 'On a blind bend screened by bushes, the safest policy is to:', '["Assume the road ahead is clear", "Slow down and expect a possible hazard just out of sight", "Overtake before the bend ends", "Cut the corner to straighten the bend"]'::jsonb, 1, 'Slow down and expect a possible hazard just out of sight', 'Vision is blocked on blind turns; a lower speed lets you stop within the distance you can actually see.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q34', 3, 'hazard_perception', 'A taxi ahead stops suddenly to pick up a passenger. The biggest hidden danger is:', '["The taxi''s colour", "A pedestrian stepping out from in front of or behind the taxi", "Your radio volume", "The taxi''s number plate"]'::jsonb, 1, 'A pedestrian stepping out from in front of or behind the taxi', 'Stopped taxis and buses often hide people crossing; ease off and be ready to stop.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q35', 3, 'hazard_perception', 'Regularly checking your mirrors before slowing, turning or changing lane helps you to:', '["Admire your reflection", "Know what is behind and beside you so you can act safely", "Save fuel", "Increase your speed"]'::jsonb, 1, 'Know what is behind and beside you so you can act safely', 'Knowing the position of following and overtaking traffic lets you plan moves without surprising anyone.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q36', 3, 'emergency_response', 'In roadside first aid, the letters A-B-C stand for the priorities:', '["Ask, Bandage, Carry", "Airway, Breathing, Circulation", "Alert, Brake, Call", "Assess, Bleed, Cover"]'::jsonb, 1, 'Airway, Breathing, Circulation', 'Open the Airway, check Breathing, then check Circulation — the order that keeps a casualty alive.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q37', 3, 'emergency_response', 'When protecting a crash scene on the highway, warning triangles or signs should be placed roughly:', '["Right next to the wreck", "Well back — about 100 metres — to warn approaching traffic", "Only behind your own car", "Nowhere; just wave your hand"]'::jsonb, 1, 'Well back — about 100 metres — to warn approaching traffic', 'Placing warnings well upstream gives fast traffic time to slow before reaching the scene and the rescuers.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q38', 3, 'emergency_response', 'An unconscious casualty who is breathing normally is best placed:', '["Flat on their back with the head raised", "On their side in the recovery position to keep the airway clear", "Sitting upright against a wall", "Face down on their stomach"]'::jsonb, 1, 'On their side in the recovery position to keep the airway clear', 'The recovery position stops the tongue or vomit from blocking the airway while help is on the way.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q39', 3, 'emergency_response', 'At a crash with several casualties, first aiders should:', '["Move the dead bodies first", "Treat the most severely injured first and move the deceased last", "Help whoever shouts loudest", "Wait until everyone is calm"]'::jsonb, 1, 'Treat the most severely injured first and move the deceased last', 'Priority goes to the critically injured; the deceased are moved last so effort is spent saving the living.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q40', 3, 'emergency_response', 'A petrol or fuel fire in a vehicle (a Class B fire) is best tackled with:', '["A jet of water", "A dry-chemical powder or carbon-dioxide extinguisher", "Fanning it with a cloth", "Adding more fuel"]'::jsonb, 1, 'A dry-chemical powder or carbon-dioxide extinguisher', 'Water spreads burning fuel; dry powder or CO2 smothers the flames by cutting off the oxygen.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q41', 3, 'vehicle_control', 'If the back of your car begins to skid to the right, you should generally:', '["Brake hard and hold the wheel still", "Steer gently in the same direction as the skid and ease off the accelerator", "Accelerate hard", "Yank the handbrake"]'::jsonb, 1, 'Steer gently in the same direction as the skid and ease off the accelerator', 'Steering into the skid and easing off power helps the tyres regain grip; harsh braking makes it worse.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q42', 3, 'vehicle_control', 'To move off smoothly on an uphill slope without rolling back, you should:', '["Rely only on the accelerator", "Balance the clutch and accelerator as you release the handbrake", "Switch off the engine first", "Coast in neutral"]'::jsonb, 1, 'Balance the clutch and accelerator as you release the handbrake', 'Co-ordinating clutch, accelerator and handbrake holds the car still, then pulls away without rolling back.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q43', 3, 'vehicle_control', 'In good, dry conditions a safe minimum following gap behind the vehicle ahead is about:', '["Half a second", "Two seconds", "No gap is needed", "Ten car lengths at any speed"]'::jsonb, 1, 'Two seconds', 'The two-second rule scales with speed and gives time to react; double it in the wet.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q44', 3, 'vehicle_condition', 'A quick daily pre-drive check of Water, Oil, Fan belt and Tyres helps mainly to:', '["Make the car look clean", "Catch faults early and prevent breakdowns or crashes", "Increase the top speed", "Reduce the price of fuel"]'::jsonb, 1, 'Catch faults early and prevent breakdowns or crashes', 'Simple routine checks of fluids, belt and tyres spot problems before they strand you or fail at speed.', 120, 80, ''),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q45', 3, 'vehicle_condition', 'Worn, smooth tyres are dangerous chiefly because they:', '["Make the car quieter", "Lose grip, especially on wet roads, lengthening the stopping distance", "Improve fuel economy", "Only look older"]'::jsonb, 1, 'Lose grip, especially on wet roads, lengthening the stopping distance', 'Tread channels water away; bald tyres cannot grip a wet road and greatly increase the risk of skidding.', 120, 80, '')
ON CONFLICT (bank_key, rubric_version, external_id) WHERE competition_id IS NULL DO NOTHING;

COMMIT;
