-- Arena quiz bank (Naija Driver 90-question seed). ADDITIVE ONLY.
-- One shared bank feeds BOTH the public Play-Along rail AND the proctored Theory
-- exam. Bank questions are immutable templates (competition_id NULL); import binds
-- a competition-scoped copy. Attempts are append-only + idempotent.
-- Merit firewall (NDC-1): Play-Along attempts write ONLY arena_quiz_attempt +
-- arena_engagement_event, NEVER arena_merit_entry. Exam merit is minted ONLY
-- through the signed TheoryExamAdapter at proctor attestation (NDC-2).
-- No DROP / RENAME / type-narrowing. Safe to re-run.

-- ── Quiz question bank (immutable) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS arena_quiz_question (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id     UUID REFERENCES arena_competition(id) ON DELETE CASCADE, -- NULL = template bank
  bank_key           TEXT NOT NULL,
  rubric_version     TEXT NOT NULL,
  external_id        TEXT NOT NULL,                 -- e.g. ND-S1-Q01 (public handle)
  stage              INTEGER NOT NULL CHECK (stage IN (1,2,3)),
  category           TEXT,
  prompt             TEXT NOT NULL,
  options            JSONB NOT NULL,                -- array of 4 strings
  correct_index      INTEGER NOT NULL CHECK (correct_index BETWEEN 0 AND 3),
  correct_answer     TEXT,
  explanation        TEXT,
  time_limit_seconds INTEGER NOT NULL DEFAULT 120,
  pass_mark_percent  INTEGER,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Template uniqueness: one row per (bank,rubric,external) for the template bank.
CREATE UNIQUE INDEX IF NOT EXISTS arena_quiz_question_template_key
  ON arena_quiz_question (bank_key, rubric_version, external_id)
  WHERE competition_id IS NULL;
-- Bound uniqueness: one imported copy per (competition, external_id).
CREATE UNIQUE INDEX IF NOT EXISTS arena_quiz_question_bound_key
  ON arena_quiz_question (competition_id, external_id)
  WHERE competition_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS arena_quiz_question_bank_stage_idx
  ON arena_quiz_question (bank_key, rubric_version, stage);

-- ── Quiz attempts (append-only, idempotent) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS arena_quiz_attempt (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id   UUID NOT NULL,
  mode             TEXT NOT NULL CHECK (mode IN ('PLAYALONG','THEORY_EXAM')),
  taker_id         UUID NOT NULL,                  -- spectator or contestant user id
  contestant_id    UUID,                           -- set for THEORY_EXAM
  stage            INTEGER,
  batch            TEXT,                            -- B1/B2/B3 for exams
  rubric_version   TEXT,
  responses        JSONB NOT NULL DEFAULT '[]'::jsonb, -- [{question_external_id, option_index, correct}]
  score            INTEGER NOT NULL DEFAULT 0,
  total            INTEGER NOT NULL DEFAULT 0,
  passed           BOOLEAN NOT NULL DEFAULT false,
  response_time_ms BIGINT,
  idempotency_key  TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (idempotency_key)
);
CREATE INDEX IF NOT EXISTS arena_quiz_attempt_taker_idx
  ON arena_quiz_attempt (competition_id, mode, taker_id);
CREATE INDEX IF NOT EXISTS arena_quiz_attempt_contestant_idx
  ON arena_quiz_attempt (competition_id, contestant_id, stage);

-- ── Immutability: reuse arena_block_mutation (defined in 20260824000000) ──────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'arena_block_mutation') THEN
    CREATE OR REPLACE FUNCTION arena_block_mutation() RETURNS trigger AS $fn$
    BEGIN
      RAISE EXCEPTION 'append-only table %: UPDATE/DELETE forbidden', TG_TABLE_NAME;
    END;
    $fn$ LANGUAGE plpgsql;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='arena_quiz_question_immutable') THEN
    CREATE TRIGGER arena_quiz_question_immutable BEFORE UPDATE OR DELETE ON arena_quiz_question
      FOR EACH ROW EXECUTE FUNCTION arena_block_mutation();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='arena_quiz_attempt_immutable') THEN
    CREATE TRIGGER arena_quiz_attempt_immutable BEFORE UPDATE OR DELETE ON arena_quiz_attempt
      FOR EACH ROW EXECUTE FUNCTION arena_block_mutation();
  END IF;
END $$;

-- ── RLS: public read of the bank (contestant-safe fields stripped in the app
--    layer); all writes via service-role backend. Attempts are backend-only. ──
ALTER TABLE arena_quiz_question ENABLE ROW LEVEL SECURITY;
ALTER TABLE arena_quiz_attempt  ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='arena_quiz_question' AND policyname='quiz_question_public_read') THEN
    CREATE POLICY quiz_question_public_read ON arena_quiz_question FOR SELECT USING (true);
  END IF;
  -- arena_quiz_attempt: no anon/authenticated policy → service-role only.
END $$;

-- ── RBAC: arena.admin.questions (module arena, resource question, action manage)
BEGIN;

INSERT INTO public.permissions(name, slug, module, resource, action, description, is_system_permission)
VALUES
  ('Arena Questions', 'arena.admin.questions', 'arena', 'question', 'manage', 'Import/list/inspect the Arena quiz bank + stats', true)
ON CONFLICT (slug) DO NOTHING;

-- Grant to the arena config role (matches how arena.admin.config is granted).
WITH role_row AS (SELECT id FROM public.roles WHERE slug = 'arena-admin'),
     perms AS (SELECT id FROM public.permissions WHERE slug IN ('arena.admin.questions'))
INSERT INTO public.role_permissions(role_id, permission_id)
SELECT role_row.id, perms.id FROM role_row, perms
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Grant to super-admin + system-admin (whichever platform roles exist).
WITH role_row AS (SELECT id FROM public.roles WHERE slug IN ('super-admin','super_admin','system-admin','system_admin')),
     perms AS (SELECT id FROM public.permissions WHERE slug IN ('arena.admin.questions'))
INSERT INTO public.role_permissions(role_id, permission_id)
SELECT role_row.id, perms.id FROM role_row, perms
ON CONFLICT (role_id, permission_id) DO NOTHING;

COMMIT;

-- ── SEED: 90 Naija Driver questions (template bank; competition_id NULL) ──────
-- bank_key = naija_driver_safe_driving_assessment, rubric_version = naija_driver_v1.0.0.
-- pass_mark_percent from each stage's suggested_pass_mark_percent (S1=70, S2=75, S3=80).
-- Idempotent: ON CONFLICT (bank_key, rubric_version, external_id) [template] DO NOTHING.
INSERT INTO arena_quiz_question
  (competition_id, bank_key, rubric_version, external_id, stage, category, prompt, options, correct_index, correct_answer, explanation, time_limit_seconds, pass_mark_percent)
VALUES
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q01', 1, 'road_signs', 'In Nigeria, what shape are most warning signs (e.g. ''bend ahead'', ''narrow bridge'')?', '["Rectangular", "Triangular", "Circular", "Octagonal"]'::jsonb, 1, 'Triangular', 'Triangular signs warn of hazards ahead. Circular signs give orders; rectangular signs give information.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q02', 1, 'road_signs', 'A circular road sign with a red border generally means:', '["Information for drivers", "A warning of danger ahead", "Parking is permitted", "Prohibition — something is not allowed"]'::jsonb, 3, 'Prohibition — something is not allowed', 'Red-bordered circles are prohibitive/regulatory signs, e.g. ''No entry'', ''No overtaking''.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q03', 1, 'traffic_rules', 'What must you do at a red traffic light?', '["Stop only if pedestrians are crossing", "Slow down and proceed if clear", "Sound your horn and proceed", "Stop completely behind the stop line"]'::jsonb, 3, 'Stop completely behind the stop line', 'Red means a complete stop behind the stop line until the light turns green.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q04', 1, 'traffic_rules', 'A flashing amber (yellow) traffic light means:', '["Stop and wait for green", "Speed up before it turns red", "The light is broken — ignore it", "Proceed with caution, giving way where required"]'::jsonb, 3, 'Proceed with caution, giving way where required', 'Flashing amber allows you to proceed carefully while giving way to pedestrians and other traffic as required.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q05', 1, 'traffic_rules', 'Which agency is primarily responsible for road traffic safety and driver''s licensing in Nigeria?', '["NAFDAC", "FRSC (Federal Road Safety Corps)", "NDLEA", "EFCC"]'::jsonb, 1, 'FRSC (Federal Road Safety Corps)', 'The FRSC administers road safety, driver''s licences and highway regulations in Nigeria.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q06', 1, 'emergency_response', 'What is the FRSC national toll-free emergency number?', '["767", "122", "199", "911"]'::jsonb, 1, '122', 'Dial 122 (toll-free) to reach the FRSC in a road emergency or crash.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q07', 1, 'documentation', 'The minimum age to obtain a driver''s licence in Nigeria is:', '["16 years", "18 years", "17 years", "21 years"]'::jsonb, 1, '18 years', 'You must be at least 18 years old to hold a Nigerian driver''s licence.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q08', 1, 'traffic_rules', 'In Nigeria, vehicles are driven on which side of the road?', '["Either side", "The left side", "The right side", "The centre of the road"]'::jsonb, 2, 'The right side', 'Nigeria uses right-hand traffic: keep right, and overtaking is normally done on the left.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q09', 1, 'traffic_rules', 'A zebra crossing is designed for:', '["Cyclists to ride across", "Vehicles to overtake", "Animals to cross", "Pedestrians to cross the road safely"]'::jsonb, 3, 'Pedestrians to cross the road safely', 'Zebra crossings give pedestrians priority; drivers must slow down and stop for people on the crossing.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q10', 1, 'road_signs', 'A red octagonal (eight-sided) sign always means:', '["STOP", "No parking", "Give way", "Danger ahead"]'::jsonb, 0, 'STOP', 'The octagon is reserved for STOP: come to a complete halt before proceeding.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q11', 1, 'documentation', 'Which of these is NOT a document you are required to have for your vehicle?', '["Driver''s licence", "International passport", "Certificate of roadworthiness", "Vehicle insurance certificate"]'::jsonb, 1, 'International passport', 'Required papers include your licence, insurance, roadworthiness and proof of ownership — not a passport.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q12', 1, 'documentation', 'A standard Nigerian driver''s licence is issued with a validity of:', '["3 or 5 years", "10 years", "1 year", "2 years"]'::jsonb, 0, '3 or 5 years', 'FRSC issues driver''s licences with 3-year and 5-year validity options.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q13', 1, 'road_signs', 'A triangular sign with an exclamation mark (!) means:', '["End of speed limit", "Road permanently closed", "General danger/hazard ahead", "Filling station ahead"]'::jsonb, 2, 'General danger/hazard ahead', 'The exclamation triangle is a general warning: slow down and be prepared for a hazard.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q14', 1, 'traffic_rules', 'A green traffic light means:', '["Go immediately regardless of traffic", "Proceed only if the junction is clear and safe", "Pedestrians have right of way over you in all directions", "Prepare to stop"]'::jsonb, 1, 'Proceed only if the junction is clear and safe', 'Green permits you to go, but only when your exit and the junction are clear and it is safe.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q15', 1, 'road_signs', 'A road sign showing two children walking usually warns of:', '["No minors allowed on this road", "A school or children crossing ahead", "A playground for adults", "A toy market ahead"]'::jsonb, 1, 'A school or children crossing ahead', 'Slow down near school zones — children may cross suddenly.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q16', 1, 'road_signs', 'Rectangular road signs are generally used to:', '["Provide information or direction", "Give compulsory orders", "Indicate speed limits only", "Warn of danger"]'::jsonb, 0, 'Provide information or direction', 'Rectangles are informative signs: directions, distances, facilities and services.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q17', 1, 'documentation', 'Every vehicle in Nigeria must display:', '["Number plates at the front and rear", "A tinted-glass permit", "The owner''s photograph", "A national flag"]'::jsonb, 0, 'Number plates at the front and rear', 'Valid number plates must be fixed and clearly visible at the front and rear of the vehicle.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q18', 1, 'traffic_rules', 'When the traffic light changes from green to amber (yellow), you should:', '["Sound your horn and continue", "Reverse away from the junction", "Prepare to stop safely before the line", "Accelerate to beat the red"]'::jsonb, 2, 'Prepare to stop safely before the line', 'Amber means stop if you can do so safely — never accelerate to ''beat'' the light.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q19', 1, 'road_signs', 'A continuous (unbroken) white line in the centre of the road means:', '["It marks a bus lane", "It marks a parking zone", "Overtaking is allowed at any time", "Do not cross or overtake across the line"]'::jsonb, 3, 'Do not cross or overtake across the line', 'A solid centre line prohibits crossing or overtaking because visibility or conditions are unsafe.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q20', 1, 'road_signs', 'A broken white centre line means:', '["The road ends ahead", "No overtaking at any time", "You may overtake when it is safe to do so", "It is a one-way street"]'::jsonb, 2, 'You may overtake when it is safe to do so', 'Broken lines allow crossing/overtaking, but only when you can see it is completely safe.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q21', 1, 'speed_limits', 'The general speed limit for cars in built-up areas (towns and cities) in Nigeria is:', '["50 km/h", "100 km/h", "30 km/h", "80 km/h"]'::jsonb, 0, '50 km/h', 'In built-up areas the limit for cars is 50 km/h due to pedestrians, junctions and heavy activity.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q22', 1, 'safe_practice', 'Before starting to drive, the first things to adjust are your:', '["Number plates", "Seat and mirrors", "Tyres", "Radio and air-conditioner"]'::jsonb, 1, 'Seat and mirrors', 'A correct seating position and properly set mirrors are essential for control and visibility.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q23', 1, 'safe_practice', 'Seat belts must be worn by:', '["The driver only", "Only on expressways", "The driver and all passengers", "Front-seat occupants only"]'::jsonb, 2, 'The driver and all passengers', 'Nigerian law requires the driver and all passengers to use seat belts on every trip.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q24', 1, 'road_signs', 'The ''No Entry'' sign is best described as:', '["A yellow triangle", "A blue square with an arrow", "A red circle with a white horizontal bar", "A green circle"]'::jsonb, 2, 'A red circle with a white horizontal bar', 'The red disc with a white bar means the road is closed to traffic in that direction.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q25', 1, 'safe_practice', 'Where there is no footpath, pedestrians should walk:', '["In the middle of the road", "With their back to traffic", "Only at night", "Facing oncoming traffic"]'::jsonb, 3, 'Facing oncoming traffic', 'Facing traffic lets pedestrians see approaching vehicles and step aside in time.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q26', 1, 'traffic_rules', 'Sounding your horn near a hospital or in a marked ''silence zone'' is:', '["Allowed only at night", "Encouraged", "Compulsory", "Prohibited"]'::jsonb, 3, 'Prohibited', 'Horns are banned in silence zones such as hospital areas; the sign shows a crossed-out horn.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q27', 1, 'documentation', 'Third-party motor insurance covers:', '["Theft of your own car", "All damage to your own car", "Injury or damage you cause to other people and their property", "Your fuel costs"]'::jsonb, 2, 'Injury or damage you cause to other people and their property', 'Third-party cover is the legal minimum: it protects others against loss you cause, not your own vehicle.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q28', 1, 'documentation', 'A certificate of roadworthiness confirms that:', '["The owner has paid income tax", "The vehicle is mechanically fit to be on the road", "The car has been washed", "The driver can drive well"]'::jsonb, 1, 'The vehicle is mechanically fit to be on the road', 'Roadworthiness certifies the vehicle''s brakes, lights, tyres and body are in safe condition.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q29', 1, 'safe_practice', 'When approaching a junction with no signs or traffic lights, you should:', '["Slow down, look both ways and be ready to give way", "Speed through quickly before others arrive", "Flash your headlights and continue", "Sound your horn and continue at speed"]'::jsonb, 0, 'Slow down, look both ways and be ready to give way', 'Uncontrolled junctions demand reduced speed and readiness to stop for crossing traffic.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S1-Q30', 1, 'documentation', 'A learner driver in Nigeria must:', '["Display ''L'' plates and be accompanied by a licensed driver", "Avoid all main roads permanently", "Drive only at night", "Drive only automatic cars"]'::jsonb, 0, 'Display ''L'' plates and be accompanied by a licensed driver', 'Learners must show L plates and drive under the supervision of a fully licensed driver.', 120, 70),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q01', 2, 'safe_practice', 'The ''two-second rule'' is used to:', '["Time traffic lights", "Keep a safe following distance from the vehicle ahead", "Calculate fuel consumption", "Measure engine speed"]'::jsonb, 1, 'Keep a safe following distance from the vehicle ahead', 'Pick a fixed point; if you pass it less than two seconds after the car ahead, you are too close.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q02', 2, 'night_weather', 'On wet roads or in rain, your following distance should be:', '["The same as in dry weather", "Ignored because of the wipers", "Reduced to stay in convoy", "At least doubled — about four seconds"]'::jsonb, 3, 'At least doubled — about four seconds', 'Wet roads can double stopping distances, so double your gap to at least four seconds.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q03', 2, 'overtaking', 'In Nigeria (right-hand traffic), you should normally overtake other vehicles on the:', '["Left side", "Either side freely", "Right side", "Road shoulder"]'::jsonb, 0, 'Left side', 'With traffic keeping right, overtaking is done on the left, returning right when safely clear.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q04', 2, 'overtaking', 'It is most dangerous to overtake:', '["During daylight", "At bends, hilltops, junctions and pedestrian crossings", "On a dual carriageway", "On a straight, clear road"]'::jsonb, 1, 'At bends, hilltops, junctions and pedestrian crossings', 'Never overtake where your view of oncoming traffic or crossing hazards is blocked.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q05', 2, 'speed_limits', 'The maximum speed limit for private cars on Nigerian expressways is:', '["140 km/h", "100 km/h", "80 km/h", "120 km/h"]'::jsonb, 1, '100 km/h', 'Cars are limited to 100 km/h on expressways (80 km/h on other highways, 50 km/h in town).', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q06', 2, 'safe_practice', 'The legal blood alcohol concentration (BAC) limit for drivers in Nigeria is:', '["0.00% — but only for learners", "0.50%", "0.10%", "0.05%"]'::jsonb, 3, '0.05%', 'FRSC enforces a 0.05 g/100ml BAC limit; the safest choice is not to drink at all before driving.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q07', 2, 'safe_practice', 'Using a handheld mobile phone while driving is:', '["Allowed for business calls", "A punishable traffic offence", "Allowed if the call is short", "Allowed in slow traffic"]'::jsonb, 1, 'A punishable traffic offence', 'Phone use while driving is an FRSC offence — it multiplies your crash risk. Park safely to make calls.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q08', 2, 'speed_limits', 'FRSC requires commercial vehicles in Nigeria to be fitted with:', '["A speed limiting device", "A television screen", "External loudspeakers", "Extra roof seats"]'::jsonb, 0, 'A speed limiting device', 'Speed limiters are mandatory on commercial vehicles to curb overspeeding, the top cause of crashes.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q09', 2, 'vehicle_condition', 'The minimum legal tyre tread depth is generally:', '["1.6 mm", "0.5 mm", "10 mm", "5 mm"]'::jsonb, 0, '1.6 mm', 'Below 1.6 mm of tread, grip in the wet collapses and the tyre is illegal — check tyres weekly.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q10', 2, 'overtaking', 'When another vehicle is overtaking you, you should:', '["Brake suddenly", "Swerve towards it to warn the driver", "Accelerate so it cannot pass", "Maintain or slightly reduce your speed and keep right"]'::jsonb, 3, 'Maintain or slightly reduce your speed and keep right', 'Help the overtaker pass safely; speeding up prolongs the manoeuvre and creates danger.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q11', 2, 'safe_practice', 'The correct routine before changing lanes is:', '["Signal only, then move", "Horn, then swerve", "Mirror — Signal — check blind spot — then Manoeuvre", "Brake, turn, then signal"]'::jsonb, 2, 'Mirror — Signal — check blind spot — then Manoeuvre', 'The MSM routine with a blind-spot (shoulder) check prevents side-swipe collisions.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q12', 2, 'safe_practice', 'You should signal your intention to turn:', '["In good time — at least about 30 metres before the turn", "At the exact moment of turning", "Only when other cars are visible", "After completing the turn"]'::jsonb, 0, 'In good time — at least about 30 metres before the turn', 'Early, clear signals give other road users time to react to your intentions.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q13', 2, 'safe_practice', 'Leaving a broken-down vehicle on the road at night without lights or reflectors is:', '["Allowed on expressways only", "A serious hazard and an offence", "Normal practice on quiet roads", "Acceptable if you will return soon"]'::jsonb, 1, 'A serious hazard and an offence', 'Unlit stationary vehicles cause fatal night crashes — use hazard lights and place your warning triangle.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q14', 2, 'safe_practice', '''Tailgating'' means:', '["Following the vehicle ahead too closely", "Reversing on a highway", "Overtaking on the shoulder", "Driving with the boot open"]'::jsonb, 0, 'Following the vehicle ahead too closely', 'Tailgating removes your stopping margin; if the car ahead brakes hard, you will hit it.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q15', 2, 'traffic_rules', 'At a zebra crossing, the right of way belongs to:', '["Pedestrians on the crossing", "Commercial buses", "Motorcycles", "The fastest approaching vehicle"]'::jsonb, 0, 'Pedestrians on the crossing', 'Slow down on approach and stop for anyone on or stepping onto the crossing.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q16', 2, 'night_weather', 'In heavy rain during the day, you should:', '["Use hazard lights while moving", "Use full beam headlights", "Switch on dipped (low beam) headlights", "Drive with no lights to save the battery"]'::jsonb, 2, 'Switch on dipped (low beam) headlights', 'Dipped headlights make you visible in rain and spray; hazard lights while moving confuse other drivers.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q17', 2, 'night_weather', 'If dazzled by the high beams of an oncoming vehicle at night:', '["Stop suddenly in your lane", "Slow down and look towards the right edge of the road", "Close your eyes briefly until it passes", "Flash your lights repeatedly and speed up"]'::jsonb, 1, 'Slow down and look towards the right edge of the road', 'Using the road edge as a guide keeps you on course until your vision recovers.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q18', 2, 'vehicle_condition', 'Overloading a vehicle beyond its rated capacity:', '["Reduces braking efficiency and stability, and is an offence", "Is allowed for short trips", "Saves fuel", "Improves road grip"]'::jsonb, 0, 'Reduces braking efficiency and stability, and is an offence', 'Excess load lengthens braking distance, strains tyres and destabilises the vehicle.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q19', 2, 'safe_practice', 'Young children travelling in a car should:', '["Sit on the driver''s lap", "Sit in front without a belt", "Stand between the front seats", "Sit in the back seat, properly restrained"]'::jsonb, 3, 'Sit in the back seat, properly restrained', 'The back seat with an appropriate restraint is the safest position for children.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q20', 2, 'traffic_rules', 'When entering a roundabout, you should give way to:', '["Only trucks and tankers", "Nobody — first come, first served", "Vehicles behind you", "Traffic already circulating in the roundabout"]'::jsonb, 3, 'Traffic already circulating in the roundabout', 'Vehicles already in the roundabout have priority; enter only when there is a safe gap.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q21', 2, 'safe_practice', 'Hazard warning lights should be used:', '["When your vehicle is stationary and causing an obstruction, or in an emergency", "Whenever you overtake", "While driving normally in light rain", "To thank other drivers"]'::jsonb, 0, 'When your vehicle is stationary and causing an obstruction, or in an emergency', 'Hazard lights warn of danger or breakdown — using them while moving normally misleads other drivers.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q22', 2, 'safe_practice', '''Defensive driving'' means:', '["Fitting protective bars to your vehicle", "Driving very slowly at all times", "Anticipating hazards and the mistakes of other road users", "Driving aggressively to defend your lane"]'::jsonb, 2, 'Anticipating hazards and the mistakes of other road users', 'A defensive driver expects errors from others and always leaves room and time to respond.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q23', 2, 'safe_practice', 'If you begin to feel sleepy while driving, the safest action is to:', '["Stop in a safe place and rest", "Drive faster to finish the trip quickly", "Turn up the music loudly", "Open the window and continue"]'::jsonb, 0, 'Stop in a safe place and rest', 'No trick beats sleep. A short nap in a safe place can save your life — fatigue kills.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q24', 2, 'safe_practice', 'On long journeys, FRSC advises drivers to take a rest break:', '["Every ten hours", "About every two hours, or whenever tired", "Never — breaks waste time", "Only when fuel runs out"]'::jsonb, 1, 'About every two hours, or whenever tired', 'Regular breaks keep reaction time sharp; fatigue builds up silently on long trips.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q25', 2, 'safe_practice', 'When passing motorcyclists (okada) and cyclists, you should:', '["Force them onto the shoulder", "Pass as closely as possible", "Give them extra clearance and reduce speed", "Sound your horn continuously"]'::jsonb, 2, 'Give them extra clearance and reduce speed', 'Two-wheelers can wobble or swerve around potholes — leave generous side space.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q26', 2, 'speed_limits', 'Compared with private cars, tankers and trailers are subject to:', '["Higher speed limits", "Exactly the same limits", "No speed limits", "Lower speed limits"]'::jsonb, 3, 'Lower speed limits', 'Heavy vehicles need far longer to stop, so their limits (e.g. 45–60 km/h) are lower than cars''.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q27', 2, 'safe_practice', 'The recommended way to hold the steering wheel is:', '["Steering with the knees on straight roads", "One hand resting at the bottom", "Both hands on the wheel, about the 9 and 3 o''clock position", "One finger on the rim"]'::jsonb, 2, 'Both hands on the wheel, about the 9 and 3 o''clock position', 'Two hands at 9 and 3 give maximum control for emergency steering.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q28', 2, 'safe_practice', 'When joining an expressway from a slip road (acceleration lane), you should:', '["Reverse if no gap appears", "Stop at the end of the lane and wait", "Merge immediately at very low speed", "Build up speed to match traffic and merge when there is a safe gap"]'::jsonb, 3, 'Build up speed to match traffic and merge when there is a safe gap', 'Matching traffic speed lets you merge smoothly without forcing others to brake.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q29', 2, 'safe_practice', 'Wearing a seat belt in a crash roughly:', '["Only helps below 30 km/h", "Halves your risk of death or serious injury", "Doubles your risk of injury", "Makes no measurable difference"]'::jsonb, 1, 'Halves your risk of death or serious injury', 'Belts cut the risk of death for front-seat occupants by about 45–50% — buckle up every trip.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S2-Q30', 2, 'safe_practice', 'At a railway level crossing without barriers or lights, you should:', '["Stop, look both ways and listen before crossing", "Drive across as quickly as possible", "Follow the vehicle in front without checking", "Sound your horn and cross"]'::jsonb, 0, 'Stop, look both ways and listen before crossing', 'Trains cannot stop for you. Cross only after confirming the line is completely clear.', 120, 75),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q01', 3, 'emergency_response', 'If your brakes fail while driving, you should first:', '["Accelerate to escape the traffic around you", "Switch off the engine and remove the key", "Jump out of the moving vehicle", "Pump the brake pedal, shift to a lower gear and apply the handbrake gradually"]'::jsonb, 3, 'Pump the brake pedal, shift to a lower gear and apply the handbrake gradually', 'Pumping may restore pressure; engine braking and gradual handbrake use scrub off speed under control.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q02', 3, 'emergency_response', 'If a tyre bursts at speed, you should:', '["Grip the steering firmly, ease off the accelerator and slow down gradually", "Swerve quickly to the shoulder at speed", "Switch off the ignition at once", "Brake as hard as possible immediately"]'::jsonb, 0, 'Grip the steering firmly, ease off the accelerator and slow down gradually', 'Hard braking or sharp steering after a blowout causes loss of control — decelerate smoothly first.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q03', 3, 'hazard_perception', '''Aquaplaning'' (hydroplaning) happens when:', '["Tyres lose contact with the road on a film of water", "The road surface is dusty", "The wipers stop working", "The engine floods with fuel"]'::jsonb, 0, 'Tyres lose contact with the road on a film of water', 'At speed on standing water, tyres ride on the water film and steering and braking stop working.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q04', 3, 'emergency_response', 'If your car begins to aquaplane, you should:', '["Brake as hard as possible", "Ease off the accelerator, keep the steering straight and avoid braking suddenly", "Accelerate through the water", "Turn the wheel sharply to regain grip"]'::jsonb, 1, 'Ease off the accelerator, keep the steering straight and avoid braking suddenly', 'Lifting off gently lets the tyres slow and regain contact; sudden inputs cause a skid.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q05', 3, 'emergency_response', 'If your vehicle catches fire while driving:', '["Keep driving to the nearest mechanic", "Continue slowly with the windows open", "Open the bonnet fully to inspect the flames", "Stop safely, switch off the ignition, get everyone out and away, then tackle only a small fire with an extinguisher"]'::jsonb, 3, 'Stop safely, switch off the ignition, get everyone out and away, then tackle only a small fire with an extinguisher', 'Life first: evacuate upwind and call for help. Never fully open a burning bonnet — it feeds the fire air.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q06', 3, 'emergency_response', 'On a highway, the warning triangle (C-caution) should be placed approximately:', '["200 metres ahead of the vehicle", "45 metres behind the vehicle", "5 metres behind the vehicle", "On the roof of the vehicle"]'::jsonb, 1, '45 metres behind the vehicle', 'About 45 m gives approaching traffic time to see and react before reaching your vehicle.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q07', 3, 'emergency_response', 'To correct a rear-wheel skid, you should:', '["Accelerate hard out of it", "Pull the handbrake firmly", "Ease off the pedals and steer gently in the direction the rear is sliding", "Brake hard and steer away from the skid"]'::jsonb, 2, 'Ease off the pedals and steer gently in the direction the rear is sliding', 'Steering into the skid realigns the car; harsh braking or power makes the slide worse.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q08', 3, 'night_weather', 'The most important rule for night driving is:', '["Follow the tail lights ahead closely", "Use hazard lights while moving", "Use full beam at all times", "Never drive faster than you can stop within the distance your headlights show"]'::jsonb, 3, 'Never drive faster than you can stop within the distance your headlights show', 'If a hazard appears at the edge of your beam, you must be able to stop before reaching it.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q09', 3, 'night_weather', 'When meeting an oncoming vehicle at night, you should:', '["Flash your lights repeatedly", "Switch off your lights completely", "Dip your headlights to low beam", "Keep full beam on for better vision"]'::jsonb, 2, 'Dip your headlights to low beam', 'Dipping prevents dazzling the other driver — a dazzled driver may drift into your lane.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q10', 3, 'night_weather', 'During harmattan haze or fog, you should:', '["Drive at normal speed to exit the fog quickly", "Use full beam to see farther", "Use dipped headlights or fog lights, reduce speed and increase following distance", "Use only parking lights"]'::jsonb, 2, 'Use dipped headlights or fog lights, reduce speed and increase following distance', 'Full beam reflects off haze and blinds you; slow down and extend your gap — visibility can drop suddenly.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q11', 3, 'emergency_response', 'Arriving first at a crash scene, your first action should be to:', '["Start moving all victims immediately", "Take photographs before anything else", "Drive past quickly to avoid delay", "Park safely, switch on hazard lights, protect the scene and call 122"]'::jsonb, 3, 'Park safely, switch on hazard lights, protect the scene and call 122', 'Securing the scene prevents a second crash; then summon FRSC/emergency services on 122.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q12', 3, 'emergency_response', 'A crash victim with a suspected neck or spinal injury should be:', '["Carried on someone''s back to a car", "Given water to drink", "Left in position and not moved unless there is immediate danger such as fire", "Sat upright immediately to help breathing"]'::jsonb, 2, 'Left in position and not moved unless there is immediate danger such as fire', 'Movement can turn a spinal injury into permanent paralysis — wait for trained responders unless danger forces evacuation.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q13', 3, 'hazard_perception', 'Total stopping distance is made up of:', '["Engine size plus tyre width", "Speed minus reaction time", "Braking distance only", "Thinking (reaction) distance plus braking distance"]'::jsonb, 3, 'Thinking (reaction) distance plus braking distance', 'You travel a long way while reacting before the brakes even begin to work.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q14', 3, 'hazard_perception', 'If you double your speed, your braking distance becomes roughly:', '["Half as long", "Twice as long", "Exactly the same", "Four times as long"]'::jsonb, 3, 'Four times as long', 'Braking distance rises with the square of speed — small speed increases cost big stopping distance.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q15', 3, 'vehicle_condition', 'If the engine overheats, you should:', '["Open the radiator cap immediately to release pressure", "Pull over safely, switch off the engine and wait for it to cool before checking", "Pour cold water on the hot engine block", "Keep driving to burn off the heat"]'::jsonb, 1, 'Pull over safely, switch off the engine and wait for it to cool before checking', 'A hot radiator cap can erupt with scalding steam; cold water on a hot block can crack it.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q16', 3, 'hazard_perception', 'Sleeping inside a parked car with the engine and air-conditioner running is dangerous mainly because of:', '["Carbon monoxide poisoning", "Fuel gauge damage", "Tyre wear", "Battery drain"]'::jsonb, 0, 'Carbon monoxide poisoning', 'Exhaust fumes can seep into the cabin; carbon monoxide is odourless and can kill sleeping occupants.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q17', 3, 'hazard_perception', 'A ''black spot'' on a road refers to:', '["A location with a history of frequent crashes", "An oil stain on the tarmac", "A speed camera position", "A toll gate"]'::jsonb, 0, 'A location with a history of frequent crashes', 'Approach marked black spots with extra caution and reduced speed.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q18', 3, 'hazard_perception', 'Strong crosswinds on bridges and exposed roads most affect:', '["High-sided vehicles, motorcycles — and any vehicle''s steering, so grip the wheel firmly", "Only small-engine cars", "Only parked vehicles", "Nothing on a modern car"]'::jsonb, 0, 'High-sided vehicles, motorcycles — and any vehicle''s steering, so grip the wheel firmly', 'Sudden gusts can push you off line, especially when passing trucks or gaps in buildings.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q19', 3, 'hazard_perception', 'A long articulated truck ahead signals and swings wide before a junction. You should:', '["Flash your lights to hurry it up", "Sound your horn and squeeze past", "Hold back — it needs extra room to complete its turn", "Quickly overtake through the gap it has opened"]'::jsonb, 2, 'Hold back — it needs extra room to complete its turn', 'Long vehicles swing out before turning; the ''gap'' will close on anything beside them.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q20', 3, 'hazard_perception', 'A defensive driver always maintains a ''space cushion'', meaning:', '["Extra passengers for balance", "A fully loaded boot", "Soft padded seats", "Space around the vehicle that allows an escape route if something goes wrong"]'::jsonb, 3, 'Space around the vehicle that allows an escape route if something goes wrong', 'Managing the space ahead, behind and beside you is the core of defensive driving.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q21', 3, 'emergency_response', 'In an emergency stop with ABS brakes, you should:', '["Pump the pedal rapidly", "Release the brake when the pedal vibrates", "Press the brake firmly, keep it pressed, and steer around the hazard if needed", "Use only the handbrake"]'::jsonb, 2, 'Press the brake firmly, keep it pressed, and steer around the hazard if needed', 'The pulsing pedal is ABS working — maintain firm pressure; ABS lets you steer while braking.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q22', 3, 'safe_practice', 'When descending a long, steep hill, you should:', '["Ride the brakes continuously all the way down", "Switch off the engine", "Shift to neutral to save fuel", "Engage a lower gear and use engine braking"]'::jsonb, 3, 'Engage a lower gear and use engine braking', 'Engine braking controls speed without overheating the brakes; neutral or engine-off removes control.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q23', 3, 'vehicle_condition', '''Brake fade'' is caused by:', '["Overheating of the brakes from continuous heavy use", "Driving too slowly", "Brand-new brake pads", "Very cold weather"]'::jsonb, 0, 'Overheating of the brakes from continuous heavy use', 'Overheated pads and fluid lose stopping power — a major danger on long descents.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q24', 3, 'night_weather', 'The safest approach to a flooded section of road is to:', '["Follow trucks through at their speed", "Cross with the clutch fully pressed", "Avoid it if possible; if you must cross, go slowly in a low gear and test your brakes afterwards", "Speed through so the engine does not stall"]'::jsonb, 2, 'Avoid it if possible; if you must cross, go slowly in a low gear and test your brakes afterwards', 'Water hides depth, washouts and open drains; wet brakes need gentle testing after crossing.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q25', 3, 'vehicle_condition', 'An unsecured or protruding load on a vehicle:', '["Improves the vehicle''s balance", "Is only illegal at night", "Is a serious hazard to other road users and an offence", "Is acceptable if tied loosely with rope"]'::jsonb, 2, 'Is a serious hazard to other road users and an offence', 'Falling loads cause multi-vehicle crashes; loads must be secured and within legal dimensions.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q26', 3, 'night_weather', 'At night or in heavy rain, the two-second following rule should be extended to at least:', '["It should be reduced", "One second", "Four seconds", "Half a second"]'::jsonb, 2, 'Four seconds', 'Lower visibility and grip demand a much bigger safety gap.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q27', 3, 'emergency_response', 'A pedestrian suddenly steps into your path. The safest reaction is usually to:', '["Accelerate past before they cross", "Swerve into the oncoming lane", "Brake firmly while keeping control and staying in your lane where possible", "Sound the horn and maintain speed"]'::jsonb, 2, 'Brake firmly while keeping control and staying in your lane where possible', 'Controlled firm braking sheds the most speed; swerving into traffic often trades one crash for a worse one.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q28', 3, 'documentation', 'FRSC requires vehicles to carry which safety items?', '["An umbrella and torch only", "A television and loudspeakers", "A fire extinguisher and a warning triangle (C-caution)", "A spare number plate"]'::jsonb, 2, 'A fire extinguisher and a warning triangle (C-caution)', 'The extinguisher and C-caution are mandatory equipment checked at FRSC inspections.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q29', 3, 'hazard_perception', 'Brief ''microsleeps'' while driving are a sign of:', '["Low fuel level", "The air-conditioner being too strong", "Good, relaxed concentration", "Dangerous fatigue — stop and rest immediately"]'::jsonb, 3, 'Dangerous fatigue — stop and rest immediately', 'A 3-second microsleep at 100 km/h means over 80 metres travelled blind.', 120, 80),
(NULL, 'naija_driver_safe_driving_assessment', 'naija_driver_v1.0.0', 'ND-S3-Q30', 3, 'hazard_perception', 'After long, fast expressway driving, when you enter a town your speed often:', '["No longer matters in built-up areas", "Cannot be measured accurately", "Feels slower than it really is — check your speedometer", "Feels faster than it really is"]'::jsonb, 2, 'Feels slower than it really is — check your speedometer', 'Speed adaptation tricks your senses; trust the speedometer and drop to the 50 km/h limit.', 120, 80)
ON CONFLICT (bank_key, rubric_version, external_id) WHERE competition_id IS NULL DO NOTHING;
