import type {
  Contest,
  Contestant,
  VotePackage,
  VoteTransaction,
  FreeVoteAllocation,
  LeaderboardEntry,
  VotingNotification,
} from '../types/voting.types';

// ─── Contests ─────────────────────────────────────────────────────────────────

export const MOCK_CONTESTS: Contest[] = [
  {
    id: 'c1',
    title: 'Spotlight Music Talent 2026',
    description: 'Nigeria\'s biggest music talent search. Vote for your favourite artist and help them win the grand prize of ₦5,000,000.',
    category: 'Music',
    status: 'LIVE',
    bannerImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    contestantCount: 48,
    totalVotes: 124_850,
    startsAt: '2026-05-01T00:00:00Z',
    endsAt: '2026-07-01T23:59:59Z',
    freeVotesPerDay: 5,
    paidVotingEnabled: true,
    sponsorName: 'MTN Nigeria',
    prizes: ['₦5,000,000 Grand Prize', '₦2,000,000 Runner Up', '₦500,000 People\'s Choice'],
    rules: ['18+ only', 'Nigerian citizens only', 'One entry per category'],
  },
  {
    id: 'c2',
    title: 'Best Fashion Designer 2026',
    description: 'Celebrate creativity and elegance. Vote for Nigeria\'s next top fashion designer.',
    category: 'Fashion',
    status: 'LIVE',
    bannerImage: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&q=80',
    contestantCount: 32,
    totalVotes: 87_400,
    startsAt: '2026-05-15T00:00:00Z',
    endsAt: '2026-06-30T23:59:59Z',
    freeVotesPerDay: 5,
    paidVotingEnabled: true,
    sponsorName: 'House of Tara',
    prizes: ['₦3,000,000 Grand Prize', '₦1,000,000 Runner Up'],
    rules: [],
  },
  {
    id: 'c3',
    title: 'Rising Comedy Stars',
    description: 'Who made Nigeria laugh the most? Vote for the funniest comedian of the year.',
    category: 'Comedy',
    status: 'UPCOMING',
    bannerImage: 'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&q=80',
    contestantCount: 0,
    totalVotes: 0,
    startsAt: '2026-07-15T00:00:00Z',
    endsAt: '2026-08-31T23:59:59Z',
    freeVotesPerDay: 5,
    paidVotingEnabled: true,
    prizes: ['₦2,000,000 Grand Prize'],
    rules: [],
  },
  {
    id: 'c4',
    title: 'Spotlight Dance Challenge',
    description: 'Show us your moves! Vote for the most electrifying dance crew in Nigeria.',
    category: 'Dance',
    status: 'CLOSED',
    bannerImage: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=80',
    contestantCount: 24,
    totalVotes: 310_000,
    startsAt: '2026-03-01T00:00:00Z',
    endsAt: '2026-05-31T23:59:59Z',
    freeVotesPerDay: 5,
    paidVotingEnabled: true,
    prizes: ['₦4,000,000 Grand Prize'],
    rules: [],
  },
];

// ─── Contestants ──────────────────────────────────────────────────────────────

export const MOCK_CONTESTANTS: Contestant[] = [
  {
    id: 'ct1',
    contestId: 'c1',
    name: 'Adaeze Okafor',
    stageName: 'Queen Ada',
    category: 'Afrobeats',
    state: 'Lagos',
    photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80',
    rank: 1,
    votes: 24_850,
    bio: 'Afrobeats sensation from Lagos with a voice that moves mountains. Ada has been performing since age 12 and is ready to take the world stage.',
    isVerified: true,
    status: 'ACTIVE',
    votesNeededToNextRank: 0,
    movement: 'UP',
    profileViews: 45_230,
    shareClicks: 3_421,
  },
  {
    id: 'ct2',
    contestId: 'c1',
    name: 'Emeka Nwosu',
    stageName: 'King E',
    category: 'Afropop',
    state: 'Anambra',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    rank: 2,
    votes: 21_200,
    bio: 'Born and raised in Onitsha, Emeka blends highlife roots with contemporary Afropop to create a sound uniquely his own.',
    isVerified: true,
    status: 'ACTIVE',
    votesNeededToNextRank: 3_650,
    movement: 'SAME',
    profileViews: 38_100,
    shareClicks: 2_890,
  },
  {
    id: 'ct3',
    contestId: 'c1',
    name: 'Fatima Bello',
    stageName: 'Fati B',
    category: 'R&B / Soul',
    state: 'Kano',
    photo: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&q=80',
    rank: 3,
    votes: 18_700,
    bio: 'Soulful singer-songwriter whose music tells the story of Northern Nigeria through a contemporary lens.',
    isVerified: false,
    status: 'ACTIVE',
    votesNeededToNextRank: 2_500,
    movement: 'UP',
    profileViews: 29_500,
    shareClicks: 1_700,
  },
  {
    id: 'ct4',
    contestId: 'c1',
    name: 'Chidi Eze',
    stageName: 'ChiGod',
    category: 'Rap / Hip-Hop',
    state: 'Enugu',
    photo: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&q=80',
    rank: 4,
    votes: 14_350,
    bio: 'Lyrical heavyweight who uses music to address social issues in Nigeria. Winner of three local rap battles.',
    isVerified: false,
    status: 'ACTIVE',
    votesNeededToNextRank: 4_350,
    movement: 'DOWN',
    profileViews: 21_000,
    shareClicks: 1_200,
  },
  {
    id: 'ct5',
    contestId: 'c1',
    name: 'Ngozi Adeyemi',
    stageName: 'NGO',
    category: 'Gospel',
    state: 'Ogun',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    rank: 5,
    votes: 12_100,
    bio: 'Gospel artist whose powerful vocals have moved thousands. NGO believes music is ministry.',
    isVerified: true,
    status: 'ACTIVE',
    votesNeededToNextRank: 2_250,
    movement: 'UP',
    profileViews: 18_900,
    shareClicks: 980,
  },
  {
    id: 'ct6',
    contestId: 'c1',
    name: 'Tunde Fashola',
    stageName: 'Tee-F',
    category: 'Afrobeats',
    state: 'Oyo',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    rank: 6,
    votes: 9_800,
    bio: 'Energetic performer known for high-octane stage shows and infectious dance moves.',
    isVerified: false,
    status: 'ACTIVE',
    votesNeededToNextRank: 2_300,
    movement: 'SAME',
    profileViews: 14_500,
    shareClicks: 760,
  },
];

// ─── Vote Packages ─────────────────────────────────────────────────────────────

export const MOCK_VOTE_PACKAGES: VotePackage[] = [
  {
    id: 'vp1',
    votes: 10,
    amount: 100_00,   // ₦100 in kobo
    currency: 'NGN',
    label: 'Starter',
  },
  {
    id: 'vp2',
    votes: 50,
    amount: 400_00,   // ₦400 in kobo
    currency: 'NGN',
    label: 'Popular',
    bonusVotes: 5,
    isPopular: true,
  },
  {
    id: 'vp3',
    votes: 150,
    amount: 1_000_00, // ₦1,000 in kobo
    currency: 'NGN',
    label: 'Power Pack',
    bonusVotes: 25,
    isBestValue: true,
  },
  {
    id: 'vp4',
    votes: 500,
    amount: 3_000_00, // ₦3,000 in kobo
    currency: 'NGN',
    label: 'Champion',
    bonusVotes: 100,
  },
];

// ─── Vote Transactions ────────────────────────────────────────────────────────

export const MOCK_VOTE_TRANSACTIONS: VoteTransaction[] = [
  {
    id: 'vt1',
    contestId: 'c1',
    contestantId: 'ct1',
    contestantName: 'Queen Ada',
    contestTitle: 'Spotlight Music Talent 2026',
    voteType: 'PAID',
    votes: 50,
    amount: 400_00,
    currency: 'NGN',
    status: 'SUCCESSFUL',
    reference: 'SPL-VT-2026-001',
    createdAt: '2026-06-13T14:32:00Z',
  },
  {
    id: 'vt2',
    contestId: 'c1',
    contestantId: 'ct1',
    contestantName: 'Queen Ada',
    contestTitle: 'Spotlight Music Talent 2026',
    voteType: 'FREE',
    votes: 5,
    status: 'SUCCESSFUL',
    reference: 'SPL-FV-2026-002',
    createdAt: '2026-06-13T10:00:00Z',
  },
  {
    id: 'vt3',
    contestId: 'c2',
    contestantId: 'ct3',
    contestantName: 'Fati B',
    contestTitle: 'Best Fashion Designer 2026',
    voteType: 'FREE',
    votes: 5,
    status: 'SUCCESSFUL',
    reference: 'SPL-FV-2026-003',
    createdAt: '2026-06-12T09:15:00Z',
  },
];

// ─── Free Vote Allocation ──────────────────────────────────────────────────────

export const MOCK_FREE_VOTE_ALLOCATION: FreeVoteAllocation = {
  total: 5,
  used: 2,
  remaining: 3,
  resetsAt: '2026-06-15T00:00:00Z',
};

// ─── Leaderboard ──────────────────────────────────────────────────────────────

export const MOCK_LEADERBOARD: LeaderboardEntry[] = MOCK_CONTESTANTS
  .filter((c) => c.contestId === 'c1')
  .map((c) => ({
    rank: c.rank,
    contestant: c,
    previousRank: c.movement === 'UP' ? c.rank + 1 : c.movement === 'DOWN' ? c.rank - 1 : c.rank,
    movement: c.movement,
  }));

// ─── Notifications ────────────────────────────────────────────────────────────

export const MOCK_VOTING_NOTIFICATIONS: VotingNotification[] = [
  {
    id: 'n1',
    type: 'FREE_VOTES_RESET',
    title: 'Your free votes have reset!',
    message: 'You have 5 new free votes ready to cast in Spotlight Music Talent 2026. Go vote now!',
    contestId: 'c1',
    createdAt: '2026-06-14T00:00:00Z',
    read: false,
  },
  {
    id: 'n2',
    type: 'RANK_CHANGED',
    title: 'Queen Ada moved to #1!',
    message: 'Your favourite contestant just took the lead in Spotlight Music Talent 2026.',
    contestId: 'c1',
    contestantId: 'ct1',
    createdAt: '2026-06-13T18:45:00Z',
    read: false,
  },
  {
    id: 'n3',
    type: 'VOTE_SUCCESS',
    title: 'Vote confirmed!',
    message: '50 votes cast for Queen Ada. Keep the momentum going!',
    contestId: 'c1',
    contestantId: 'ct1',
    createdAt: '2026-06-13T14:32:00Z',
    read: true,
  },
  {
    id: 'n4',
    type: 'CONTEST_ENDING',
    title: 'Voting closes in 48 hours!',
    message: 'Spotlight Music Talent 2026 ends on July 1. Cast your final votes now.',
    contestId: 'c1',
    createdAt: '2026-06-13T08:00:00Z',
    read: true,
  },
];
